/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface _SBIconProgressWaitingLoadingStateTransition : _SBIconProgressStateTransition

- (void)_updateView:(id)arg1;

@end
