/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface _SBIconProgressNoneWaitingStateTransition : _SBIconProgressStateTransition

- (void)_updateView:(id)arg1;

@end
