/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBCloseBoxView : SBHomeScreenButton {
    UITapGestureRecognizer * _actionTapGestureRecognizer;
    <SBCloseBoxViewDelegate> * _delegate;
    <SBIconListLayout> * _listLayout;
}

@property (nonatomic, retain) UITapGestureRecognizer *actionTapGestureRecognizer;
@property (nonatomic) <SBCloseBoxViewDelegate> *delegate;
@property (nonatomic, retain) <SBIconListLayout> *listLayout;

+ (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })backgroundInsets;

- (void).cxx_destruct;
- (id)actionTapGestureRecognizer;
- (id)delegate;
- (id)listLayout;
- (bool)pointInside:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (void)setActionTapGestureRecognizer:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setListLayout:(id)arg1;
- (bool)shouldTrack;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

@end
