/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBDefaultIconDragPreviewWindow : UIWindow <SBIconDragPreviewContaining>

@property (nonatomic, readonly) UIView *iconDragPreviewContainerView;

- (id)iconDragPreviewContainerView;

@end
