/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBFloatyFolderController : SBFolderController

@property (nonatomic) unsigned long long backgroundEffect;

+ (Class)_contentViewClass;
+ (Class)configurationClass;
+ (id)iconLocation;

- (unsigned long long)backgroundEffect;
- (id)floatyFolderView;
- (bool)isDisplayingIcon:(id)arg1 inLocation:(id)arg2;
- (bool)isDisplayingIconView:(id)arg1 inLocation:(id)arg2;
- (bool)isPresentingIconLocation:(id)arg1;
- (id)presentedIconLocations;
- (void)setBackgroundEffect:(unsigned long long)arg1;

@end
