/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBFloatyFolderView : SBFolderView <PTSettingsKeyObserver, SBFolderBackgroundViewDelegate, UIGestureRecognizerDelegate> {
    bool  _animatingRotation;
    unsigned long long  _backgroundEffect;
    SBIconView * _cachedHiddenIconView;
    bool  _convertingIconListStyle;
    bool  _displayingMultipleIconLists;
    bool  _displaysMultipleIconListsInLandscapeOrientation;
    SBHFolderSettings * _folderSettings;
    UILongPressGestureRecognizer * _longPressGesture;
    NSMutableArray * _pageBackgroundViews;
    NSMapTable * _pageBackgroundViewsForIconListViews;
    UIPinchGestureRecognizer * _pinchGesture;
    long long  _scalingViewPageIndex;
    SBFloatyFolderBackgroundClipView * _scrollClipView;
    UITapGestureRecognizer * _tapGesture;
}

@property (getter=isAnimatingRotation, nonatomic) bool animatingRotation;
@property (nonatomic) unsigned long long backgroundEffect;
@property (getter=isConvertingIconListStyle, nonatomic) bool convertingIconListStyle;
@property (nonatomic, readonly) double cornerRadius;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (getter=isDisplayingMultipleIconLists, nonatomic) bool displayingMultipleIconLists;
@property (nonatomic, readonly) bool displaysMultipleIconListsInLandscapeOrientation;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (Class)_scrollViewClass;
+ (unsigned long long)countOfAdditionalPagesToKeepVisibleInOneDirection;
+ (double)defaultCornerRadius;
+ (id)defaultIconLocation;

- (void).cxx_destruct;
- (void)_addIconListView:(id)arg1;
- (void)_configureGestures;
- (void)_convertToMultipleIconListsAnimated:(bool)arg1;
- (void)_convertToSingleIconListAnimated:(bool)arg1;
- (void)_currentPageIndexDidChange;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_frameForScalingView;
- (void)_handleLongPressGesture:(id)arg1;
- (void)_handleOutsideTap:(id)arg1;
- (void)_handlePinchGesture:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_iconListFrameForPageRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 atIndex:(unsigned long long)arg2;
- (void)_layoutSubviews;
- (id)_newPageBackgroundView;
- (double)_offsetToCenterPageControlInSpaceForPageControl;
- (void)_orientationDidChange:(long long)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_pageBackgroundFrameForPageRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_removeIconListView:(id)arg1;
- (double)_rubberBandIntervalForOverscroll;
- (struct CGPoint { double x1; double x2; })_scrollView:(id)arg1 adjustedOffsetForOffset:(struct CGPoint { double x1; double x2; })arg2 translation:(struct CGPoint { double x1; double x2; })arg3 startPoint:(struct CGPoint { double x1; double x2; })arg4 locationInView:(struct CGPoint { double x1; double x2; })arg5 horizontalVelocity:(inout double*)arg6 verticalVelocity:(inout double*)arg7;
- (void)_setScrollViewNeedsToClipCorners:(bool)arg1;
- (bool)_shouldConvertToMultipleIconListsInLandscapeOrientation;
- (bool)_showsTitle;
- (bool)_tapToCloseGestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (double)_titleFontSize;
- (double)_titleVerticalOffsetForOrientation:(long long)arg1;
- (void)_updateIconListContainment:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)_updateScalingViewFrame;
- (void)_updateScalingViewLocation;
- (void)_updateScrollingState:(bool)arg1;
- (void)accessibilityReduceTransparencyDidChange:(id)arg1;
- (id)accessibilityTintColorForBackgroundView:(id)arg1;
- (unsigned long long)backgroundEffect;
- (id)borrowScalingView;
- (double)cornerRadius;
- (void)dealloc;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (void)didTransitionAnimated:(bool)arg1;
- (bool)displaysMultipleIconListsInLandscapeOrientation;
- (void)enumeratePageBackgroundViewsUsingBlock:(id /* block */)arg1;
- (void)fadeContentForMagnificationFraction:(double)arg1;
- (void)fadeContentForMinificationFraction:(double)arg1;
- (void)findHiddenIconView;
- (id)floatyFolderConfiguration;
- (bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (id)iconListViewAtPoint:(struct CGPoint { double x1; double x2; })arg1;
- (long long)iconVisibilityHandling;
- (id)initWithConfiguration:(id)arg1;
- (bool)isAnimatingRotation;
- (bool)isConvertingIconListStyle;
- (bool)isDisplayingMultipleIconLists;
- (id)legibilitySettingsForIconListViews;
- (bool)locationCountsAsInsideFolder:(struct CGPoint { double x1; double x2; })arg1;
- (double)minimumVisibleScrollOffset;
- (void)returnScalingView;
- (void)scrollViewDidScroll:(id)arg1;
- (double)scrollableWidthForVisibleColumnRange;
- (void)setAnimatingRotation:(bool)arg1;
- (void)setBackgroundAlpha:(double)arg1;
- (void)setBackgroundEffect:(unsigned long long)arg1;
- (void)setConvertingIconListStyle:(bool)arg1;
- (void)setCornerRadius:(double)arg1;
- (void)setDisplayingMultipleIconLists:(bool)arg1;
- (void)setLegibilitySettings:(id)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (void)transitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;
- (void)updateAccessibilityTintColors;
- (struct CGPoint { double x1; double x2; })visibleFolderRelativeImageCenterForIcon:(id)arg1;
- (void)willTransitionAnimated:(bool)arg1 withSettings:(id)arg2;

@end
