/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBFloatingDockIconListView : SBDockIconListView

- (void)configureIconView:(id)arg1 forIcon:(id)arg2;
- (unsigned long long)iconColumnsForCurrentOrientation;

@end
