/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHAdjustableRootIconListLayoutProvider : SBHDefaultIconListLayoutProvider

- (id)layoutForIconLocation:(id)arg1;

@end
