/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHCrossfadeAppLaunchSettings : SBHCrossfadeAppTransitionSettings

- (void)setDefaultValues;

@end
