/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHCrossfadeAcceleratedAppSuspendSettings : SBHCrossfadeAppSuspendSettings

- (void)setDefaultValues;

@end
