/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHClockApplicationIconImageView : SBLiveIconImageView {
    NSString * _currentNumberingSystem;
    CALayer * _hourMinuteDot;
    CALayer * _hours;
    unsigned int  _jitterSkips;
    UIImage * _mappedContentsImage;
    CALayer * _minutes;
    CALayer * _secondDot;
    CALayer * _seconds;
    UIImage * _squareMappedContentsImage;
    SBHClockIconVisualConfiguration * _visualConfiguration;
}

@property (nonatomic, copy) NSString *currentNumberingSystem;
@property (nonatomic, copy) SBHClockIconVisualConfiguration *visualConfiguration;

+ (void)_handleTimeChange:(id)arg1;
+ (void)_timerFired:(id)arg1;
+ (id)defaultConfiguration;
+ (id)effectiveDate;
+ (id)generateProcessedMappedIconImageWithName:(id)arg1 imageInfo:(struct SBIconImageInfo { struct CGSize { double x_1_1_1; double x_1_1_2; } x1; double x2; double x3; })arg2 includingMask:(bool)arg3;
+ (void)initialize;
+ (id)overrideDate;
+ (void)setOverrideDate:(id)arg1;
+ (id)systemNumberingSystem;

- (void).cxx_destruct;
- (void)_setAnimating:(bool)arg1;
- (void)_timerFiredWithComponents:(id)arg1 flags:(unsigned long long)arg2;
- (void)_updateUnanimatedWithComponents:(id)arg1;
- (void)applyConfiguration:(id)arg1;
- (id)backgroundImageName;
- (id)contentsImage;
- (id)currentNumberingSystem;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)isAnimationAllowed;
- (void)layoutSubviews;
- (void)localeDidChange:(id)arg1;
- (void)prepareForReuse;
- (void)setCurrentNumberingSystem:(id)arg1;
- (void)setJittering:(bool)arg1;
- (void)setPaused:(bool)arg1;
- (void)setVisualConfiguration:(id)arg1;
- (id)squareContentsImage;
- (void)updateAnimatingState;
- (void)updateUnanimated;
- (id)visualConfiguration;

@end
