/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHDefaultIconListLayoutProvider : NSObject <BSDescriptionProviding, SBIconListLayoutProvider> {
    NSMutableDictionary * _cachedListLayouts;
    unsigned long long  _layoutOptions;
    unsigned long long  _screenType;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) unsigned long long layoutOptions;
@property (nonatomic, readonly) unsigned long long screenType;
@property (readonly) Class superclass;

+ (unsigned long long)currentDeviceScreenType;
+ (id)frameworkFallbackInstance;

- (void).cxx_destruct;
- (void)configureClockIconConfiguration:(id)arg1 forScreenType:(unsigned long long)arg2 layoutOptions:(unsigned long long)arg3;
- (void)configureFloatyFolderConfiguration:(id)arg1 forScreenType:(unsigned long long)arg2 layoutOptions:(unsigned long long)arg3;
- (void)configureFolderIconConfiguration:(id)arg1 forScreenType:(unsigned long long)arg2 layoutOptions:(unsigned long long)arg3;
- (void)configureIconAccessoryConfiguration:(id)arg1 forScreenType:(unsigned long long)arg2 layoutOptions:(unsigned long long)arg3;
- (void)configureLabelConfigurations:(id)arg1 forScreenType:(unsigned long long)arg2;
- (void)configureSidebarConfiguration:(id)arg1 forScreenType:(unsigned long long)arg2;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)init;
- (id)initWithLayoutOptions:(unsigned long long)arg1;
- (id)initWithScreenType:(unsigned long long)arg1;
- (id)initWithScreenType:(unsigned long long)arg1 layoutOptions:(unsigned long long)arg2;
- (id)layoutForIconLocation:(id)arg1;
- (unsigned long long)layoutOptions;
- (id)makeLayoutForIconLocation:(id)arg1;
- (unsigned long long)screenType;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end
