/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHHomeScreenDomain : PTDomain

+ (id)domainGroupName;
+ (id)domainName;
+ (id)rootSettings;
+ (Class)rootSettingsClass;

@end
