/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHHomeScreenSettings : PTSettings {
    double  _defaultDragInteractionLiftDelay;
    SBHFolderSettings * _folderSettings;
    SBHIconAnimationRootSettings * _iconAnimationSettings;
    SBHIconSettings * _iconSettings;
    SBHRootFolderSettings * _rootFolderSettings;
    bool  _showPopOvers;
    bool  _showWidgets;
    bool  _usesMinimumViableHomeScreen;
}

@property (nonatomic) double defaultDragInteractionLiftDelay;
@property (nonatomic, retain) SBHFolderSettings *folderSettings;
@property (nonatomic, retain) SBHIconAnimationRootSettings *iconAnimationSettings;
@property (nonatomic, retain) SBHIconSettings *iconSettings;
@property (nonatomic, retain) SBHRootFolderSettings *rootFolderSettings;
@property (nonatomic) bool showPopOvers;
@property (nonatomic) bool showWidgets;
@property (nonatomic) bool usesMinimumViableHomeScreen;

+ (id)settingsControllerModule;

- (void).cxx_destruct;
- (double)defaultDragInteractionLiftDelay;
- (id)folderSettings;
- (id)iconAnimationSettings;
- (id)iconSettings;
- (id)rootFolderSettings;
- (void)setDefaultDragInteractionLiftDelay:(double)arg1;
- (void)setDefaultValues;
- (void)setFolderSettings:(id)arg1;
- (void)setIconAnimationSettings:(id)arg1;
- (void)setIconSettings:(id)arg1;
- (void)setRootFolderSettings:(id)arg1;
- (void)setShowPopOvers:(bool)arg1;
- (void)setShowWidgets:(bool)arg1;
- (void)setUsesMinimumViableHomeScreen:(bool)arg1;
- (bool)showPopOvers;
- (bool)showWidgets;
- (bool)usesMinimumViableHomeScreen;

@end
