/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHIconSettings : PTSettings {
    SBFParallaxSettings * _badgeParallaxSettings;
    bool  _closeBoxesEverywhere;
    SBFParallaxSettings * _iconParallaxSettings;
    bool  _suppressJitter;
}

@property (nonatomic, retain) SBFParallaxSettings *badgeParallaxSettings;
@property (nonatomic) bool closeBoxesEverywhere;
@property (nonatomic, retain) SBFParallaxSettings *iconParallaxSettings;
@property (nonatomic) bool suppressJitter;

+ (id)settingsControllerModule;

- (void).cxx_destruct;
- (id)badgeParallaxSettings;
- (bool)closeBoxesEverywhere;
- (id)iconParallaxSettings;
- (void)setBadgeParallaxSettings:(id)arg1;
- (void)setCloseBoxesEverywhere:(bool)arg1;
- (void)setDefaultValues;
- (void)setIconParallaxSettings:(id)arg1;
- (void)setSuppressJitter:(bool)arg1;
- (bool)suppressJitter;

@end
