/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHIconLabelVisualConfiguration : NSObject <BSDescriptionProviding, NSCopying> {
    double  _baselineOffsetFromImage;
    double  _fontSize;
    double  _height;
    double  _widthDelta;
}

@property (nonatomic) double baselineOffsetFromImage;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) double fontSize;
@property (readonly) unsigned long long hash;
@property (nonatomic) double height;
@property (readonly) Class superclass;
@property (nonatomic) double widthDelta;

- (double)baselineOffsetFromImage;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (double)fontSize;
- (double)height;
- (id)init;
- (void)setBaselineOffsetFromImage:(double)arg1;
- (void)setFontSize:(double)arg1;
- (void)setHeight:(double)arg1;
- (void)setWidthDelta:(double)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (double)widthDelta;

@end
