/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBHomeScreenButton : UIButton {
    SBHomeScreenMaterialView * _materialView;
}

@property (nonatomic, readonly) SBHomeScreenMaterialView *materialView;

+ (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })backgroundInsets;
+ (id)defaultContentImage;

- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 backgroundView:(id)arg2;
- (void)layoutSubviews;
- (id)materialView;
- (void)setHighlighted:(bool)arg1;

@end
