/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBIconBlockedForScreenTimeExpirationLabelAccessoryView : SBIconLegibilityLabelAccessoryView

+ (id)labelAccessorySystemImageName;
+ (long long)labelAccessorySystemImageScale;

@end
