/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBIconLayoutOverrideStrategy : NSObject {
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _layoutInsets;
    bool  _preservesCurrentListOrigin;
}

@property (nonatomic, readonly) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } layoutInsets;
@property (nonatomic, readonly) bool preservesCurrentListOrigin;

- (id)initWithLayoutInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1 perservingCurrentListOrigin:(bool)arg2;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })layoutInsets;
- (bool)preservesCurrentListOrigin;

@end
