/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBIconCloudLabelAccessoryView : SBIconLegibilityLabelAccessoryView

+ (id)labelAccessorySystemImageName;

@end
