/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBIconDragInteraction : UIDragInteraction

+ (bool)isEnabledByDefault;

@end
