/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBIconImageCrossfadeView : SBFTouchPassThroughView {
    double  _containerScaleX;
    double  _containerScaleY;
    UIView * _containerView;
    UIView * _crossfadeContainerView;
    UIView * _crossfadeView;
    SBIconImageView * _iconImageView;
    bool  _masksCorners;
    double  _morphFraction;
    bool  _performsTrueCrossfade;
    struct CGPoint { 
        double x; 
        double y; 
    }  _stretchAnchorPoint;
}

@property (nonatomic, readonly) UIView *containerView;
@property (nonatomic, readonly) UIView *crossfadeView;
@property (nonatomic, readonly) SBIconImageView *iconImageView;
@property (nonatomic) bool masksCorners;
@property (nonatomic) bool performsTrueCrossfade;
@property (nonatomic) struct CGPoint { double x1; double x2; } stretchAnchorPoint;

- (void).cxx_destruct;
- (void)_updateCornerMask;
- (void)applyCornerRadius:(double)arg1;
- (void)cleanup;
- (id)containerView;
- (id)crossfadeView;
- (id)iconImageView;
- (id)initWithImageView:(id)arg1 crossfadeView:(id)arg2;
- (void)layoutSubviews;
- (bool)masksCorners;
- (bool)performsTrueCrossfade;
- (void)prepareGeometry;
- (void)setAppSnapshotCornerRadius:(double)arg1;
- (void)setCornerRadiusEnabled:(bool)arg1;
- (void)setCrossfadeFraction:(double)arg1;
- (void)setMasksCorners:(bool)arg1;
- (void)setMorphFraction:(double)arg1;
- (void)setPerformsTrueCrossfade:(bool)arg1;
- (void)setStretchAnchorPoint:(struct CGPoint { double x1; double x2; })arg1;
- (struct CGPoint { double x1; double x2; })stretchAnchorPoint;

@end
