/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBMinusCloseBoxView : SBCloseBoxView

+ (id)defaultContentImage;

@end
