/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBRootFolderControllerDefaultTransitionContext : SBViewControllerTransitionContext

@end
