/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardHome.framework/SpringBoardHome
 */

@interface SBRootFolderDockAnimationViewController : UIViewController {
    long long  _forcedInterfaceOrientation;
}

@property (nonatomic) long long forcedInterfaceOrientation;

- (long long)forcedInterfaceOrientation;
- (void)setForcedInterfaceOrientation:(long long)arg1;
- (bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;

@end
