/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardUI.framework/SpringBoardUI
 */

@interface SBUISearchUtilities : NSObject

+ (double)idealSearchPlatterWidth;

- (id)init;

@end
