/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardUI.framework/SpringBoardUI
 */

@interface SBUICarPlayMappedImageCache : BSUIMappedImageCache

+ (id)sharedCache;

@end
