/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardUI.framework/SpringBoardUI
 */

@interface SBUIPluginAppearanceContext : NSObject {
    bool  _hideOtherWindowsDuringAppearance;
}

@property (nonatomic) bool hideOtherWindowsDuringAppearance;

- (bool)hideOtherWindowsDuringAppearance;
- (void)setHideOtherWindowsDuringAppearance:(bool)arg1;

@end
