/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
 */

@interface SBFTodayGestureSettings : PTSettings {
    double  _interactiveSideSpringFriction;
    double  _interactiveSideSpringTension;
    double  _sideSpringFriction;
    double  _sideSpringTension;
}

@property (nonatomic) double interactiveSideSpringFriction;
@property (nonatomic) double interactiveSideSpringTension;
@property (nonatomic) double sideSpringFriction;
@property (nonatomic) double sideSpringTension;

+ (id)settingsControllerModule;

- (double)interactiveSideSpringFriction;
- (double)interactiveSideSpringTension;
- (void)setDefaultValues;
- (void)setInteractiveSideSpringFriction:(double)arg1;
- (void)setInteractiveSideSpringTension:(double)arg1;
- (void)setSideSpringFriction:(double)arg1;
- (void)setSideSpringTension:(double)arg1;
- (double)sideSpringFriction;
- (double)sideSpringTension;

@end
