/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBApplicationLaunchAlertInfo : NSObject {
    NSMutableSet * _alertItems;
    NSString * _bundleID;
    NSMutableSet * _foregroundScenes;
}

@property (nonatomic, readonly) NSMutableSet *alertItems;
@property (nonatomic, readonly, copy) NSString *bundleID;
@property (nonatomic, readonly) NSMutableSet *foregroundScenes;

- (void).cxx_destruct;
- (id)alertItems;
- (id)bundleID;
- (id)description;
- (id)foregroundScenes;
- (id)initWithBundleID:(id)arg1;

@end
