/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBAccessibilityTintView : UIView <SBWallpaperObserver, _SBFakeBlur> {
    bool  _fullscreen;
    <_SBFakeBlurObserver> * _observer;
    unsigned long long  _transformOptions;
    long long  _variant;
    SBWallpaperController * _wallpaperController;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (getter=isFullscreen, nonatomic) bool fullscreen;
@property (readonly) unsigned long long hash;
@property (nonatomic) <_SBFakeBlurObserver> *observer;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long transformOptions;
@property (nonatomic, readonly) SBWallpaperController *wallpaperController;
@property (nonatomic) double zoomScale;

- (void).cxx_destruct;
- (void)_updateBackgroundColor;
- (void)dealloc;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (long long)effectiveStyle;
- (id)initWithVariant:(long long)arg1 wallpaperController:(id)arg2;
- (bool)isFullscreen;
- (id)observer;
- (void)offsetWallpaperBy:(struct CGPoint { double x1; double x2; })arg1;
- (void)requestStyle:(long long)arg1;
- (void)setFullscreen:(bool)arg1;
- (void)setObserver:(id)arg1;
- (void)setTransformOptions:(unsigned long long)arg1;
- (void)setZoomScale:(double)arg1;
- (unsigned long long)transformOptions;
- (id)wallpaperController;
- (void)wallpaperDidChangeForVariant:(long long)arg1;
- (void)wallpaperLegibilitySettingsDidChange:(id)arg1 forVariant:(long long)arg2;
- (double)zoomScale;

@end
