/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBBulletinRootViewControllerTransitionContext : NSObject {
    bool  _animated;
    UIView * _containerView;
    id /* block */  _dismissalCompletion;
    id /* block */  _presentationCompletion;
    UIViewController * _presentedViewController;
    bool  _presenting;
    UIViewController * _presentingViewController;
}

@property (getter=isAnimated, nonatomic) bool animated;
@property (nonatomic, retain) UIView *containerView;
@property (nonatomic, copy) id /* block */ dismissalCompletion;
@property (nonatomic, copy) id /* block */ presentationCompletion;
@property (nonatomic, retain) UIViewController *presentedViewController;
@property (getter=isPresenting, nonatomic) bool presenting;
@property (nonatomic, retain) UIViewController *presentingViewController;

- (void).cxx_destruct;
- (id)containerView;
- (id /* block */)dismissalCompletion;
- (bool)isAnimated;
- (bool)isPresenting;
- (id /* block */)presentationCompletion;
- (id)presentedViewController;
- (id)presentingViewController;
- (void)setAnimated:(bool)arg1;
- (void)setContainerView:(id)arg1;
- (void)setDismissalCompletion:(id /* block */)arg1;
- (void)setPresentationCompletion:(id /* block */)arg1;
- (void)setPresentedViewController:(id)arg1;
- (void)setPresenting:(bool)arg1;
- (void)setPresentingViewController:(id)arg1;

@end
