/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBExpertAppSuggestion : SBBestAppSuggestion {
    _DECAppItem * _appSuggestion;
    _DECResult * _result;
}

@property (nonatomic, readonly) _DECAppItem *appSuggestion;
@property (nonatomic, readonly) _DECResult *result;
@property (nonatomic, readonly) NSUUID *resultUUID;

- (void).cxx_destruct;
- (id)appSuggestion;
- (id)bundleIdentifier;
- (unsigned long long)hash;
- (id)initWithAppSuggestion:(id)arg1 result:(id)arg2;
- (bool)isArrivedAtHomePrediction;
- (bool)isArrivedAtWorkPrediction;
- (bool)isBluetoothAudioPrediction;
- (bool)isBluetoothPrediction;
- (bool)isCarPlayPrediction;
- (bool)isEqual:(id)arg1;
- (bool)isFirstWakePrediction;
- (bool)isHeadphonesPrediction;
- (bool)isLocallyGeneratedSuggestion;
- (bool)isLocationBasedSuggestion;
- (bool)isPrediction;
- (id)originatingDeviceName;
- (id)result;
- (id)resultUUID;

@end
