/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBFluidSwitcherModifierTimelineEntryView : UIView {
    UILabel * _actionsLabel;
    <_SBFluidSwitcherModifierTimelineEntryViewDelegate> * _delegate;
    SBSwitcherModifierTimelineEntry * _entry;
    UILabel * _nameLabel;
    UILabel * _postStackLabel;
    UITapGestureRecognizer * _tapRecognizer;
}

@property (nonatomic) <_SBFluidSwitcherModifierTimelineEntryViewDelegate> *delegate;
@property (nonatomic, retain) SBSwitcherModifierTimelineEntry *entry;

- (void).cxx_destruct;
- (id)_appendRecursiveDescriptionToString:(id)arg1 level:(unsigned long long)arg2 snapshot:(id)arg3;
- (id)_randomColor;
- (id)_stringForStack:(id)arg1;
- (void)_tap:(id)arg1;
- (id)delegate;
- (id)entry;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 entry:(id)arg2;
- (void)layoutSubviews;
- (void)setDelegate:(id)arg1;
- (void)setEntry:(id)arg1;

@end
