/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBFakeBlurView : UIView <SBReachabilityObserver, _SBFakeBlur> {
    long long  _effectiveStyle;
    bool  _fullscreen;
    UIImageView * _imageView;
    <_SBFakeBlurObserver> * _observer;
    long long  _requestedStyle;
    unsigned long long  _transformOptions;
    SBWallpaperController * _wallpaperController;
    struct CGPoint { 
        double x; 
        double y; 
    }  _wallpaperOffset;
    SBFWallpaperView * _wallpaperView;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (getter=isFullscreen, nonatomic) bool fullscreen;
@property (readonly) unsigned long long hash;
@property (nonatomic) <_SBFakeBlurObserver> *observer;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long transformOptions;
@property (nonatomic, readonly) long long variant;
@property (nonatomic, readonly) SBWallpaperController *wallpaperController;
@property (nonatomic) double zoomScale;

+ (id)_imageForStyle:(inout long long*)arg1 withSource:(id)arg2 rootSettings:(id)arg3;
+ (id)_imageForStyle:(inout long long*)arg1 withSource:(id)arg2 rootSettings:(id)arg3 overrideTraitCollection:(id)arg4;

- (void).cxx_destruct;
- (void)_createOrRemoveMatchMoveAnimationIfNeeded;
- (void)_setImage:(id)arg1 style:(long long)arg2 notify:(bool)arg3;
- (void)_updateImageWithSource:(id)arg1 overrideTraitCollection:(id)arg2 notifyObserver:(bool)arg3;
- (void)dealloc;
- (id)description;
- (void)didMoveToWindow;
- (long long)effectiveStyle;
- (void)handleReachabilityYOffsetDidChange;
- (id)initWithVariant:(long long)arg1 wallpaperController:(id)arg2 transformOptions:(unsigned long long)arg3;
- (bool)isFullscreen;
- (void)layoutSubviews;
- (id)observer;
- (void)offsetWallpaperBy:(struct CGPoint { double x1; double x2; })arg1;
- (void)reconfigureWithSource:(id)arg1;
- (void)requestStyle:(long long)arg1;
- (void)rotateToInterfaceOrientation:(long long)arg1;
- (void)setFullscreen:(bool)arg1;
- (void)setObserver:(id)arg1;
- (void)setTransformOptions:(unsigned long long)arg1;
- (void)setZoomScale:(double)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (unsigned long long)transformOptions;
- (void)updateImageWithSource:(id)arg1;
- (void)updateImageWithSource:(id)arg1 overrideTraitCollection:(id)arg2;
- (long long)variant;
- (id)wallpaperController;
- (void)willMoveToWindow:(id)arg1;
- (double)zoomScale;

@end
