/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBHomeScreenFolderDelegate : NSObject {
    <SBFolderControllerDelegate> * _forwardingTarget;
}

@property (nonatomic, retain) <SBFolderControllerDelegate> *forwardingTarget;

- (void).cxx_destruct;
- (id)backgroundViewForDockForRootFolderController:(id)arg1;
- (id)forwardingTarget;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (bool)respondsToSelector:(SEL)arg1;
- (void)setForwardingTarget:(id)arg1;

@end
