/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBHUDHostViewController : SBFTouchPassThroughViewController <SBViewControllerTransitionContextDelegate> {
    SBHUDController * _HUDController;
    NSMutableArray * _activeTransitionContexts;
    <_SBHUDHostViewControllerDelegate> * _delegate;
    NSMutableSet * _dismissingHUDsTransitionContexts;
    NSMutableSet * _presentedHUDs;
    NSMutableSet * _presentingHUDs;
    NSMutableSet * _presentingHUDsTransitionContexts;
}

@property (nonatomic, readonly) SBHUDController *HUDController;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <_SBHUDHostViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) unsigned long long numberOfActiveTransitions;
@property (nonatomic, readonly) NSSet *presentedHUDs;
@property (nonatomic, readonly) NSSet *presentingHUDs;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)HUDController;
- (id)_buildTransitionContextToPresentHUD:(id)arg1 dismissHUD:(id)arg2 animated:(bool)arg3 delegate:(id)arg4 containerView:(id)arg5 completion:(id /* block */)arg6;
- (bool)_canShowWhileLocked;
- (void)_executeDismissHUD:(id)arg1 animated:(bool)arg2 completion:(id /* block */)arg3;
- (void)_executePresentNewHUD:(id)arg1 animated:(bool)arg2 completion:(id /* block */)arg3;
- (void)_executeViewControllerTransitionContext:(id)arg1;
- (id)_transitionContextMatchingHUD:(id)arg1 withinContainer:(id)arg2;
- (id)delegate;
- (id)description;
- (void)dismissHUD:(id)arg1 animated:(bool)arg2 completion:(id /* block */)arg3;
- (void)dismissHUDs:(bool)arg1;
- (id)initWithHUDController:(id)arg1;
- (bool)isHUDBeingDismissed:(id)arg1;
- (bool)isHUDBeingPresented:(id)arg1;
- (id)knownHUDForIdentifier:(id)arg1;
- (unsigned long long)numberOfActiveTransitions;
- (void)presentHUD:(id)arg1 animated:(bool)arg2 completion:(id /* block */)arg3;
- (id)presentedHUDs;
- (id)presentingHUDs;
- (void)reverseHUDDismissal:(id)arg1;
- (void)reverseHUDPresentation:(id)arg1;
- (void)setDelegate:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)transitionDidFinish:(id)arg1;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;

@end
