/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBInteractiveScreenshotGestureReplicatorView : UIView

@property (nonatomic, readonly) CAReplicatorLayer *replicatorLayer;

+ (Class)layerClass;

- (id)replicatorLayer;

@end
