/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBModifierTimelineDetailViewController : UIViewController <UITableViewDataSource, UITableViewDelegate> {
    _SBModifierTimelineTextViewController * _actionDetailViewController;
    SBSwitcherModifierTimelineEntry * _entry;
    _SBModifierTimelineModifierDetailViewController * _modifierDetailViewController;
    UITableView * _tableView;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) SBSwitcherModifierTimelineEntry *entry;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_done;
- (long long)_numberOfModifiersInStackSnapshot:(id)arg1;
- (id)_stackSnapshotAtIndex:(long long)arg1;
- (id)entry;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)setEntry:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end
