/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBModalViewControllerStackTransition : NSObject {
    bool  _animated;
    id /* block */  _completion;
    unsigned long long  _operation;
    UIViewController * _viewController;
}

@property (nonatomic) bool animated;
@property (nonatomic, copy) id /* block */ completion;
@property (nonatomic) unsigned long long operation;
@property (nonatomic, retain) UIViewController *viewController;

+ (id)transitionForViewController:(id)arg1 operation:(unsigned long long)arg2 animated:(bool)arg3 completion:(id /* block */)arg4;

- (void).cxx_destruct;
- (bool)animated;
- (id /* block */)completion;
- (id)description;
- (void)invokeCompletionIfNecessaryWithResult:(bool)arg1;
- (unsigned long long)operation;
- (void)setAnimated:(bool)arg1;
- (void)setCompletion:(id /* block */)arg1;
- (void)setOperation:(unsigned long long)arg1;
- (void)setViewController:(id)arg1;
- (id)viewController;

@end
