/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBProximityTouchHandlingViewController : UIViewController {
    double  _statusBarHeight;
}

@property (nonatomic) <_SBProximityTouchHandlingDelegate> *delegate;
@property (nonatomic) double statusBarHeight;

- (id)_view;
- (id)delegate;
- (void)loadView;
- (long long)preferredInterfaceOrientationForPresentation;
- (void)setDelegate:(id)arg1;
- (void)setStatusBarHeight:(double)arg1;
- (bool)shouldAutorotate;
- (double)statusBarHeight;
- (unsigned long long)supportedInterfaceOrientations;

@end
