/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface _SBVolumeHUDViewControllerNullAnimator : SBUIAnimationPropertyAnimator

- (id)init;

@end
