/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBActiveAppLayoutFloatingSwitcherModifier : SBSwitcherModifier {
    _SBActiveAppFloorFloatingSwitcherModifier * _floorModifier;
    SBStackedFloatingSwitcherModifier * _stackedModifier;
}

- (void).cxx_destruct;
- (id)initWithActiveAppLayout:(id)arg1 floatingConfiguration:(long long)arg2;

@end
