/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAlertItemWindow : SBSecureMainScreenActiveInterfaceOrientationWindow

- (bool)_canBecomeKeyWindow;

@end
