/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAnimationUtilities : NSObject

+ (double)adjustedRotationAnimationDurationForDuration:(double)arg1 fromOrientation:(long long)arg2 toOrientation:(long long)arg3;
+ (id)animationSettingsForRotationFromInterfaceOrientation:(long long)arg1 toInterfaceOrientation:(long long)arg2;

@end
