/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAnimationWrapperViewLiveContentOverlay : NSObject <SBSwitcherLiveContentOverlay> {
    SBSceneLayoutAnimationWrapperView * _animationWrapperView;
    long long  _containerOrientation;
}

@property (nonatomic, readonly) SBSceneLayoutAnimationWrapperView *animationWrapperView;
@property (nonatomic) long long containerOrientation;
@property (nonatomic, readonly) UIView *contentOverlayView;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)animationWrapperView;
- (long long)containerOrientation;
- (id)contentOverlayView;
- (void)disableAsynchronousRenderingForNextCommit;
- (id)initWithAnimationWrapperView:(id)arg1;
- (void)noteKeyboardFocusDidChangeToSceneID:(id)arg1;
- (long long)rasterizationStyle;
- (void)setContainerOrientation:(long long)arg1;
- (void)setHomeGrabberHidden:(bool)arg1 animated:(bool)arg2;
- (void)setRasterizationStyle:(long long)arg1 withMinificationFilterEnabled:(bool)arg2;
- (void)setStatusBarHidden:(bool)arg1 nubViewHidden:(bool)arg2 animator:(id /* block */)arg3;
- (void)setUsesBrightSceneViewBackgroundMaterial:(bool)arg1;

@end
