/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBApplicationTestingManager : NSObject {
    NSString * _currentTestName;
    NSMutableDictionary * _idleTimerDisableAssertions;
    NSObject<OS_dispatch_queue> * _queue;
    NSMutableArray * _queue_testEndedHandlers;
    NSString * _scrollTestActiveSubtest;
}

@property (nonatomic, copy) NSString *currentTestName;
@property (getter=_idleTimerDisableAssertions, nonatomic, readonly) NSMutableDictionary *idleTimerDisableAssertions;
@property (nonatomic, copy) NSString *scrollTestActiveSubtest;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_handleTestEnded;
- (id)_idleTimerDisableAssertions;
- (void)_installTestEndedHandler:(id /* block */)arg1;
- (void)_prepareForTestStartup:(id)arg1;
- (id)currentTestName;
- (id)init;
- (void)markUserLaunchInitiationTime;
- (id)scrollTestActiveSubtest;
- (void)setCurrentTestName:(id)arg1;
- (void)setScrollTestActiveSubtest:(id)arg1;

@end
