/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppLayout : NSObject <BSDescriptionProviding, NSCopying> {
    long long  _cachedAppLayoutType;
    long long  _configuration;
    long long  _environment;
    bool  _hidden;
    NSDictionary * _rolesToLayoutItemsMap;
}

@property (nonatomic) long long configuration;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) long long environment;
@property (readonly) unsigned long long hash;
@property (getter=isHidden, nonatomic, readonly) bool hidden;
@property (getter=isInsetForHomeAffordance, nonatomic, readonly) bool insetForHomeAffordance;
@property (nonatomic, copy) NSDictionary *rolesToLayoutItemsMap;
@property (readonly) Class superclass;
@property (nonatomic, readonly) long long type;

+ (id)appLayoutWithProtobufRepresentation:(id)arg1;
+ (id)homeScreenAppLayout;

- (void).cxx_destruct;
- (id)allItems;
- (id)appLayoutByModifyingHiddenState:(bool)arg1;
- (id)appLayoutWithItemsPassingTest:(id /* block */)arg1;
- (long long)compare:(id)arg1;
- (long long)configuration;
- (bool)containsAnyItemFromSet:(id)arg1;
- (bool)containsItem:(id)arg1;
- (bool)containsItemWithBundleIdentifier:(id)arg1;
- (bool)containsItemWithUniqueIdentifier:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)enumerate:(id /* block */)arg1;
- (long long)environment;
- (unsigned long long)frameOptions;
- (unsigned long long)hash;
- (id)init;
- (id)initWithItemsForLayoutRoles:(id)arg1 configuration:(long long)arg2 environment:(long long)arg3;
- (id)initWithItemsForLayoutRoles:(id)arg1 configuration:(long long)arg2 environment:(long long)arg3 hidden:(bool)arg4;
- (id)initWithPlistRepresentation:(id)arg1;
- (bool)isEqual:(id)arg1;
- (bool)isHidden;
- (bool)isInsetForHomeAffordance;
- (id)itemForLayoutRole:(long long)arg1;
- (long long)layoutRoleForItem:(id)arg1;
- (id)plistRepresentation;
- (id)protobufRepresentation;
- (id)rolesToLayoutItemsMap;
- (void)setConfiguration:(long long)arg1;
- (void)setRolesToLayoutItemsMap:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (long long)type;

@end
