/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppResizeGestureWorkspaceTransaction : SBSystemGestureWorkspaceTransaction {
    UIApplicationSceneDeactivationAssertion * _appDeactivationAssertion;
    SBBlurViewCoordinator * _blurCoordinator;
    unsigned long long  _currentGestureIdentifier;
    SBMainWorkspaceTransaction * _currentWorkspaceTransaction;
    <BSInvalidatable> * _deferOrientationUpdatesForResizeAssertion;
    NSSet * _fromApplicationSceneEntities;
    bool  _isSceneLayoutViewControllerPushedIn;
    SBMainDisplaySceneLayoutViewController * _layoutViewController;
    double  _previousSlideOffPercent;
    SBLayoutElementViewController * _primaryLayoutElementController;
    SBLayoutElementViewController * _sideLayoutElementController;
    NSMutableArray * _statusBarAssertions;
    NSSet * _toApplicationSceneEntitiesSuspendPrimary;
    NSSet * _toApplicationSceneEntitiesSuspendSide;
}

@property (nonatomic, readonly) UIApplicationSceneDeactivationAssertion *appDeactivationAssertion;
@property (nonatomic, retain) SBBlurViewCoordinator *blurCoordinator;
@property (nonatomic) unsigned long long currentGestureIdentifier;
@property (nonatomic, retain) SBMainWorkspaceTransaction *currentWorkspaceTransaction;
@property (nonatomic, readonly) SBMainDisplaySceneLayoutViewController *layoutViewController;
@property (nonatomic, readonly) SBLayoutElementViewController *primaryLayoutElementController;
@property (nonatomic, readonly) SBLayoutElementViewController *sideLayoutElementController;

+ (double)_rubberbandingStartScreenEdgeMarginInOrientation:(long long)arg1;

- (void).cxx_destruct;
- (void)_addChildWorkspaceTransaction:(id)arg1;
- (void)_animateElementViewsForFinalAction:(long long)arg1 forLayoutState:(id)arg2 completionHandler:(id /* block */)arg3;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_appFrameForElementWithRole:(long long)arg1 inLayoutState:(id)arg2 spaceConfiguration:(long long)arg3 inCoordinateSpace:(id)arg4;
- (void)_begin;
- (bool)_canBeInterrupted;
- (bool)_canResizeToHalfHalf;
- (void)_childTransactionDidComplete:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_convertRectFromReferenceCoordinateSpaceToContentViewCoordinateSpace:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_didComplete;
- (void)_didInterruptWithReason:(id)arg1;
- (void)_dismissResizeUIAnimated:(bool)arg1;
- (double)_dividerPositionFromPanGestureRecognizer:(id)arg1;
- (long long)_finalActionForGestureRegion:(long long)arg1;
- (void)_finishWithCompletionType:(long long)arg1;
- (void)_getPrimaryLayoutElementViewFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg1 sideLayoutElementViewFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg2 separatorViewFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; }*)arg3 forResizeGestureRegion:(long long)arg4 location:(double)arg5 allowRubberbanding:(bool)arg6;
- (void)_hideLayoutElementViewControllerStatusBars;
- (long long)_layoutModeForGestureRegion:(long long)arg1;
- (double)_maxRubberBandOffset;
- (double)_normalizedVelocityFromPanGestureRecognizer:(id)arg1;
- (void)_popOutSceneLayoutViewController;
- (void)_pushInSceneLayoutViewController;
- (void)_resizeGestureDidUpdate:(id)arg1;
- (void)_resizeGestureFinishedWithFinalAction:(long long)arg1;
- (void)_resizeGestureFinishedWithState:(long long)arg1 gestureDividerPosition:(double)arg2 normalizedVelocity:(double)arg3;
- (long long)_resizeGestureRegionForLocation:(double)arg1 velocity:(double)arg2;
- (void)_restartResizeUI;
- (double)_rubberBandOffsetForOffset:(double)arg1 maxOffset:(double)arg2 minOffset:(double)arg3 range:(double)arg4 outside:(bool*)arg5;
- (long long)_spaceConfigurationForGestureRegion:(long long)arg1;
- (id)_transactionForExecutingApplicationTransitionContext:(id)arg1 eventLabel:(id)arg2;
- (id)_transitionContextForFinalAction:(long long)arg1;
- (void)_unhideLayoutElementViewControllerStatusBars;
- (void)_updateElementViewsAlphaAndGrabberForFinalAction:(long long)arg1;
- (void)_updateResizeUIFromGestureRecognizer:(id)arg1;
- (id)appDeactivationAssertion;
- (id)blurCoordinator;
- (unsigned long long)currentGestureIdentifier;
- (id)currentWorkspaceTransaction;
- (void)dealloc;
- (id)initWithTransitionRequest:(id)arg1;
- (id)initWithTransitionRequest:(id)arg1 layoutViewController:(id)arg2;
- (id)layoutViewController;
- (id)primaryLayoutElementController;
- (void)setBlurCoordinator:(id)arg1;
- (void)setCurrentGestureIdentifier:(unsigned long long)arg1;
- (void)setCurrentWorkspaceTransaction:(id)arg1;
- (id)sideLayoutElementController;
- (void)systemGestureStateChanged:(id)arg1;

@end
