/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppExposeSwitcherModifierEvent : SBSwitcherModifierEvent {
    NSString * _bundleID;
}

@property (nonatomic, readonly, copy) NSString *bundleID;

- (void).cxx_destruct;
- (id)bundleID;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)initWithBundleID:(id)arg1;
- (long long)type;

@end
