/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppStatusBarSettingsAssertion : NSObject <BSDescriptionProviding, BSInvalidatable> {
    unsigned long long  _level;
    NSString * _reason;
    SBAppStatusBarSettings * _settings;
    NSDate * _timestamp;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) unsigned long long level;
@property (nonatomic, readonly, copy) NSString *reason;
@property (nonatomic, readonly, copy) SBAppStatusBarSettings *settings;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSDate *timestamp;

- (void).cxx_destruct;
- (void)acquire;
- (void)acquireWithAnimationParameters:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)init;
- (id)initWithSettings:(id)arg1 atLevel:(unsigned long long)arg2 reason:(id)arg3;
- (id)initWithStatusBarHidden:(bool)arg1 atLevel:(unsigned long long)arg2 reason:(id)arg3;
- (void)invalidate;
- (void)invalidateWithAnimationParameters:(id)arg1;
- (unsigned long long)level;
- (void)modifySettingsWithBlock:(id /* block */)arg1;
- (void)modifySettingsWithBlock:(id /* block */)arg1 animationParameters:(id)arg2;
- (id)reason;
- (id)settings;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)timestamp;

@end
