/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppStatusBarAssertionManager : NSObject <BSDescriptionProviding, UIStatusBarManager> {
    NSMutableSet * _activeLayoutLayers;
    bool  _changingStatusBarAlpha;
    bool  _changingStatusBarStyle;
    SBAppStatusBarSettings * _currentStatusBarSettings;
    double  _defaultWindowLevel;
    NSHashTable * _disableAlphaChangeAssertions;
    NSHashTable * _disableUserInteractionChangeAssertions;
    NSMutableDictionary * _edgeInsetsDictionary;
    NSHashTable * _observers;
    NSMutableDictionary * _orientationWindowDictionary;
    <BSInvalidatable> * _stateCaptureAssertion;
    unsigned long long  _statusBarAlphaAnimationCount;
    NSPointerArray * _statusBarSettingsAssertionsByLevel;
    NSMutableDictionary * _windowLevelOverrideMap;
    NSMutableOrderedSet * _windowLevelOverrideReasons;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } statusBarEdgeInsets;
@property (readonly) Class superclass;
@property (nonatomic, readonly) unsigned long long topmostActiveLayoutLayer;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_addDisableAppStatusBarAlphaChangesAssertion:(id)arg1;
- (void)_addDisableAppStatusBarUserInteractionChangesAssertion:(id)arg1;
- (void)_addStatusBarSettingsAssertion:(id)arg1;
- (void)_addStatusBarSettingsAssertion:(id)arg1 withAnimationParameters:(id)arg2;
- (void)_applyEdgeInsetsToStatusBar;
- (void)_cleanUpAllStatusBarSettingsAssertions;
- (id)_descriptionForPropertyWithAssertions:(id)arg1;
- (void)_enumerateAssertionsToLevel:(unsigned long long)arg1 withBlock:(id /* block */)arg2;
- (void)_evaluateSettingsWithStyleAnimations:(id)arg1;
- (void)_modifiedStatusBarSettingsAssertion:(id)arg1;
- (void)_modifiedStatusBarSettingsAssertion:(id)arg1 withAnimationParameters:(id)arg2;
- (void)_removeDisableAppStatusBarAlphaChangesAssertion:(id)arg1;
- (void)_removeDisableAppStatusBarUserInteractionChangesAssertion:(id)arg1;
- (void)_removeStatusBarSettingsAssertion:(id)arg1;
- (void)_removeStatusBarSettingsAssertion:(id)arg1 withAnimationParameters:(id)arg2;
- (void)_resolveEffectiveStatusBarStyleForSettings:(id)arg1;
- (void)_setStatusBarValueForPropertyWithAssertions:(id)arg1 setter:(id /* block */)arg2;
- (void)_statusBarUpdatedFromSettings:(id)arg1 toSettings:(id)arg2 withAnimations:(id)arg3;
- (id)_styleRequestForSettings:(id)arg1;
- (void)_updateStatusBarOrientationForTopMostActiveLayer;
- (void)_updateWindowLevel;
- (void)addActiveLayoutLayer:(unsigned long long)arg1;
- (void)addObserver:(id)arg1;
- (id)currentEffectiveStatusBarStyleRequest;
- (id)currentStatusBarSettings;
- (void)dealloc;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)effectiveStatusBarStyleRequestForLevel:(unsigned long long)arg1;
- (id)effectiveStatusBarStyleRequestWithSettings:(id)arg1;
- (id)init;
- (bool)isStatusBarHidden;
- (bool)isStatusBarUserInteractionEnabled;
- (id)orientationWindowForLayoutLayer:(unsigned long long)arg1;
- (void)removeActiveLayoutLayer:(unsigned long long)arg1;
- (void)removeObserver:(id)arg1;
- (void)removeWindowLevelOverrideReason:(id)arg1;
- (void)setDefaultWindowLevel:(double)arg1;
- (void)setOrientationWindow:(id)arg1 forStatusBarLayoutLayer:(unsigned long long)arg2;
- (void)setStatusBarEdgeInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1 forLayoutLayer:(unsigned long long)arg2;
- (void)setStatusBarUserInteractionEnabled:(bool)arg1;
- (void)setWindowLevel:(double)arg1 forOverrideReason:(id)arg2;
- (int)statusBar:(id)arg1 effectiveStyleOverridesForRequestedStyle:(long long)arg2 overrides:(int)arg3;
- (bool)statusBar:(id)arg1 shouldRequestStyle:(long long)arg2 animationParameters:(id)arg3 forced:(bool)arg4;
- (bool)statusBar:(id)arg1 shouldRequestStyleAttributes:(id)arg2 animationParameters:(id)arg3 forced:(bool)arg4;
- (bool)statusBar:(id)arg1 shouldSetAlpha:(double)arg2;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })statusBarEdgeInsets;
- (bool)statusBarOrientationShouldFollowWindow:(id)arg1;
- (id)statusBarSettingsForLevel:(unsigned long long)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (unsigned long long)topmostActiveLayoutLayer;

@end
