/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppExitedWorkspaceTransaction : SBToAppsWorkspaceTransaction

- (void)_begin;
- (void)_didComplete;

@end
