/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBApplicationBlurContentView : UIView {
    UIView * _blurView;
    UIView * _blurredSnapshotView;
    SBSceneViewAppIconView * _iconView;
    UIView * _liveBlurView;
    NSMutableDictionary * _mapStateToCompletionBlocks;
    SBDeviceApplicationSceneHandle * _sceneHandle;
    SBApplicationBlurSnapshotGenerationContainerView * _snapshotGenerationContainerView;
    unsigned long long  _state;
    struct CGSize { 
        double width; 
        double height; 
    }  _targetViewOriginalSize;
    UIView * _targetViewToBlur;
    UIView * _unblurredCopySnapshotView;
    UIView * _unblurredRealSnapshotView;
}

@property (nonatomic, readonly) SBSceneViewAppIconView *iconView;

- (void).cxx_destruct;
- (void)_addCompletionBlock:(id /* block */)arg1 forState:(unsigned long long)arg2;
- (void)_doAnimationToBlurredSnapshotWithFactory:(id)arg1 completion:(id /* block */)arg2;
- (void)_doBlurGenerationWithCompletion:(id /* block */)arg1;
- (void)_fireCompletionBlocksForState:(unsigned long long)arg1;
- (id)_iconViewForApplication;
- (void)_setState:(unsigned long long)arg1;
- (void)animateToBlurredSnapshotWithFactory:(id)arg1 completion:(id /* block */)arg2;
- (void)dealloc;
- (void)didMoveToWindow;
- (void)generateAndAnimateToBlurredSnapshotWithAnimationFactory:(id)arg1 completion:(id /* block */)arg2;
- (void)generateBlurredSnapshotWithCompletion:(id /* block */)arg1;
- (id)iconView;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 deviceApplicationSceneHandle:(id)arg2 targetViewToBlur:(id)arg3;
- (void)layoutSubviews;

@end
