/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppSwitcherSnapshotLockoutViewControllerProvider : NSObject {
    NSMutableArray * _availableControllers;
}

- (void).cxx_destruct;
- (void)_receivedMemoryWarning:(id)arg1;
- (void)dealloc;
- (id)init;
- (id)lockoutViewControllerForBundleIdentifier:(id)arg1;
- (void)recycleLockoutViewController:(id)arg1;

@end
