/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppBrightnessMetricData : SBAWDMetricData {
    NSString * _appBundleID;
    unsigned long long  _brightness;
    unsigned long long  _duration;
}

@property (nonatomic, copy) NSString *appBundleID;
@property (nonatomic) unsigned long long brightness;
@property (nonatomic) unsigned long long duration;

- (void).cxx_destruct;
- (id)appBundleID;
- (unsigned long long)brightness;
- (unsigned long long)duration;
- (void)setAppBundleID:(id)arg1;
- (void)setBrightness:(unsigned long long)arg1;
- (void)setDuration:(unsigned long long)arg1;

@end
