/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppBrightnessMetric : SBAWDMetric

- (id)configureWithData:(id)arg1;
- (Class)dataClass;
- (unsigned long long)metricID;
- (void)postWithDataBuilder:(id /* block */)arg1;

@end
