/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppUnderFloatingSwitcherTransitionSwitcherModifier : SBTransitionSwitcherModifier

- (long long)liveContentRasterizationStyle;
- (bool)shouldTetherTransitionCompletion;
- (bool)wantsMinificationFilter;

@end
