/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBApplicationSceneSpecification : UIApplicationSceneSpecification

- (id)baseSceneComponentClassDictionary;
- (Class)uiSceneMinimumClass;

@end
