/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppSwitcherSnapshotViewState : NSObject {
    bool  _animatingTransition;
    SBAppSwitcherSnapshotCacheEntry * _cacheEntry;
    SBDeviceApplicationSceneHandle * _sceneHandle;
}

@property (getter=isAnimatingTransition, nonatomic) bool animatingTransition;
@property (nonatomic, retain) SBAppSwitcherSnapshotCacheEntry *cacheEntry;
@property (nonatomic, retain) SBDeviceApplicationSceneHandle *sceneHandle;

- (void).cxx_destruct;
- (id)cacheEntry;
- (bool)isAnimatingTransition;
- (id)sceneHandle;
- (void)setAnimatingTransition:(bool)arg1;
- (void)setCacheEntry:(id)arg1;
- (void)setSceneHandle:(id)arg1;

@end
