/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAppBrightnessChangeLogger : NSObject {
    long long  _brightnessLevel;
    NSString * _bundleID;
    NSDate * _eventTimestamp;
}

@property (nonatomic) long long brightnessLevel;
@property (nonatomic, copy) NSString *bundleID;
@property (nonatomic, copy) NSDate *eventTimestamp;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_publishMetrics;
- (void)_publishMetricsIfNeeded;
- (void)_screenLocked;
- (long long)brightnessLevel;
- (id)bundleID;
- (id)eventTimestamp;
- (id)init;
- (void)noteApp:(id)arg1 setScreenBrightness:(double)arg2;
- (void)setBrightnessLevel:(long long)arg1;
- (void)setBundleID:(id)arg1;
- (void)setEventTimestamp:(id)arg1;

@end
