/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAttentionAwarenessClient : NSObject {
    AWAttentionAwarenessClient * _attentionAwarenessClient;
    <SBAttentionAwarenessClientDelegate> * _delegate;
    bool  _enabled;
    NSObject<OS_dispatch_queue> * _queue;
    AWAttentionAwarenessConfiguration * _queue_configuration;
}

@property (nonatomic, retain) AWAttentionAwarenessClient *attentionAwarenessClient;
@property (nonatomic, retain) AWAttentionAwarenessConfiguration *configuration;
@property (nonatomic) <SBAttentionAwarenessClientDelegate> *delegate;
@property (getter=isEnabled, nonatomic) bool enabled;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *queue;

- (void).cxx_destruct;
- (void)_handleAttentionAwarenessEvent:(id)arg1;
- (void)_resetAttentionLostTimeout;
- (void)_resume;
- (void)_suspend;
- (id)attentionAwarenessClient;
- (id)configuration;
- (id)delegate;
- (id)init;
- (bool)isEnabled;
- (id)queue;
- (void)resetAttentionLostTimeout;
- (void)setAttentionAwarenessClient:(id)arg1;
- (void)setConfiguration:(id)arg1;
- (void)setConfiguration:(id)arg1 shouldReset:(bool)arg2;
- (void)setDelegate:(id)arg1;
- (void)setEnabled:(bool)arg1;
- (void)setQueue:(id)arg1;

@end
