/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAttentionAwareIdleTimer : SBIdleTimerBase <BSDescriptionProviding, SBAttentionAwarenessClientDelegate> {
    SBAttentionAwarenessClient * _attentionAwarenessClient;
    unsigned long long  _configurationGeneration;
    NSString * _configurationIdentifier;
    SBIdleTimerDescriptor * _descriptor;
    long long  _expectation;
    bool  _requiresManualReset;
    double  _timeMultiplier;
}

@property (nonatomic, retain) SBAttentionAwarenessClient *attentionAwarenessClient;
@property (getter=_configurationGeneration, nonatomic, readonly) unsigned long long configurationGeneration;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) SBIdleTimerDescriptor *descriptor;
@property (nonatomic) long long expectation;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool requiresManualReset;
@property (readonly) Class superclass;
@property (nonatomic) double timeMultiplier;

- (void).cxx_destruct;
- (unsigned long long)_configurationGeneration;
- (double)_effectiveExpireTimeout;
- (double)_effectiveQuickUnwarnTimeoutForWarnTimeout:(double)arg1;
- (double)_effectiveTimeoutForBaseTimeout:(double)arg1;
- (double)_effectiveWarnTimeout;
- (void)_reconfigureAttentionClientAndReset:(bool)arg1;
- (void)_resetExpectation;
- (void)_stopIfManual;
- (id)_timeoutDictionaryForDescriptor:(id)arg1;
- (id)attentionAwarenessClient;
- (void)client:(id)arg1 attentionLostTimeoutDidExpire:(double)arg2 forConfigurationGeneration:(unsigned long long)arg3 withAssociatedObject:(id)arg4;
- (void)clientDidResetForUserAttention:(id)arg1;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)descriptor;
- (long long)expectation;
- (id)init;
- (id)initWithConfigurationIdentifier:(id)arg1;
- (id)initWithConfigurationIdentifier:(id)arg1 attentionAwarenessClient:(id)arg2;
- (bool)isActivated;
- (bool)isDisabled;
- (bool)requiresManualReset;
- (void)reset;
- (void)setActivated:(bool)arg1;
- (void)setAttentionAwarenessClient:(id)arg1;
- (void)setDescriptor:(id)arg1;
- (void)setExpectation:(long long)arg1;
- (void)setRequiresManualReset:(bool)arg1;
- (void)setTimeMultiplier:(double)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (double)timeMultiplier;

@end
