/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAttentionAwareIdleTimerTimeoutContext : NSObject {
    long long  _expectation;
}

@property (nonatomic, readonly) long long expectation;

- (id)description;
- (long long)expectation;
- (id)initWithExpectation:(long long)arg1;

@end
