/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAutoPiPWorkspaceTransaction : SBWorkspaceTransaction {
    SBWorkspaceEntity * _entityToPiP;
    long long  _inferredTransitionStyle;
    int  _pidToPiP;
    NSString * _reason;
    long long  _transitionStyle;
}

@property (nonatomic, readonly, copy) SBWorkspaceEntity *entityToPiP;
@property (nonatomic) long long transitionStyle;

+ (bool)_shouldAutoPiPEnteringBackgroundForRequest:(id)arg1 transientOverlayEntityFoundBlock:(id /* block */)arg2 appEntityFoundBlock:(id /* block */)arg3;
+ (bool)isSystemGesture:(id)arg1;
+ (bool)shouldAutoPiPEnteringBackgroundForRequest:(id)arg1;
+ (bool)shouldAutoPiPEnteringBackgroundForRequest:(id)arg1 entityFoundBlock:(id /* block */)arg2;
+ (long long)transitionStyleForProcessIdentifier:(int)arg1 entityToPiP:(id)arg2 withTransitionContext:(id)arg3 request:(id)arg4;

- (void).cxx_destruct;
- (void)_begin;
- (bool)_canBeInterrupted;
- (id)_customizedDescriptionProperties;
- (void)_didComplete;
- (long long)_transitionStyle;
- (id)entityToPiP;
- (id)initWithTransitionRequest:(id)arg1;
- (id)initWithTransitionRequest:(id)arg1 includeActiveAppEntity:(bool)arg2;
- (void)setTransitionStyle:(long long)arg1;
- (long long)transitionStyle;

@end
