/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAVSystemControllerCache : NSObject {
    NSObject<OS_dispatch_queue> * _backgroundQueryQueue;
    NSObject<OS_dispatch_queue> * _callOutQueue;
    id /* block */  _dataProviderInitializer;
    NSNotificationCenter * _notificationCenter;
    NSMutableDictionary * _notificationToBackgroundQueryCancellationSignalMap;
    NSMutableDictionary * _notificationToHandlerMap;
    bool  _outputContextSupportsMultipleOutputDevices;
    NSObject<OS_dispatch_queue> * _queue;
    NSString * _queue_activeAudioRoute;
    NSDictionary * _queue_activeAudioRouteInfo;
    NSArray * _queue_activeOutputDevices;
    bool  _queue_airplayDisplayActive;
    <SBAVSystemControllerDataProviding> * _queue_dataProvider;
    bool  _queue_fullyMuted;
    bool  _queue_initialized;
    NSHashTable * _queue_observers;
    AVOutputContext * _queue_outputContext;
    NSArray * _queue_pickableRoutes;
    int  _queue_recordingPID;
    BSAtomicSignal * _queue_serverDeathSignal;
    float  _queue_volumeLimit;
    bool  _queue_volumeLimitEnforced;
}

@property (nonatomic, readonly, copy) NSString *activeAudioRoute;
@property (nonatomic, readonly, copy) NSDictionary *activeAudioRouteInfo;
@property (nonatomic, readonly, copy) NSArray *activeOutputDevices;
@property (getter=isAirplayDisplayActive, nonatomic, readonly) bool airplayDisplayActive;
@property (getter=isFullyMuted, nonatomic, readonly) bool fullyMuted;
@property (nonatomic, readonly, copy) NSArray *pickableRoutes;
@property (nonatomic, readonly) int recordingPID;
@property (nonatomic, readonly) float volumeLimit;
@property (getter=isVolumeLimitEnforced, nonatomic, readonly) bool volumeLimitEnforced;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)_queryActiveOutputDevicesFromContext:(id)arg1;
- (id)_queue_backgroundQueryCancellationSignalForNotificationCreatingIfNecessary:(id)arg1;
- (void)_queue_notifyObserversWithBlock:(id /* block */)arg1;
- (void)_queue_rebuildCache;
- (void)_queue_signalBackgroundQueryCancellationForNotification:(id)arg1;
- (void)_queue_updateActiveAudioRouteFromNotification:(id)arg1 allowingBackgroundQueries:(bool)arg2 backgroundQueriesCancelledBlock:(id /* block */)arg3 cancelBackgroundQueriesBlock:(id /* block */)arg4 completion:(id /* block */)arg5;
- (void)_queue_updateActiveOutputDevicesFromNotification:(id)arg1 allowingBackgroundQueries:(bool)arg2 backgroundQueriesCancelledBlock:(id /* block */)arg3 cancelBackgroundQueriesBlock:(id /* block */)arg4 completion:(id /* block */)arg5;
- (void)_queue_updateAirplayDisplayActiveFromNotification:(id)arg1 allowingBackgroundQueries:(bool)arg2 backgroundQueriesCancelledBlock:(id /* block */)arg3 cancelBackgroundQueriesBlock:(id /* block */)arg4 completion:(id /* block */)arg5;
- (void)_queue_updateFullyMutedFromNotification:(id)arg1 allowingBackgroundQueries:(bool)arg2 backgroundQueriesCancelledBlock:(id /* block */)arg3 cancelBackgroundQueriesBlock:(id /* block */)arg4 completion:(id /* block */)arg5;
- (void)_queue_updatePickableRoutesFromNotification:(id)arg1 allowingBackgroundQueries:(bool)arg2 backgroundQueriesCancelledBlock:(id /* block */)arg3 cancelBackgroundQueriesBlock:(id /* block */)arg4 completion:(id /* block */)arg5;
- (void)_queue_updateRecordingPIDFromNotification:(id)arg1 allowingBackgroundQueries:(bool)arg2 backgroundQueriesCancelledBlock:(id /* block */)arg3 cancelBackgroundQueriesBlock:(id /* block */)arg4 completion:(id /* block */)arg5;
- (void)_queue_updateVolumeLimitEnforcedFromNotification:(id)arg1 allowingBackgroundQueries:(bool)arg2 backgroundQueriesCancelledBlock:(id /* block */)arg3 cancelBackgroundQueriesBlock:(id /* block */)arg4 completion:(id /* block */)arg5;
- (void)_queue_updateVolumeLimitFromNotification:(id)arg1 allowingBackgroundQueries:(bool)arg2 backgroundQueriesCancelledBlock:(id /* block */)arg3 cancelBackgroundQueriesBlock:(id /* block */)arg4 completion:(id /* block */)arg5;
- (void)_receiveUpdatedValueFromNotification:(id)arg1;
- (void)_serverDied:(id)arg1;
- (id)activeAudioRoute;
- (id)activeAudioRouteInfo;
- (id)activeOutputDevices;
- (void)addObserver:(id)arg1;
- (void)dealloc;
- (void)fetchPickableRoutesWithCompletion:(id /* block */)arg1;
- (id)init;
- (id)initWithCallOutQueue:(id)arg1 notificationCenter:(id)arg2 dataProviderInitializer:(id /* block */)arg3;
- (bool)isAirplayDisplayActive;
- (bool)isFullyMuted;
- (bool)isVolumeLimitEnforced;
- (id)pickableRoutes;
- (int)recordingPID;
- (float)volumeLimit;

@end
