/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBAWDQueryableMetric : SBAWDMetric {
    id /* block */  _builder;
    AWDServerConnection * _connection;
}

- (void).cxx_destruct;
- (void)_postQueryableMetric;
- (void)registerWithDataBuilder:(id /* block */)arg1;

@end
