/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBBackgroundFetchTask : NSObject {
    NSString * _bundleID;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    RBSAssertion * _lock_assertion;
    id /* block */  _lock_completionHandler;
    bool  _lock_finished;
    int  _sequenceNumber;
}

+ (int)_nextSequenceNumber;

- (void).cxx_destruct;
- (void)dealloc;
- (id)description;
- (void)execute;
- (void)finishWithResult:(unsigned long long)arg1;
- (id)initForApplication:(id)arg1 withCompletion:(id /* block */)arg2;

@end
