/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBBackgroundFetchExternalRequest : NSObject {
    UIFetchContentInBackgroundAction * _action;
    SBBackgroundFetchTask * _task;
}

@property (nonatomic, readonly) UIFetchContentInBackgroundAction *action;

- (void).cxx_destruct;
- (id)action;
- (void)dealloc;
- (void)execute;
- (id)initForBundleID:(id)arg1;

@end
