/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBBannerContainerViewController : UIViewController <UIScrollViewDelegate, UIViewControllerTransitioningDelegate> {
    SBBannerContainerView * _bannerContainerView;
    SBUIBannerContext * _bannerContext;
    SBBannerContextView * _bannerContextView;
    NCBannerPresentationTransitionDelegate * _bannerPresentationTransitionDelegate;
    <SBBannerContainerViewControllerDelegate> * _delegate;
    UIScrollView * _scrollView;
}

@property (nonatomic, readonly) SBBannerContainerView *bannerContainerView;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBBannerContainerViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_bannerContextViewCreatingIfNecessary;
- (bool)_canShowWhileLocked;
- (void)_handleBannerTapGesture:(id)arg1;
- (void)_tryDismissingBannerInScrollView:(id)arg1;
- (id)bannerContainerView;
- (id)delegate;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (long long)preferredInterfaceOrientationForPresentation;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(bool)arg2;
- (void)setBannerContext:(id)arg1 withReplaceReason:(int)arg2 completion:(id /* block */)arg3;
- (void)setDelegate:(id)arg1;
- (void)viewWillLayoutSubviews;

@end
