/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBBannerContainerView : PLPlatterView {
    SBBannerContextView * _bannerContextView;
}

@property (nonatomic, readonly, retain) SBUIBannerContext *bannerContext;
@property (nonatomic, retain) SBBannerContextView *bannerContextView;

- (void).cxx_destruct;
- (id)bannerContext;
- (id)bannerContextView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)noteDidAppear;
- (void)noteDidDismissWithReason:(int)arg1;
- (void)noteWillAppear;
- (void)noteWillDismissWithReason:(int)arg1;
- (void)setBannerContextView:(id)arg1;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

@end
