/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBBatteryWidgetVisibilityController : NSObject

+ (id)sharedInstance;

- (void)_connectedDevicesDidChange;
- (bool)_containsExternalBattery;
- (bool)_isAlwaysVisible;
- (bool)_isVisible;
- (void)_makeVisible;
- (void)_setVisibleIfNecessary:(bool)arg1;
- (id)init;

@end
