/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBBluetoothAccessoryBatteryMonitor : NSObject {
    NSMutableSet * _accessoryNamesInLowPower;
}

- (void).cxx_destruct;
- (void)_popLowPowerAlertForAccessoryIfNecessary:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)descriptionBuilder;
- (id)init;

@end
