/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBBrightnessHUDViewController : SBHUDViewController

- (bool)displaysLabel;
- (id)init;

@end
