/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBBreadcrumbActionContext : NSObject {
    UISystemNavigationAction * _action;
    LSAppLink * _appLink;
    NSDictionary * _appLinkState;
    NSString * _breadcrumbAppBundleID;
    NSString * _breadcrumbSceneID;
    NSDictionary * _destinationContexts;
    bool  _didCaptureContext;
    unsigned long long  _lastSource;
    unsigned long long  _leftType;
    NSString * _previousSideBundleId;
    NSString * _primaryTitle;
    id /* block */  _responseHandler;
    unsigned long long  _rightType;
    NSString * _secondaryTitle;
    bool  _wasFromAssistant;
    bool  _wasFromSpotlight;
}

@property (nonatomic, retain) UISystemNavigationAction *action;
@property (nonatomic, copy) NSDictionary *destinationContexts;
@property (nonatomic, copy) id /* block */ responseHandler;

- (void).cxx_destruct;
- (id)action;
- (void)dealloc;
- (id)destinationContexts;
- (id /* block */)responseHandler;
- (void)setAction:(id)arg1;
- (void)setDestinationContexts:(id)arg1;
- (void)setResponseHandler:(id /* block */)arg1;

@end
