/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBBulletinWindowPresentationController : UIPresentationController {
    double  _counterRotatedAngle;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _counterRotatedOriginalBounds;
    UIView * _counterRotatedView;
}

@property (getter=_counterRotatedAngle, setter=_setCounterRotatedAngle:, nonatomic) double counterRotatedAngle;
@property (getter=_counterRotatedOriginalBounds, setter=_setCounterRotatedOriginalBounds:, nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } counterRotatedOriginalBounds;
@property (getter=_counterRotatedView, setter=_setCounterRotatedView:, nonatomic, retain) UIView *counterRotatedView;

- (void).cxx_destruct;
- (void)_adjustOrientationIfNecessaryInWindow:(id)arg1 forViewController:(id)arg2 preservingViewController:(id)arg3;
- (double)_counterRotatedAngle;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_counterRotatedOriginalBounds;
- (id)_counterRotatedView;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_frameForTransitionViewInPresentationSuperview:(id)arg1;
- (void)_removeCounterRotationIfNecessary;
- (void)_setCounterRotatedAngle:(double)arg1;
- (void)_setCounterRotatedOriginalBounds:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)_setCounterRotatedView:(id)arg1;
- (bool)_shouldDisableInteractionDuringTransitions;
- (void)dismissalTransitionDidEnd:(bool)arg1;
- (id)initWithPresentedViewController:(id)arg1 presentingViewController:(id)arg2;
- (void)presentationTransitionDidEnd:(bool)arg1;
- (bool)shouldPresentInFullscreen;
- (bool)shouldRemovePresentersView;

@end
