/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBC2GroupCompletion : NSObject

+ (void)perform:(id /* block */)arg1 finalCompletion:(id /* block */)arg2;
+ (void)perform:(id /* block */)arg1 finalCompletion:(id /* block */)arg2 options:(unsigned long long)arg3;

@end
