/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBCancelableBlockOperation : NSOperation {
    NSMutableArray * _blocks;
}

- (void).cxx_destruct;
- (void)addBlock:(id /* block */)arg1;
- (id)init;
- (void)main;

@end
