/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBChainableModifier : NSObject <BSDescriptionProviding, SBChainableModifierContext, SBChainableModifierQuery> {
    SBModifierMethodCache * _contextCache;
    <SBChainableModifierDelegate> * _delegate;
    bool  _hasNotifiedChildrenDidMoveToParent;
    NSString * _key;
    long long  _modifierLevel;
    SBChainableModifier * _nextQueryModifier;
    SBChainableModifier * _parentModifier;
    SBChainableModifier * _previousContextModifier;
    SBModifierMethodCache * _queryCache;
}

@property (nonatomic, retain) SBModifierCacheCoordinator *contextCacheCoordinator;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBChainableModifierDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSString *key;
@property (nonatomic) long long modifierLevel;
@property (nonatomic, retain) SBChainableModifier *nextQueryModifier;
@property (nonatomic) SBChainableModifier *parentModifier;
@property (nonatomic) SBChainableModifier *previousContextModifier;
@property (nonatomic, retain) SBModifierCacheCoordinator *queryCacheCoordinator;
@property (readonly) Class superclass;

+ (id)baseClassForQueryProtocol;
+ (id)contextProtocol;
+ (id)contextSelectors;
+ (void)initalizeIMPCaching;
+ (void)initialize;
+ (id)newCacheWithSelectorList:(id)arg1 subsequentMethodCacheFunc:(int (*)arg2 cachingDictionary:(id)arg3;
+ (id)newContextCache;
+ (id)newQueryCache;
+ (id)queryProtocol;
+ (id)querySelectors;
+ (void)verifyIsFloorModifier;

- (void).cxx_destruct;
- (void)_addChildModifier:(id)arg1 atLevel:(long long)arg2 key:(id)arg3 queryAction:(unsigned long long)arg4 contextAction:(unsigned long long)arg5;
- (void)_addChildModifier:(id)arg1 queryAction:(unsigned long long)arg2 contextAction:(unsigned long long)arg3;
- (void)_addImplementation:(id)arg1 forClass:(Class)arg2 selector:(SEL)arg3 protocol:(id)arg4;
- (bool)_anyDescendentImplementsAnyContextMethod;
- (bool)_anyDescendentImplementsAnyQueryMethod;
- (id)_createAndConfigureDynamicModifierWithName:(id)arg1;
- (void)_insertModifier:(id)arg1 afterModifier:(id)arg2 queryAction:(unsigned long long)arg3 contextAction:(unsigned long long)arg4;
- (id)_lastDeepChildModifier;
- (id)_nextDynamicQueryModifier;
- (void)_notifyChildrenDidMoveToParentIfNeeded;
- (id)_previousDynamicContextModifier;
- (void)_removeChildModifier:(id)arg1 queryAction:(unsigned long long)arg2 contextAction:(unsigned long long)arg3;
- (void)addChildModifier:(id)arg1;
- (void)addChildModifier:(id)arg1 atLevel:(long long)arg2 key:(id)arg3;
- (id)childModifierByKey:(id)arg1;
- (unsigned long long)childModifierCount;
- (bool)containsChildModifier:(id)arg1;
- (id)contextCacheCoordinator;
- (void)dealloc;
- (id)delegate;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)didMoveToParentModifier:(id)arg1;
- (void)enumerateChildModifiersWithBlock:(id /* block */)arg1;
- (id)init;
- (id)key;
- (long long)modifierLevel;
- (id)nextQueryModifier;
- (id)parentModifier;
- (void)performTransactionWithTemporaryChildModifier:(id)arg1 usingBlock:(id /* block */)arg2;
- (id)previousContextModifier;
- (void)provideNextQueryImplementation:(id)arg1 forSelector:(SEL)arg2;
- (void)providePreviousContextImplementation:(id)arg1 forSelector:(SEL)arg2;
- (id)queryCacheCoordinator;
- (void)removeChildModifier:(id)arg1;
- (void)removeChildModifiers:(id)arg1;
- (bool)respondsToSelectorWithoutForwarding:(SEL)arg1;
- (void)setContextCacheCoordinator:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setKey:(id)arg1;
- (void)setModifierLevel:(long long)arg1;
- (void)setNextQueryModifier:(id)arg1;
- (void)setParentModifier:(id)arg1;
- (void)setPreviousContextModifier:(id)arg1;
- (void)setQueryCacheCoordinator:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end
