/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBClientSettingObserverContext : NSObject {
    FBSSceneClientSettings * _oldClientSettings;
    FBScene * _scene;
    SBDeviceApplicationSceneHandle * _sceneHandle;
    FBSSceneTransitionContext * _transition;
}

@property (nonatomic, retain) FBSSceneClientSettings *oldClientSettings;
@property (nonatomic, retain) FBScene *scene;
@property (nonatomic, retain) SBDeviceApplicationSceneHandle *sceneHandle;
@property (nonatomic, retain) FBSSceneTransitionContext *transition;

- (void).cxx_destruct;
- (id)oldClientSettings;
- (id)scene;
- (id)sceneHandle;
- (void)setOldClientSettings:(id)arg1;
- (void)setScene:(id)arg1;
- (void)setSceneHandle:(id)arg1;
- (void)setTransition:(id)arg1;
- (id)transition;

@end
