/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBClawGestureMetricData : SBAWDMetricData {
    bool  _didPressLock;
    bool  _didPressVolumeDown;
    bool  _didPressVolumeUp;
    bool  _didTriggerSOS;
    unsigned long long  _duration;
}

@property (nonatomic) bool didPressLock;
@property (nonatomic) bool didPressVolumeDown;
@property (nonatomic) bool didPressVolumeUp;
@property (nonatomic) bool didTriggerSOS;
@property (nonatomic) unsigned long long duration;

- (bool)didPressLock;
- (bool)didPressVolumeDown;
- (bool)didPressVolumeUp;
- (bool)didTriggerSOS;
- (unsigned long long)duration;
- (void)setDidPressLock:(bool)arg1;
- (void)setDidPressVolumeDown:(bool)arg1;
- (void)setDidPressVolumeUp:(bool)arg1;
- (void)setDidTriggerSOS:(bool)arg1;
- (void)setDuration:(unsigned long long)arg1;

@end
