/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBClawGestureLogger : NSObject {
    NSMutableSet * _activePressTypes;
    NSDate * _clawEventTimestamp;
    bool  _didTriggerSOS;
    NSMutableSet * _participatingPressTypes;
}

@property (nonatomic, retain) NSMutableSet *activePressTypes;
@property (nonatomic, copy) NSDate *clawEventTimestamp;
@property (nonatomic) bool didTriggerSOS;
@property (nonatomic, retain) NSMutableSet *participatingPressTypes;

- (void).cxx_destruct;
- (void)_publishLoggedData;
- (void)_resetLoggedData;
- (id)activePressTypes;
- (id)clawEventTimestamp;
- (bool)didTriggerSOS;
- (id)init;
- (void)noteGesturePressType:(long long)arg1 withPressPhase:(long long)arg2;
- (void)noteSOSTriggered;
- (id)participatingPressTypes;
- (void)setActivePressTypes:(id)arg1;
- (void)setClawEventTimestamp:(id)arg1;
- (void)setDidTriggerSOS:(bool)arg1;
- (void)setParticipatingPressTypes:(id)arg1;

@end
