/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBCombinationHardwareButtonActions : NSObject

- (void)performPresentPowerDownTransientOverlayAction;
- (void)performTakeScreenshotAction;

@end
