/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBCoverSheetParallaxContainerView : SBFTouchPassThroughView

- (void)_setPresentationValue:(id)arg1 forKey:(id)arg2;

@end
