/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBCompleteGestureSwitcherModifierAction : SBSwitcherModifierAction

- (long long)type;

@end
