/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBControlCenterPresentationObservationToken : SBPresentationObservationToken {
    SBControlCenterController * _controlCenterController;
}

@property (nonatomic, readonly) SBControlCenterController *controlCenterController;

- (void).cxx_destruct;
- (id)controlCenterController;
- (void)dealloc;
- (id)initWithControlCenterController:(id)arg1;
- (long long)state;

@end
