/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBCoverSheetWindow : SBSecureWindow

+ (bool)sb_autorotates;

- (bool)_canBecomeKeyWindow;
- (bool)becomeFirstResponder;
- (id)hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (bool)resignFirstResponder;

@end
