/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDataPlanAlertItem : SBAlertItem

- (void)didDeactivateForReason:(int)arg1;
- (bool)suppressForKeynote;

@end
