/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDashBoardThermalStatusProvider : NSObject <CSThermalStatusProviding> {
    SBThermalController * _thermalController;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (nonatomic, readonly) long long thermalStatus;

- (void).cxx_destruct;
- (id)init;
- (id)initWithThermalController:(id)arg1;
- (long long)thermalStatus;

@end
