/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDashBoardHomeAffordanceControllerClientBridge : NSObject <SBNotificationHomeAffordanceControllerClient> {
    <CSHomeGestureParticipating> * _coverSheetHomeGestureParticipant;
}

- (void).cxx_destruct;
- (void)homeGestureParticipantOwningHomeGestureDidChange:(id)arg1;
- (id)initWithCoverSheetHomeGestureParticipant:(id)arg1;

@end
