/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDeviceApplicationSceneViewController : SBApplicationSceneViewController <SBDeviceApplicationSceneHandleObserver, SBDeviceApplicationSceneOverlayViewProviderDelegate, SBDeviceApplicationSceneViewControlling, SBSceneViewDelegate, SBSceneViewStatusBarAssertionObserver> {
    SBSceneViewStatusBarAssertion * _activeOverlayStatusBarAssertion;
    NSMutableArray * _activeOverlayViewProviders;
    UIStatusBar * _fakeStatusBar;
    long long  _homeGrabberDisplayMode;
    MTLumaDodgePillSettings * _homeGrabberPillSettings;
    SBFHomeGrabberSettings * _homeGrabberSettings;
    <BSInvalidatable> * _liveContentDisableAssertion;
    NSMutableArray * _overlayViewProviders;
    SBSceneViewStatusBarAssertion * _placeholderStatusBarAssertion;
    bool  _rendersWhileLocked;
    UIApplicationSceneDeactivationAssertion * _resignActiveAssertion;
    NSString * _sceneHostViewMinificationFilter;
    bool  _shouldRasterizeSceneHostView;
    NSHashTable * _statusBarAssertions;
}

@property (nonatomic) <SBApplicationSceneViewControllingStatusBarDelegate> *applicationSceneStatusBarDelegate;
@property (nonatomic, readonly) long long contentInterfaceOrientation;
@property (nonatomic, readonly) struct CGSize { double x1; double x2; } contentReferenceSize;
@property (nonatomic, retain) UIView *customContentView;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) long long displayMode;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long homeGrabberDisplayMode;
@property (nonatomic, retain) MTLumaDodgePillSettings *homeGrabberPillSettings;
@property (nonatomic, readonly) SBHomeGrabberView *homeGrabberView;
@property (nonatomic, readonly) long long overrideStatusBarStyle;
@property (nonatomic, retain) <SBScenePlaceholderContentContext> *placeholderContentContext;
@property (nonatomic) bool rendersWhileLocked;
@property (nonatomic, readonly) SBSceneHandle *sceneHandle;
@property (nonatomic, copy) NSString *sceneHostViewMinificationFilter;
@property (getter=_sceneView, nonatomic, readonly) SBDeviceApplicationSceneView *sceneView;
@property (nonatomic) bool shouldRasterizeSceneHostView;
@property (nonatomic, readonly) double statusBarAlpha;
@property (getter=_statusBarAssertions, setter=_setStatusBarAssertions:, nonatomic, retain) NSHashTable *statusBarAssertions;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_addFakeStatusBarWithStyleRequest:(id)arg1 enabledParts:(long long)arg2;
- (bool)_canShowWhileLocked;
- (bool)_configureFakeStatusBarWithCurrentStyleRequestCreatingIfNecessary;
- (void)_configureForCurrentSecureDisplayState;
- (void)_configureForSecureDisplay:(bool)arg1;
- (void)_createSceneOverlayViewProvidersIfNecessary;
- (void)_destroySceneOverlayViewProviders;
- (void)_didDisableSecureDisplay;
- (bool)_isApplicationStatusBarHidden;
- (void)_layoutFakeStatusBar;
- (void)_recalculateResignActiveAssertionForActiveOverlays;
- (void)_relinquishResignActiveAssertion;
- (void)_removeFakeStatusBar;
- (void)_setStatusBarAssertions:(id)arg1;
- (bool)_shouldSuppressHomeGrabber;
- (id)_statusBarAssertions;
- (void)_statusBarAssertionsDidUpdate;
- (void)_willEnableSecureDisplay;
- (void)activateOverlayForViewProvider:(id)arg1;
- (id)animationFactoryForImplicitTransitionFromMode:(long long)arg1 toMode:(long long)arg2 defaultFactory:(id)arg3;
- (void)deactivateOverlayForViewProvider:(id)arg1;
- (void)dealloc;
- (bool)definesPresentationContext;
- (void)didMoveToParentViewController:(id)arg1;
- (long long)homeGrabberDisplayMode;
- (id)homeGrabberPillSettings;
- (id)homeGrabberView;
- (id)initWithSceneHandle:(id)arg1;
- (void)invalidate;
- (bool)overlayViewProviderRendersWhileLocked:(id)arg1;
- (bool)rendersWhileLocked;
- (void)sceneHandle:(id)arg1 didChangeStatusBarAvoidanceFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (void)sceneHandle:(id)arg1 didChangeStatusBarParts:(long long)arg2;
- (id)sceneHostViewMinificationFilter;
- (void)sceneView:(id)arg1 changedPreferredStatusBarStyleTo:(long long)arg2;
- (void)setHomeGrabberDisplayMode:(long long)arg1;
- (void)setHomeGrabberPillSettings:(id)arg1;
- (void)setRendersWhileLocked:(bool)arg1;
- (void)setSceneHostViewMinificationFilter:(id)arg1;
- (void)setShouldRasterizeSceneHostView:(bool)arg1;
- (bool)shouldAutomaticallyForwardAppearanceMethods;
- (bool)shouldRasterizeSceneHostView;
- (void)statusBarAssertionDidInvalidate:(id)arg1;
- (void)statusBarAssertionDidUpdate:(id)arg1;
- (id)statusBarAssertionWithStatusBarHidden:(bool)arg1 atLevel:(unsigned long long)arg2;
- (id)statusBarAssertionWithStatusBarSettings:(id)arg1 atLevel:(unsigned long long)arg2;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;

@end
