/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDeckSwitcherForcePressGestureWorkspaceTransaction : SBFluidSwitcherGestureWorkspaceTransaction

- (void)_beginWithGesture:(id)arg1;
- (long long)_gestureType;

@end
