/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDeveloperBuildExpirationAlert : SBHomeScreenNagAlert

- (id)dismissButtonText;
- (id)init;

@end
