/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDefaultProximityBacklightPolicy : NSObject <SBProximityBacklightPolicy> {
    SBBacklightController * _backlightController;
    bool  _scheduled;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_backlightWillUndim:(id)arg1;
- (void)_cancelScheduledBacklightFactorToZero;
- (void)_doBacklightFactorChange;
- (void)_restoreBacklightFactor;
- (void)_scheduleBacklightFactorToZeroAfterDebounceDuration:(double)arg1;
- (void)_scheduleBacklightFactorToZeroAfterDefaultDuration;
- (void)dealloc;
- (id)initWithBacklightController:(id)arg1;
- (void)proximitySensorManager:(id)arg1 objectWithinProximityDidChange:(bool)arg2;

@end
