/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBDropApplicationFloatingSwitcherModifier : SBTransitionSwitcherModifier {
    SBAppLayout * _fromAppLayout;
    SBAppLayout * _toAppLayout;
}

- (void).cxx_destruct;
- (id)initWithTransitionID:(id)arg1 fromAppLayout:(id)arg2 toAppLayout:(id)arg3;
- (bool)isIndexVisible:(unsigned long long)arg1;
- (long long)keyboardSuppressionMode;
- (long long)liveContentRasterizationStyle;
- (double)opacityForIndex:(unsigned long long)arg1;
- (bool)shouldPerformCrossfadeForReduceMotion;
- (id)transitionWillBegin;
- (bool)wantsResignActiveAssertion;

@end
