/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBEmitStudyLogSwitcherModifierAction : SBSwitcherModifierAction {
    NSString * _name;
    NSDictionary * _payload;
}

@property (nonatomic, readonly, copy) NSString *name;
@property (nonatomic, readonly) NSDictionary *payload;

- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)initWithStudyLogWithName:(id)arg1 payload:(id)arg2;
- (id)name;
- (id)payload;
- (long long)type;

@end
