/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBEntityRemovalDosidoSlideOutDownwardAnimationSettings : SBEntityRemovalDosidoSlideOutAnimationSettings

- (void)setDefaultValues;

@end
