/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBEntityRemovalSlideOffscreenSwitcherModifier : SBTransitionSwitcherModifier {
    SBEntityRemovalDosidoSlideOutAnimationSettings * _animationSettings;
    SBAppLayout * _appLayout;
    unsigned long long  _direction;
    bool  _isSecondStage;
    SBSwitcherModifier * _multitaskingModifier;
    SBEntityRemovalToHomeSwitcherModifier * _toHomeRemovalModifier;
    NSUUID * _transitionID;
}

- (void).cxx_destruct;
- (void)didMoveToParentModifier:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForIndex:(unsigned long long)arg1;
- (id)handleTimerEvent:(id)arg1;
- (id)initWithTransitionID:(id)arg1 appLayout:(id)arg2 direction:(unsigned long long)arg3 animationSettings:(id)arg4 multitaskingModifier:(id)arg5;
- (bool)isIndexVisible:(unsigned long long)arg1;
- (id)layoutSettings;
- (double)scaleForIndex:(unsigned long long)arg1;
- (id)transitionWillBegin;
- (id)transitionWillUpdate;

@end
