/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBEntityRemovalDeleteFloatingSwitcherModifier : SBTransitionSwitcherModifier {
    bool  _blursFromAppLayout;
    long long  _floatingConfiguration;
    SBAppLayout * _fromAppLayout;
    SBAppLayout * _toAppLayout;
}

@property (nonatomic) bool blursFromAppLayout;

- (void).cxx_destruct;
- (bool)_isIndexFromAppLayout:(unsigned long long)arg1;
- (bool)_isIndexToAppLayout:(unsigned long long)arg1;
- (bool)blursFromAppLayout;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })containerViewBounds;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForIndex:(unsigned long long)arg1;
- (id)initWithTransitionID:(id)arg1 fromAppLayout:(id)arg2 toAppLayout:(id)arg3 floatingConfiguration:(long long)arg4;
- (bool)isIndexVisible:(unsigned long long)arg1;
- (id)layoutSettings;
- (double)opacityForIndex:(unsigned long long)arg1;
- (id)opacitySettings;
- (double)scaleForIndex:(unsigned long long)arg1;
- (void)setBlursFromAppLayout:(bool)arg1;
- (double)shadowOpacityForIndex:(unsigned long long)arg1;
- (id)topMostAppLayouts;
- (id)transitionDidEnd;
- (id)transitionWillBegin;
- (id)transitionWillUpdate;

@end
