/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBEntityRemovalMedusaSlideOutUpwardAnimationSettings : SBEntityRemovalMedusaSlideOutAnimationSettings

@end
