/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBExternalDisplayController : NSObject <SBSceneLayoutSlaveTransactionProviding> {
    FBSDisplayConfiguration * _currentConfiguration;
    bool  _disconnected;
    bool  _hasConnectTransactionRun;
    FBSDisplayIdentity * _identity;
    SBMainDisplaySceneManager * _mainDisplaySceneManager;
    SBMainWorkspace * _mainWorkspace;
    bool  _observingAppState;
    NSMutableArray * _pendingWork;
    SBExternalDisplayPresenter * _presenter;
    bool  _tornDown;
    <SBFAuthenticationStatusProvider> * _userAuthenticationProvider;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) FBSDisplayIdentity *displayIdentity;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_appProcessStateDidChange:(id)arg1;
- (bool)_application:(id)arg1 canAccessDisplay:(id)arg2;
- (void)_authenicationStateDidChange:(id)arg1;
- (id)_createUpdateTransactionWithLabel:(id)arg1;
- (bool)_displayConnectShouldWaitForAppRunning:(id)arg1;
- (id)_expectedForegroundApp;
- (void)_handleDisplayConnectIfPossible;
- (void)_runRootTransaction:(id)arg1 withLabel:(id)arg2 completion:(id /* block */)arg3;
- (void)_runRootUpdateTransactionWithLabel:(id)arg1 completion:(id /* block */)arg2;
- (bool)_shouldConnectDisplayNow:(id)arg1;
- (void)dealloc;
- (void)disconnectWithCompletion:(id /* block */)arg1;
- (id)displayIdentity;
- (id)init;
- (id)initWithMainWorkspace:(id)arg1 userAuthenticationProvider:(id)arg2 mainDisplaySceneManager:(id)arg3 layoutPublisher:(id)arg4 displayConfiguration:(id)arg5;
- (bool)isConnected;
- (id)slaveTransactionsForTransitionRequest:(id)arg1;
- (void)updateWithConfiguration:(id)arg1;

@end
