/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBExternalNotesDefaults : BSAbstractDefaultDomain

@property (nonatomic) bool quickNotesDisabled;

- (void)_bindAndRegisterDefaults;
- (id)init;

@end
