/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBExternalDemoDefaults : BSAbstractDefaultDomain

@property (nonatomic, readonly) bool shouldLockIconsInStoreDemoMode;

- (void)_bindAndRegisterDefaults;
- (id)init;

@end
