/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBExternalDisplayPresenter : NSObject <BSInvalidatable, SBSceneHandleObserver> {
    CADisplay * _caDisplay;
    FBSDisplayConfiguration * _currentConfiguration;
    FBSDisplayConfiguration * _currentReportedConfiguration;
    unsigned long long  _displayMutationCompletedCount;
    unsigned long long  _displayMutationEnqueuedCount;
    NSObject<OS_dispatch_queue> * _displayMutationQueue;
    SBApplication * _foregroundApp;
    FBScene * _foregroundAppScene;
    SBApplicationSceneHandle * _foregroundAppSceneHandle;
    BSAtomicSignal * _foregroundAppSceneTransactionInvalidator;
    bool  _hasEnqueuedPresentationUpdate;
    FBSDisplayIdentity * _identity;
    BSAtomicSignal * _idleOffTimerInvalidation;
    bool  _invalidated;
    FBSDisplayLayoutPublisher * _layoutPublisher;
    long long  _powerMode;
    FBScene * _presentationScene;
    BSAtomicSignal * _presentationSceneActivationInvalidator;
    SBApplicationSceneHandle * _presentationSceneHandle;
    bool  _presentationSceneHasActivated;
    SBSExternalDisplayLayoutElement * _presentedLayoutElement;
    <BSInvalidatable> * _presentedLayoutElementAssertion;
    SBApplication * _preventIdleSleepApp;
    bool  _preventIdleSleepPresenting;
    NSString * _preventIdleSleepReason;
    CADisplayMode * _requestedMode;
    NSString * _requestedOverscanAdjustment;
    _UIRootWindow * _rootWindow;
    FBSDisplayConfiguration * _rootWindowConfiguration;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_createUpdateTransaction;
- (void)_enqueuePresentationUpdate;
- (void)_ensureMode:(id)arg1 overscanCompensation:(long long)arg2;
- (void)_setPreventIdleSleepForApp:(id)arg1 presenting:(bool)arg2;
- (void)_updateHostingIfNecessary;
- (void)dealloc;
- (id)initWithLayoutPublisher:(id)arg1 displayConfiguration:(id)arg2;
- (void)invalidate;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)sceneHandle:(id)arg1 didUpdateClientSettingsWithDiff:(id)arg2 transitionContext:(id)arg3;
- (id)updateToConfiguration:(id)arg1 withForegroundApp:(id)arg2;

@end
