/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBFaceContactExpectationManager : NSObject {
    bool  _faceExpected;
    SBProximitySensorManager * _proximitySensorManager;
    SBSceneManager * _sceneManager;
}

- (void).cxx_destruct;
- (id)_frontmostScenesExpectingFaceContact;
- (id)_proximitySensorClientID;
- (id)description;
- (id)initWithSceneManager:(id)arg1;
- (id)initWithSceneManager:(id)arg1 proximitySensorManager:(id)arg2;
- (void)updateFaceContactExpectation;

@end
