/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBFluidScrunchGestureRecognizer : SBTouchTemplateGestureRecognizer <SBGestureRecognizerPanGestureProviding, SBGestureRecognizerTouchHistoryProviding> {
    double  _absoluteScale;
    struct CGPoint { 
        double x; 
        double y; 
    }  _absoluteTranslation;
    struct CGPoint { 
        double x; 
        double y; 
    }  _additionalTranslationDueToChangingAnchorPoints;
    struct CGPoint { 
        double x; 
        double y; 
    }  _initialCentroid;
    double  _lastPerimeter;
    SBFluidSwitcherViewController * _switcherViewController;
    SBTouchHistory * _touchHistory;
}

@property (nonatomic) double absoluteScale;
@property (nonatomic) struct CGPoint { double x1; double x2; } absoluteTranslation;
@property (nonatomic) struct CGPoint { double x1; double x2; } additionalTranslationDueToChangingAnchorPoints;
@property (nonatomic, readonly) struct CGPoint { double x1; double x2; } centroid;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) struct CGPoint { double x1; double x2; } initialCentroid;
@property (nonatomic) double lastPerimeter;
@property (readonly) Class superclass;
@property (nonatomic) SBFluidSwitcherViewController *switcherViewController;
@property (nonatomic, retain) SBTouchHistory *touchHistory;

- (void).cxx_destruct;
- (struct CGPoint { double x1; double x2; })_centroidInSwitcherViewForPolygon:(id)arg1;
- (void)_computeGestureMotionWithTouches:(id)arg1 polygon:(id)arg2;
- (double)_hysteresis;
- (void)_installTemplates;
- (bool)_isMatchedTemplateScrunchTemplate;
- (void)_setMatchedPolygon:(id)arg1;
- (bool)_shouldAddNewTouchesAfterGestureRecognition;
- (id)_switcherView;
- (double)absoluteScale;
- (struct CGPoint { double x1; double x2; })absoluteTranslation;
- (struct CGPoint { double x1; double x2; })additionalTranslationDueToChangingAnchorPoints;
- (double)animationDistance;
- (double)averageTouchPathAngleOverTimeDuration:(double)arg1;
- (struct CGPoint { double x1; double x2; })averageTouchVelocityOverTimeDuration:(double)arg1;
- (struct CGPoint { double x1; double x2; })centroid;
- (double)incrementalGestureMotionForCandidate:(id)arg1 withTransformAnalyzerInfo:(id)arg2;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;
- (struct CGPoint { double x1; double x2; })initialCentroid;
- (double)lastPerimeter;
- (struct CGPoint { double x1; double x2; })locationInView:(id)arg1;
- (id)logCategory;
- (double)peakSpeed;
- (void)reset;
- (void)setAbsoluteScale:(double)arg1;
- (void)setAbsoluteTranslation:(struct CGPoint { double x1; double x2; })arg1;
- (void)setAdditionalTranslationDueToChangingAnchorPoints:(struct CGPoint { double x1; double x2; })arg1;
- (void)setInitialCentroid:(struct CGPoint { double x1; double x2; })arg1;
- (void)setLastPerimeter:(double)arg1;
- (void)setState:(long long)arg1;
- (void)setSwitcherViewController:(id)arg1;
- (void)setTouchHistory:(id)arg1;
- (id)switcherViewController;
- (id)touchHistory;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (struct CGPoint { double x1; double x2; })translationInView:(id)arg1;
- (struct CGPoint { double x1; double x2; })translationWithoutConsideringScaleInView:(id)arg1;
- (struct CGPoint { double x1; double x2; })velocityInView:(id)arg1;

@end
