/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBFluidSwitcherItemContainerHeaderView : UIView <PTSettingsKeyObserver> {
    SBFluidSwitcherIconImageContainerView * _firstIconImageView;
    SBFluidSwitcherItemContainerHeaderItem * _firstItem;
    BSUIEmojiLabelView * _firstSubtitleLabelView;
    UILabel * _firstTitleLabel;
    NSArray * _headerItems;
    double  _iconSideLength;
    SBFluidSwitcherIconImageContainerView * _secondIconImageView;
    SBFluidSwitcherItemContainerHeaderItem * _secondItem;
    BSUIEmojiLabelView * _secondSubtitleLabelView;
    UILabel * _secondTitleLabel;
    double  _spacingBetweenBoundsCenterAndSecondIcon;
    double  _spacingBetweenIconAndLabel;
    double  _spacingBetweenLabelAndSecondIcon;
    double  _spacingBetweenLeadingEdgeAndIcon;
    double  _spacingBetweenSnapshotAndDescriptionLabelBaseline;
    double  _spacingBetweenSnapshotAndIcon;
    double  _spacingBetweenTitleAndSubtitleBaseline;
    double  _spacingBetweenTrailingEdgeAndLabels;
    MTVisualStyling * _subtitleVisualStyling;
    long long  _subtitleVisualStylingInterfaceStyle;
    double  _textAlpha;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) NSArray *headerItems;
@property (nonatomic, readonly) double preferredHeaderHeight;
@property (readonly) Class superclass;
@property (nonatomic) double textAlpha;

+ (double)distanceFromBoundingLeadingEdgeToIconTrailingEdge;

- (void).cxx_destruct;
- (void)_applyPrototypeSettings;
- (void)_contentSizeCategoryDidChangeNotification:(id)arg1;
- (id)_subtitleLabelFont;
- (id)_titleLabelFont;
- (void)_updateTitleAlpha;
- (void)_updateVisualStylingWithHeaderItems:(id)arg1;
- (void)dealloc;
- (id)headerItems;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (double)preferredHeaderHeight;
- (void)setHeaderItems:(id)arg1;
- (void)setHeaderItems:(id)arg1 animated:(bool)arg2;
- (void)setTextAlpha:(double)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (double)textAlpha;

@end
