/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBFloatingApplicationSceneLiveContentOverlayView : NSObject <SBDeviceApplicationSceneHandleObserver, SBFloatingApplicationLiveContentOverlayView, SBUISizeObservingViewDelegate> {
    bool  _asynchronousRenderingTemporarilyDisabled;
    SBMedusaDecoratedDeviceApplicationSceneViewController * _deviceApplicationSceneViewController;
    FBDisplayLayoutElement * _displayLayoutElement;
    SBFHomeGrabberSettings * _grabberSettings;
    bool  _liveContentRasterizationDisabled;
    long long  _rasterizationStyle;
    SBUISizeObservingView * _sizeObservingView;
    SBSceneViewStatusBarAssertion * _statusBarAssertion;
    bool  _wantsMinificationFilter;
    SBFloatingApplicationLiveContentWindow * _window;
    SBWindowSelfHostWrapper * _windowHostWrapper;
}

@property (nonatomic, readonly) bool asynchronousRenderingTemporarilyDisabled;
@property (nonatomic, readonly) UIView *contentOverlayView;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) SBMedusaDecoratedDeviceApplicationSceneViewController *deviceApplicationSceneViewController;
@property (nonatomic, readonly) FBDisplayLayoutElement *displayLayoutElement;
@property (nonatomic, readonly) SBFHomeGrabberSettings *grabberSettings;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool liveContentRasterizationDisabled;
@property (nonatomic, readonly) long long rasterizationStyle;
@property (nonatomic, readonly) SBUISizeObservingView *sizeObservingView;
@property (nonatomic, readonly) SBSceneViewStatusBarAssertion *statusBarAssertion;
@property (readonly) Class superclass;
@property (nonatomic, readonly) bool wantsMinificationFilter;
@property (nonatomic, readonly) SBFloatingApplicationLiveContentWindow *window;
@property (nonatomic, readonly) SBWindowSelfHostWrapper *windowHostWrapper;

- (void).cxx_destruct;
- (void)_updateContentWindowFrameFromView:(id)arg1;
- (void)_updateLiveContentRasterization;
- (bool)asynchronousRenderingTemporarilyDisabled;
- (void)configureWithWorkspaceEntity:(id)arg1 referenceFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2 interfaceOrientation:(long long)arg3;
- (id)contentOverlayView;
- (id)contentViewController;
- (void)dealloc;
- (id)deviceApplicationSceneViewController;
- (void)disableAsynchronousRenderingForNextCommit;
- (id)displayLayoutElement;
- (id)grabberSettings;
- (id)initWithWindow:(id)arg1;
- (void)invalidate;
- (bool)liveContentRasterizationDisabled;
- (void)noteKeyboardFocusDidChangeToSceneID:(id)arg1;
- (void)noteNeedsLayoutUpdateFor180DegreeRotation;
- (long long)rasterizationStyle;
- (void)sceneHandle:(id)arg1 didCreateScene:(id)arg2;
- (void)setHomeGrabberHidden:(bool)arg1 animated:(bool)arg2;
- (void)setLiveContentRasterizationDisabled:(bool)arg1;
- (void)setRasterizationStyle:(long long)arg1 withMinificationFilterEnabled:(bool)arg2;
- (void)setStatusBarHidden:(bool)arg1 nubViewHidden:(bool)arg2 animator:(id /* block */)arg3;
- (void)setUsesBrightSceneViewBackgroundMaterial:(bool)arg1;
- (id)sizeObservingView;
- (void)sizeObservingView:(id)arg1 didChangeSize:(struct CGSize { double x1; double x2; })arg2;
- (id)statusBarAssertion;
- (bool)wantsMinificationFilter;
- (id)window;
- (id)windowHostWrapper;

@end
