/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBFloatingSwitcherSettings : PTSettings {
    double  _cardSpacing;
    double  _darkeningFadeDistance;
    double  _darkeningMinimumDistanceThreshold;
    double  _dimmingAlpha;
    MTLumaDodgePillSettings * _homeAffordanceSettings;
    double  _leadingEdgeRubberbandingRange;
    double  _maximumDarkening;
    double  _opacityFadeDistance;
    double  _opacityMinimumDistanceThreshold;
    double  _overshootPullbackDelayOffscreen;
    double  _overshootPullbackDelayOnscreen;
    double  _perCardAdditionalScaleCoefficient;
    double  _scaleCurveExponent;
    bool  _showFloats;
    double  _switcherCardScale;
    double  _titleAndIconOpacityFadeDistance;
    double  _titleAndIconOpacityMinimumDistanceThreshold;
    double  _titleOpacityFadeDistance;
    double  _titleOpacityMinimumDistanceThreshold;
}

@property double cardSpacing;
@property double darkeningFadeDistance;
@property double darkeningMinimumDistanceThreshold;
@property double dimmingAlpha;
@property (retain) MTLumaDodgePillSettings *homeAffordanceSettings;
@property double leadingEdgeRubberbandingRange;
@property double maximumDarkening;
@property double opacityFadeDistance;
@property double opacityMinimumDistanceThreshold;
@property double overshootPullbackDelayOffscreen;
@property double overshootPullbackDelayOnscreen;
@property double perCardAdditionalScaleCoefficient;
@property double scaleCurveExponent;
@property bool showFloats;
@property double switcherCardScale;
@property double titleAndIconOpacityFadeDistance;
@property double titleAndIconOpacityMinimumDistanceThreshold;
@property double titleOpacityFadeDistance;
@property double titleOpacityMinimumDistanceThreshold;

+ (id)settingsControllerModule;

- (void).cxx_destruct;
- (id)archiveValueForKey:(id)arg1;
- (double)cardSpacing;
- (double)darkeningFadeDistance;
- (double)darkeningMinimumDistanceThreshold;
- (double)dimmingAlpha;
- (id)homeAffordanceSettings;
- (double)leadingEdgeRubberbandingRange;
- (double)maximumDarkening;
- (double)opacityFadeDistance;
- (double)opacityMinimumDistanceThreshold;
- (double)overshootPullbackDelayOffscreen;
- (double)overshootPullbackDelayOnscreen;
- (double)perCardAdditionalScaleCoefficient;
- (double)scaleCurveExponent;
- (void)setCardSpacing:(double)arg1;
- (void)setDarkeningFadeDistance:(double)arg1;
- (void)setDarkeningMinimumDistanceThreshold:(double)arg1;
- (void)setDefaultValues;
- (void)setDimmingAlpha:(double)arg1;
- (void)setHomeAffordanceSettings:(id)arg1;
- (void)setLeadingEdgeRubberbandingRange:(double)arg1;
- (void)setMaximumDarkening:(double)arg1;
- (void)setOpacityFadeDistance:(double)arg1;
- (void)setOpacityMinimumDistanceThreshold:(double)arg1;
- (void)setOvershootPullbackDelayOffscreen:(double)arg1;
- (void)setOvershootPullbackDelayOnscreen:(double)arg1;
- (void)setPerCardAdditionalScaleCoefficient:(double)arg1;
- (void)setScaleCurveExponent:(double)arg1;
- (void)setShowFloats:(bool)arg1;
- (void)setSwitcherCardScale:(double)arg1;
- (void)setTitleAndIconOpacityFadeDistance:(double)arg1;
- (void)setTitleAndIconOpacityMinimumDistanceThreshold:(double)arg1;
- (void)setTitleOpacityFadeDistance:(double)arg1;
- (void)setTitleOpacityMinimumDistanceThreshold:(double)arg1;
- (bool)showFloats;
- (double)switcherCardScale;
- (double)titleAndIconOpacityFadeDistance;
- (double)titleAndIconOpacityMinimumDistanceThreshold;
- (double)titleOpacityFadeDistance;
- (double)titleOpacityMinimumDistanceThreshold;

@end
