/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBFloatingDockWindowLevelAssertion : NSObject <BSDescriptionProviding> {
    double  _level;
    unsigned long long  _priority;
    NSString * _reason;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) double level;
@property (nonatomic, readonly) unsigned long long priority;
@property (nonatomic, readonly, copy) NSString *reason;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)dealloc;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)initWithPriority:(unsigned long long)arg1 level:(double)arg2 reason:(id)arg3;
- (void)invalidate;
- (double)level;
- (unsigned long long)priority;
- (id)reason;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end
