/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBFullScreenToHomeIconZoomSwitcherModifier : SBTransitionSwitcherModifier {
    SBAppLayout * _appLayout;
    SBCoplanarSwitcherModifier * _coplanarModifier;
    unsigned long long  _direction;
    double  _homeScreenIconCornerRadius;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _homeScreenIconFrame;
    bool  _homeScreenIconLocationIsFloatingDock;
    double  _homeScreenIconScale;
    bool  _itemContainerOverlapsDock;
    bool  _shouldAcceleratedHomeButtonPressBegin;
    bool  _wantsDockWindowLevelAssertion;
}

- (void).cxx_destruct;
- (bool)_isEffectivelyHome;
- (bool)_isIndexZoomAppLayout:(unsigned long long)arg1;
- (double)_normalizedHomeScreenIconZoomPercentBetweenTopAndBottom;
- (double)_normalizedHomeScreenTargetZoomPercentBetweenCenterAndEdge;
- (id)_settingsByInterpolatingBetween:(id)arg1 and:(id)arg2 progress:(double)arg3;
- (long long)backdropBlurType;
- (struct UIRectCornerRadii { double x1; double x2; double x3; double x4; })cardCornerRadiiForIndex:(unsigned long long)arg1;
- (void)didMoveToParentModifier:(id)arg1;
- (double)dockProgress;
- (double)dockWindowLevel;
- (unsigned long long)dockWindowLevelPriority;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForIndex:(unsigned long long)arg1;
- (id)handleTimerEvent:(id)arg1;
- (double)homeScreenAlpha;
- (id)initWithTransitionID:(id)arg1 appLayout:(id)arg2 direction:(unsigned long long)arg3;
- (bool)isHomeScreenContentRequired;
- (bool)isIndexVisible:(unsigned long long)arg1;
- (bool)isSwitcherWindowUserInteractionEnabled;
- (bool)isSwitcherWindowVisible;
- (bool)isWallpaperRequiredForSwitcher;
- (id)layoutSettings;
- (unsigned long long)numberOfAppLayoutsToCacheSnapshots;
- (double)opacityForIndex:(unsigned long long)arg1;
- (double)scaleForIndex:(unsigned long long)arg1;
- (bool)shouldAcceleratedHomeButtonPressBegin;
- (bool)shouldFireTransitionCompletionInDefaultRunLoopMode;
- (bool)shouldRasterizeLiveContentUntilDelay:(inout double*)arg1;
- (id)topMostAppLayouts;
- (id)transitionDidEnd;
- (id)transitionWillBegin;
- (long long)wallpaperStyle;
- (bool)wantsDockBehaviorAssertion;
- (bool)wantsDockWindowLevelAssertion;

@end
