/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBGridSwitcherModifier : SBSwitcherModifier <SBGridSwitcherScrollProviding> {
    SBAppLayout * _activeAppLayoutInSwitcher;
    _SBGridFloorSwitcherModifier * _floorModifier;
    SBGridLayoutSwitcherModifier * _gridLayoutModifier;
    unsigned long long  _ongoingAppLayoutRemovals;
    <SBFluidSwitcherScrollProvidingDelegate> * _scrollDelegate;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) double effectiveHorizontalSpacing;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) unsigned long long numberOfRows;
@property (nonatomic) <SBFluidSwitcherScrollProvidingDelegate> *scrollDelegate;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)didMoveToParentModifier:(id)arg1;
- (double)effectiveHorizontalSpacing;
- (id)forwardingTargetForSelector:(SEL)arg1;
- (id)gridLayoutModifier;
- (id)handleMainTransitionEvent:(id)arg1;
- (id)handleRemovalEvent:(id)arg1;
- (id)handleTapAppLayoutEvent:(id)arg1;
- (id)handleTapOutsideToDismissEvent:(id)arg1;
- (unsigned long long)numberOfRows;
- (bool)respondsToSelector:(SEL)arg1;
- (id)scrollDelegate;
- (void)setScrollDelegate:(id)arg1;

@end
