/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBHIDInterface : NSObject <SBProximitySensorControlling> {
    NSMutableArray * _assertions;
    <BSInvalidatable> * _dispatchingAssertion;
    unsigned long long  _lockState;
    SBHIDUILockAssertion * _pocketTouchesAssertion;
    bool  _proximityDetectionEnabled;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool pocketTouchesExpected;
@property (getter=isProximityDetectionEnabled, nonatomic) bool proximityDetectionEnabled;
@property (readonly) Class superclass;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_reevaluateLockStateForSource:(long long)arg1;
- (void)_setLockState:(unsigned long long)arg1 source:(long long)arg2;
- (id)_suspendProximity:(bool)arg1 suspendMultitouch:(bool)arg2 disableTapToWake:(bool)arg3 source:(long long)arg4 reason:(id)arg5;
- (id)addStartupHIDLockAssertion;
- (id)init;
- (bool)isProximityDetectionEnabled;
- (bool)pocketTouchesExpected;
- (void)reevaluateHIDLockAssertionsForSource:(long long)arg1;
- (void)removeHIDLockAssertion:(id)arg1 source:(long long)arg2;
- (void)resetProximityCalibration;
- (void)setPocketTouchesExpected:(bool)arg1;
- (void)setProximityDetectionEnabled:(bool)arg1;
- (id)suspendProximityDetectionAndMultitouchForSource:(long long)arg1 disableTapToWake:(bool)arg2 reason:(id)arg3;
- (id)suspendProximityDetectionForSource:(long long)arg1 reason:(id)arg2;

@end
