/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBHomeScreenViewController : UIViewController {
    SBUIController * _UIController;
    <BSInvalidatable> * _appIconForceTouchControllerOrientationUpdateDeferralAssertion;
    SBFloatingDockWindowLevelAssertion * _appIconForceTouchControllerWindowLevelAssertion;
    SBAppStatusBarSettingsAssertion * _childOrPresentedStatusBarAssertion;
    UIView * _contentView;
    bool  _disableAnimationForNextIconRotation;
    bool  _homeScreenAutorotatesEvenWhenIconIsDragging;
    SBFloatingDockBehaviorAssertion * _homeScreenFloatingDockAssertion;
    SBIconController * _iconController;
    bool  _iconControllerHidden;
    NSMutableSet * _iconRotationPreventionReasons;
    SBFloatingDockBehaviorAssertion * _widgetEditFloatingDockAssertion;
    <BSInvalidatable> * _widgetEditViewControllerOrientationUpdateDeferralAssertion;
}

@property (nonatomic, readonly) SBUIController *UIController;
@property (nonatomic) bool homeScreenAutorotatesEvenWhenIconIsDragging;
@property (nonatomic, readonly) SBIconController *iconController;
@property (getter=isIconControllerHidden, nonatomic) bool iconControllerHidden;
@property (nonatomic, readonly) SBHIconManager *iconManager;
@property (nonatomic, retain) _UILegibilitySettings *legibilitySettings;
@property (nonatomic, retain) SBFloatingDockBehaviorAssertion *widgetEditFloatingDockAssertion;
@property (nonatomic, retain) <BSInvalidatable> *widgetEditViewControllerOrientationUpdateDeferralAssertion;

- (void).cxx_destruct;
- (id)UIController;
- (void)_acquireForceTouchOrientationUpdateDeferralAssertion;
- (void)_acquireForceTouchWindowLevelAssertionForIconView:(id)arg1;
- (void)_animateTransitionToSize:(struct CGSize { double x1; double x2; })arg1 andInterfaceOrientation:(long long)arg2 withTransitionContext:(id)arg3;
- (void)_appIconForceTouchControllerDidDismissNotification:(id)arg1;
- (void)_appIconForceTouchControllerWillPresentNotification:(id)arg1;
- (id)_autorotationPreventionReasons;
- (void)_cleanupAfterTransitionToSize:(struct CGSize { double x1; double x2; })arg1 fromInterfaceOrientation:(long long)arg2 withTransitionContext:(id)arg3;
- (void)_prepareForTransitionToSize:(struct CGSize { double x1; double x2; })arg1 andInterfaceOrientation:(long long)arg2 withTransitionCoordinator:(id)arg3;
- (void)_relinquishForceTouchOrientationUpdateDeferralAssertion;
- (void)_relinquishForceTouchWindowLevelAssertion;
- (void)_widgetEditViewDidDisappear:(id)arg1;
- (void)_widgetEditViewDidDisappearImplementation;
- (void)_widgetEditViewWillAppear:(id)arg1;
- (void)disableAnimationForNextIconRotation;
- (bool)homeScreenAutorotatesEvenWhenIconIsDragging;
- (id)homeScreenView;
- (id)iconController;
- (id)iconManager;
- (id)initWithCoder:(id)arg1;
- (id)initWithIconController:(id)arg1 UIController:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (bool)isIconControllerHidden;
- (id)legibilitySettings;
- (void)loadView;
- (void)nudgeIconInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (void)setAllowIconRotation:(bool)arg1 forReason:(id)arg2;
- (void)setHomeScreenAutorotatesEvenWhenIconIsDragging:(bool)arg1;
- (void)setIconControllerHidden:(bool)arg1;
- (void)setLegibilitySettings:(id)arg1;
- (void)setNeedsStatusBarAppearanceUpdate;
- (void)setWidgetEditFloatingDockAssertion:(id)arg1;
- (void)setWidgetEditViewControllerOrientationUpdateDeferralAssertion:(id)arg1;
- (bool)shouldAutomaticallyForwardAppearanceMethods;
- (bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;
- (id)widgetEditFloatingDockAssertion;
- (id)widgetEditViewControllerOrientationUpdateDeferralAssertion;

@end
