/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBHomeScreenService : NSObject <BSServiceConnectionListenerDelegate, SBSHomeScreenServiceClientToServerInterface> {
    NSMutableSet * _activeConnections;
    FBServiceClientAuthenticator * _addWidgetToTodayViewAuthenticator;
    BSServiceConnectionListener * _connectionListener;
    SBIconController * _iconController;
    FBServiceClientAuthenticator * _iconFolderPathLookupAuthenticator;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lock;
    FBServiceClientAuthenticator * _lowDensityLayoutAuthenticator;
    FBServiceClientAuthenticator * _requestSuggestedAppAuthenticator;
    FBServiceClientAuthenticator * _resetHomeScreenLayoutAuthenticator;
}

@property (nonatomic, readonly) NSMutableSet *activeConnections;
@property (nonatomic, readonly) FBServiceClientAuthenticator *addWidgetToTodayViewAuthenticator;
@property (nonatomic, readonly) BSServiceConnectionListener *connectionListener;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) SBIconController *iconController;
@property (nonatomic, readonly) FBServiceClientAuthenticator *iconFolderPathLookupAuthenticator;
@property (nonatomic, copy) NSNumber *lowDensityIconLayoutEnabledValue;
@property (nonatomic, readonly) FBServiceClientAuthenticator *lowDensityLayoutAuthenticator;
@property (nonatomic, readonly) FBServiceClientAuthenticator *requestSuggestedAppAuthenticator;
@property (nonatomic, readonly) FBServiceClientAuthenticator *resetHomeScreenLayoutAuthenticator;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)activeConnections;
- (id)addWidgetToTodayViewAuthenticator;
- (void)addWidgetToTodayViewWithBundleIdentifier:(id)arg1;
- (id)connectionListener;
- (id)folderPathToIconWithBundleIdentifier:(id)arg1;
- (id)iconController;
- (id)iconFolderPathLookupAuthenticator;
- (id)initWithIconController:(id)arg1;
- (void)listener:(id)arg1 didReceiveConnection:(id)arg2 withContext:(id)arg3;
- (id)lowDensityIconLayoutEnabledValue;
- (id)lowDensityLayoutAuthenticator;
- (id)requestSuggestedAppAuthenticator;
- (oneway void)requestSuggestedApplicationWithBundleIdentifier:(id)arg1 assertionPort:(id)arg2 completion:(id /* block */)arg3;
- (id)resetHomeScreenLayoutAuthenticator;
- (oneway void)resetHomeScreenLayoutWithCompletion:(id /* block */)arg1;
- (void)setLowDensityIconLayoutEnabledValue:(id)arg1;

@end
