/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBHomeGestureSwitcherModifier : SBGestureSwitcherModifier <SBHomeGestureDockSwitcherModifierDelegate, SBHomeGestureFinalDestinationSwitcherModifierDelegate> {
    double  _absoluteScale;
    bool  _cancelledGestureForEmptySwitcher;
    double  _centerYOffsetWhenPresentedInSwitcher;
    struct CGPoint { 
        double x; 
        double y; 
    }  _centroid;
    bool  _continuingGesture;
    SBCoplanarSwitcherModifier * _coplanarLayoutModifier;
    bool  _didPlayFlyInHaptic;
    bool  _didWarmupFlyInHaptic;
    CADisplayLink * _displayLink;
    SBHomeGestureDockSwitcherModifier * _dockModifier;
    bool  _everTranslatedUpwards;
    SBHomeGestureFinalDestinationSwitcherModifier * _finalDestinationModifier;
    bool  _gestureHasBegun;
    bool  _gestureHasEnded;
    long long  _gestureHoldTimer;
    struct CGPoint { 
        double x; 
        double y; 
    }  _gestureLiftOffTranslation;
    struct CGPoint { 
        double x; 
        double y; 
    }  _gestureLiftOffVelocity;
    bool  _hasBecomeCoplanarSinceGestureFromSwitcherBegan;
    bool  _hasTriggeredCardFlyIn;
    bool  _inMultitasking;
    UIViewFloatAnimatableProperty * _inMultitaskingChangedProperty;
    struct CGPoint { 
        double x; 
        double y; 
    }  _initialCentroid;
    struct CGPoint { 
        double x; 
        double y; 
    }  _initialTouchLocation;
    double  _lastFrameOffsetX;
    bool  _lastGestureWasAnArcSwipe;
    struct CGPoint { 
        double x; 
        double y; 
    }  _lastTouchLocation;
    double  _lastTouchTimestamp;
    double  _lastTranslationXForRubberbanding;
    SBSwitcherModifier * _multitaskingModifier;
    double  _progressToInSwitcherCardScale;
    double  _progressToMaxTranslation;
    bool  _scrunchInitiated;
    SBAppLayout * _selectedAppLayout;
    bool  _shouldResignActive;
    double  _stackedProgress;
    long long  _startingEnvironmentMode;
    double  _toDimmingAlpha;
    double  _toHomeScreenAlpha;
    double  _toHomeScreenBlurProgress;
    struct CGPoint { 
        double x; 
        double y; 
    }  _touchOffset;
    struct CGPoint { 
        double x; 
        double y; 
    }  _translation;
    struct CGPoint { 
        double x; 
        double y; 
    }  _translationAdjustmentForStartingFromHomeScreen;
    struct CGPoint { 
        double x; 
        double y; 
    }  _translationAdjustmentForStartingFromSwitcher;
    struct CGPoint { 
        double x; 
        double y; 
    }  _translationWithoutScale;
    double  _translationXLostToRubberbanding;
    double  _translationYWhenTriggeredCardFlyIn;
    struct CGPoint { 
        double x; 
        double y; 
    }  _velocity;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_actionForActivatingFinalDestination:(long long)arg1;
- (id)_actionForActivatingReachabilityIfNeededWithFinalDestination:(long long)arg1;
- (id)_actionForSBEventGestureBeganWithTimeDelta:(double)arg1;
- (id)_actionForSBEventGestureEndWithEvent:(id)arg1 finalDestination:(long long)arg2;
- (id)_actionForStudyLogDidBeginGesture;
- (id)_actionForStudyLogDidEndGestureWithEvent:(id)arg1 finalDestination:(long long)arg2 destinationReason:(id)arg3;
- (id)_actionForUpdatingIconViewVisibility:(bool)arg1;
- (id)_actionForUpdatingLayoutForGestureBegan;
- (void)_applyPrototypeSettings;
- (void)_beginAnimatingMultitaskingPropertyWithMode:(long long)arg1 settings:(id)arg2;
- (double)_centerYOffsetDuringGesture;
- (double)_coplanarSpacing;
- (void)_displayLinkFired:(id)arg1;
- (double)_distanceYToInSwitcherCardScale;
- (double)_distanceYToMaxTranslation;
- (struct CGPoint { double x1; double x2; })_frameOffsetForTranslation:(struct CGPoint { double x1; double x2; })arg1;
- (double)_gestureProgressToMaxTranslationForTranslation:(double)arg1;
- (bool)_hasPausedEnoughForFlyIn;
- (bool)_hasTraveledSufficientDistanceForHomeOrAppSwitcher;
- (bool)_inMultitaskingForLocation:(struct CGPoint { double x1; double x2; })arg1 translation:(struct CGPoint { double x1; double x2; })arg2;
- (double)_inSwitcherCenterYOffsetWhenPresented;
- (bool)_isSelectedAppLayoutAtIndex:(unsigned long long)arg1;
- (bool)_isTranslationPastDistanceThresholdToUnconditionallyGoHome:(double)arg1;
- (bool)_preventPositioningCardsOffscreenForFlatBottomEdgeSwipe;
- (struct CGPoint { double x1; double x2; })_rubberbandedTranslationForAdjacentCards;
- (double)_scaleForAdjacentCards;
- (double)_scaleForOffscreenAdjacentCardsForFlyIn;
- (double)_scaleForTranslation:(struct CGPoint { double x1; double x2; })arg1;
- (unsigned long long)_selectedAppLayoutIndex;
- (bool)_shouldPositionAdjacentCardsOffscreenForFlyIn;
- (bool)_shouldResignActiveBasedOnCardScale;
- (double)_switcherCardScale;
- (struct CGPoint { double x1; double x2; })_unadjustedGestureTranslation;
- (id)_updateForGestureDidBeginWithEvent:(id)arg1;
- (id)_updateForGestureDidChangeWithEvent:(id)arg1;
- (id)_updateForGestureDidEndWithEvent:(id)arg1;
- (void)_updateFrameOffsetForXRubberbandingForTranslation:(struct CGPoint { double x1; double x2; })arg1;
- (void)_updateGestureTranslationVelocityAndProgressWithEvent:(id)arg1;
- (id)_updateInMultitaskingIfNeededWithLocation:(struct CGPoint { double x1; double x2; })arg1;
- (void)_updateShouldResignActiveWithEvent:(id)arg1;
- (void)_updateStackedProgress;
- (void)_updateTranslationAdjustmentForGestureFromHomeScreenIfNeededWithEvent:(id)arg1;
- (double)backdropBlurProgress;
- (long long)backdropBlurType;
- (struct UIRectCornerRadii { double x1; double x2; double x3; double x4; })cardCornerRadiiForIndex:(unsigned long long)arg1;
- (id)cornerRadiusSettingsForIndex:(unsigned long long)arg1;
- (long long)currentFinalDestination;
- (double)darkeningAlphaForIndex:(unsigned long long)arg1;
- (void)dealloc;
- (id)debugDescription;
- (void)didMoveToParentModifier:(id)arg1;
- (double)dimmingAlpha;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForIndex:(unsigned long long)arg1;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })fullSizeSnapshotsRange;
- (id)handleGestureEvent:(id)arg1;
- (id)handleHomeGestureSettingsChangedEvent:(id)arg1;
- (id)handleMainTransitionEvent:(id)arg1;
- (id)handleSwitcherSettingsChangedEvent:(id)arg1;
- (double)homeScreenAlpha;
- (double)homeScreenScale;
- (id)initWithGestureID:(id)arg1 selectedAppLayout:(id)arg2 startingEnvironmentMode:(long long)arg3 centerYOffsetWhenPresentedInSwitcher:(double)arg4 multitaskingModifier:(id)arg5 continuingGesture:(bool)arg6 lastGestureWasAnArcSwipe:(bool)arg7;
- (bool)isContainerStatusBarVisible;
- (bool)isContentStatusBarVisibleForIndex:(unsigned long long)arg1;
- (bool)isHomeScreenContentRequired;
- (bool)isIndexVisible:(unsigned long long)arg1;
- (bool)isShowingOrAnimatingCardsForFlyIn;
- (bool)isSwitcherWindowUserInteractionEnabled;
- (bool)isSwitcherWindowVisible;
- (bool)isWallpaperRequiredForSwitcher;
- (long long)keyboardSuppressionMode;
- (id)layoutSettingsForIndex:(unsigned long long)arg1;
- (struct CGPoint { double x1; double x2; })liftOffTranslationForGestureEnd;
- (struct CGPoint { double x1; double x2; })liftOffVelocityForGestureEnd;
- (double)lighteningAlphaForIndex:(unsigned long long)arg1;
- (long long)liveContentRasterizationStyle;
- (unsigned long long)numberOfAppLayoutsToCacheSnapshots;
- (double)opacityForIndex:(unsigned long long)arg1;
- (double)scaleForIndex:(unsigned long long)arg1;
- (long long)sceneDeactivationReason;
- (double)shadowOpacityForIndex:(unsigned long long)arg1;
- (double)titleAndIconOpacityForIndex:(unsigned long long)arg1;
- (double)titleOpacityForIndex:(unsigned long long)arg1;
- (double)unconditionalDistanceThresholdForHome;
- (double)wallpaperOverlayAlphaForIndex:(unsigned long long)arg1;
- (double)wallpaperScale;
- (long long)wallpaperStyle;
- (bool)wantsMinificationFilter;
- (bool)wantsResignActiveAssertion;

@end
