/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBHomeGestureRootSwitcherModifier : SBGestureRootSwitcherModifier {
    double  _centerYOffsetWhenPresentedInMultitasking;
    <SBFluidSwitcherModifierProviding> * _modifierProvider;
}

- (void).cxx_destruct;
- (id)gestureChildModifierForGestureEvent:(id)arg1 activeTransitionModifier:(id)arg2;
- (long long)gestureType;
- (id)initWithStartingEnvironmentMode:(long long)arg1 centerYOffsetWhenPresentedInMultitasking:(double)arg2 modifierProvider:(id)arg3;
- (id)transitionChildModifierForMainTransitionEvent:(id)arg1 activeGestureModifier:(id)arg2;
- (bool)wantsAsynchronousSurfaceRetentionAssertion;

@end
