/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBHomeScreenPreviewView : UIView <SBIconViewProviding> {
    UIView * _floatingDock;
    SBFloatingDockViewController * _floatingDockViewController;
    UIView * _folderContent;
    _SBHomeScreenFolderDelegate * _folderDelegate;
    SBIconController * _iconController;
    SBRootFolderController * _rootFolderController;
    UIView * _statusBar;
    SBWallpaperController * _wallpaperController;
}

@property (nonatomic, readonly) SBFloatingDockViewController *floatingDockViewController;
@property (nonatomic, readonly) SBIconController *iconController;
@property (nonatomic, readonly) SBWallpaperController *wallpaperController;

- (void).cxx_destruct;
- (void)configureIconView:(id)arg1 forIcon:(id)arg2;
- (id)dequeueReusableIconViewOfClass:(Class)arg1;
- (id)floatingDockViewController;
- (id)iconController;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 iconController:(id)arg2 wallpaperController:(id)arg3 options:(unsigned long long)arg4 wallpaperImage:(id)arg5;
- (bool)isIconViewRecycled:(id)arg1;
- (void)layoutSubviews;
- (void)recycleIconView:(id)arg1;
- (id)wallpaperController;

@end
