/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBHomeGestureParticipant : NSObject <BSDescriptionProviding> {
    SBHomeGestureArbiter * _arbiter;
    <SBHomeGestureParticipantDelegate> * _delegate;
    long long  _identifier;
    bool  _ownsHomeGesture;
    NSIndexSet * _trumpsAdditionalIdentifiers;
}

@property (nonatomic) SBHomeGestureArbiter *arbiter;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBHomeGestureParticipantDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long identifier;
@property (nonatomic) bool ownsHomeGesture;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSIndexSet *trumpsAdditionalIdentifiers;

- (void).cxx_destruct;
- (id)arbiter;
- (void)dealloc;
- (id)delegate;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (long long)identifier;
- (id)initWithIdentifier:(long long)arg1;
- (void)invalidate;
- (bool)ownsHomeGesture;
- (void)setArbiter:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setIdentifier:(long long)arg1;
- (void)setOwnsHomeGesture:(bool)arg1;
- (void)setTrumpsAdditionalIdentifiers:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)trumpsAdditionalIdentifiers;

@end
