/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBHomeScreenSwitcherModifier : SBSwitcherModifier {
    SBCoplanarSwitcherModifier * _coplanarModifier;
    _SBHomeScreenFloorSwitcherModifier * _homeScreenFloorModifier;
}

- (void).cxx_destruct;
- (id)init;

@end
