/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBHomeScreenNagAlert : SBDismissOnlyAlertItem

- (bool)dismissOnLock;
- (bool)shouldShowInLockScreen;

@end
