/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBHUDViewController : SBFTouchPassThroughViewController <SBHUDViewControlling, UIViewControllerTransitioningDelegate> {
    UIImageView * _backdropMaskImageView;
    _UIBackdropView * _backdropView;
    UIView * _blockView;
    UIView * _hudView;
    UIImage * _image;
    double  _progress;
    bool  _showsProgress;
    NSString * _subtitle;
    NSString * _title;
    double  _visibilityProgress;
}

@property (nonatomic, readonly) UIImageView *backdropMaskImageView;
@property (nonatomic, readonly) _UIBackdropView *backdropView;
@property (nonatomic, readonly) UIView *blockView;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) UIView *hudView;
@property (nonatomic, retain) UIImage *image;
@property (nonatomic) double progress;
@property (nonatomic) bool showsProgress;
@property (nonatomic, copy) NSString *subtitle;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSString *title;
@property (nonatomic) double visibilityProgress;

+ (double)progressIndicatorStep;

- (void).cxx_destruct;
- (id)_blockColorForValue:(float)arg1;
- (void)_rotateToInterfaceOrientation:(long long)arg1;
- (void)_updateBackdropMask;
- (void)_updateBlockView;
- (id)backdropMaskImageView;
- (id)backdropView;
- (id)blockView;
- (bool)definesAnimatedDismissal;
- (void)dismissAnimatedWithCompletion:(id /* block */)arg1;
- (bool)displaysLabel;
- (id)hudView;
- (id)image;
- (double)progress;
- (void)setImage:(id)arg1;
- (void)setProgress:(double)arg1;
- (void)setShowsProgress:(bool)arg1;
- (void)setSubtitle:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)setVisibilityProgress:(double)arg1;
- (bool)showsProgress;
- (id)subtitle;
- (id)title;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;
- (double)visibilityProgress;

@end
