/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBIconDeleteMetric : SBAnalyticsStateMachineEventHandler {
    NSString * _location;
    unsigned long long  _presentedOptions;
    PETDistributionEventTracker * _tracker;
}

- (void).cxx_destruct;
- (id)_propertyValuesForTracker;
- (id)init;

@end
