/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBIconLaunchContext : NSObject {
    NSSet * _actions;
    SBActivationSettings * _activationSettings;
}

@property (nonatomic, copy) NSSet *actions;
@property (nonatomic, retain) SBActivationSettings *activationSettings;

- (void).cxx_destruct;
- (id)actions;
- (id)activationSettings;
- (void)setActions:(id)arg1;
- (void)setActivationSettings:(id)arg1;

@end
