/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBIgnoredForAutorotationSecureWindow : SBSecureWindow

- (bool)_shouldControlAutorotation;

@end
