/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBInlineAppExposeLayoutElementViewController : SBLayoutElementViewController <SBLayoutStateTransitionObserver, SBMainDisplaySceneLayoutElementViewControlling> {
    SBInlineAppExposeContainerViewController * _inlineContainerViewController;
    NSMutableSet * _maskDisplayCornersReasons;
}

@property (nonatomic, retain) BSCornerRadiusConfiguration *cornerRadiusConfiguration;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (bool)SB_conformsToMainDisplaySceneLayoutElementViewControlling;
- (id)_newDisplayLayoutElementForEntity:(id)arg1;
- (id)animationControllerForTransitionRequest:(id)arg1;
- (void)configureWithWorkspaceEntity:(id)arg1 forLayoutElement:(id)arg2 layoutState:(id)arg3 referenceFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg4;
- (id)cornerRadiusConfiguration;
- (void)invalidate;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidBeginWithTransitionContext:(id)arg2;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidEndWithTransitionContext:(id)arg2;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionWillEndWithTransitionContext:(id)arg2;
- (void)prepareForReuse;
- (id)relinquishInlineContainerViewController;
- (void)setCornerRadiusConfiguration:(id)arg1;
- (void)setMaskDisplayCorners:(bool)arg1 forReason:(id)arg2;
- (void)setShadowOffset:(double)arg1;
- (void)setShadowOpacity:(double)arg1;
- (void)viewDidLayoutSubviews;

@end
