/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBInlineAppExposeContainerViewController : UIViewController <SBAppPlatterDragSourceViewProviding, SBLayoutStateTransitionObserver, SBSwitcherContentViewControllerDataSource, SBSwitcherContentViewControllerDelegate> {
    NSArray * _appLayouts;
    SBAsymmetricalCornerRadiusWrapperView * _asymmetricalCornerRadiusWrapperView;
    SBHomeScreenBackdropViewBase * _backdropView;
    NSString * _bundleIdentifier;
    bool  _clipsToBounds;
    long long  _contentInterfaceOrientation;
    struct CGSize { 
        double width; 
        double height; 
    }  _contentReferenceSize;
    SBFluidSwitcherViewController * _contentViewController;
    BSCornerRadiusConfiguration * _cornerRadiusConfiguration;
    <SBInlineAppExposeContainerViewControllerDelegate> * _delegate;
    SBDeviceApplicationSceneViewController * _deviceApplicationSceneViewController;
    bool  _didPerformInitialSetup;
    UIView * _dimmingView;
    bool  _dragging;
    bool  _isRotating;
    long long  _layoutRole;
    SBInlineAppExposeLiveContentOverlayCoordinator * _liveContentCoordinator;
    unsigned long long  _maskedCorners;
    bool  _overlay;
    SBInlineAppExposeRootSwitcherModifier * _rootModifier;
    bool  _transitioningFromOverlay;
    SBWallpaperEffectView * _wallpaperEffectView;
}

@property (nonatomic) bool clipsToBounds;
@property (nonatomic, retain) BSCornerRadiusConfiguration *cornerRadiusConfiguration;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBInlineAppExposeContainerViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) SBDeviceApplicationSceneViewController *deviceApplicationSceneViewController;
@property (getter=isDragging, nonatomic) bool dragging;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long layoutRole;
@property (nonatomic) unsigned long long maskedCorners;
@property (getter=isOverlay, nonatomic) bool overlay;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_addAppLayoutToFront:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })_frameForInlineAppExposeItemAspectFill:(bool)arg1 referenceSize:(struct CGSize { double x1; double x2; })arg2 interfaceOrientation:(long long)arg3 scale:(inout double*)arg4;
- (id)_inlineAppLayoutForDisplayItem:(id)arg1;
- (id)_inlineDisplayItemInLayoutState:(id)arg1;
- (void)_insertAppLayout:(id)arg1 atIndex:(unsigned long long)arg2 animated:(bool)arg3 modelMutation:(id /* block */)arg4;
- (id)_liveSceneIDsExcludingCurrentRole:(bool)arg1 matchingBundleIdentifier:(id)arg2 forTransitionContext:(id)arg3;
- (id)_newInlineDisplayItemFromSceneHandle:(id)arg1;
- (id)_unfilteredAppLayoutsForBundleID:(id)arg1;
- (void)_updateContentViewControllerFrame;
- (id)animationControllerForTransitionRequest:(id)arg1;
- (id)appLayoutsForSwitcherContentController:(id)arg1;
- (long long)backdropInterfaceStyleForContentController:(id)arg1;
- (bool)clipsToBounds;
- (id)containerViewForBlurContentView;
- (struct UIRectCornerRadii { double x1; double x2; double x3; double x4; })cornerRadii;
- (id)cornerRadiusConfiguration;
- (void)dealloc;
- (id)delegate;
- (id)deviceApplicationSceneViewController;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForInlineAppExposeItemAspectFill:(bool)arg1;
- (id)initWithBundleID:(id)arg1 layoutRole:(long long)arg2 overlay:(bool)arg3;
- (id)initialCornerRadiusConfiguration;
- (id)initialDiffuseShadowFilters;
- (struct SBDragPreviewShadowParameters { double x1; double x2; struct CGSize { double x_3_1_1; double x_3_1_2; } x3; })initialDiffuseShadowParameters;
- (id)initialRimShadowFilters;
- (struct SBDragPreviewShadowParameters { double x1; double x2; struct CGSize { double x_3_1_1; double x_3_1_2; } x3; })initialRimShadowParameters;
- (bool)isDragging;
- (bool)isOverlay;
- (long long)layoutRole;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidBeginWithTransitionContext:(id)arg2;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionDidEndWithTransitionContext:(id)arg2;
- (void)layoutStateTransitionCoordinator:(id)arg1 transitionWillEndWithTransitionContext:(id)arg2;
- (void)loadView;
- (unsigned long long)maskedCorners;
- (long long)sbActiveInterfaceOrientation;
- (void)setClipsToBounds:(bool)arg1;
- (void)setContentReferenceSize:(struct CGSize { double x1; double x2; })arg1 withInterfaceOrientation:(long long)arg2;
- (void)setCornerRadiusConfiguration:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDeviceApplicationSceneViewController:(id)arg1;
- (void)setDragging:(bool)arg1;
- (void)setLayoutRole:(long long)arg1;
- (void)setMaskedCorners:(unsigned long long)arg1;
- (void)setOverlay:(bool)arg1;
- (long long)shadowStyleForSwitcherContentController:(id)arg1;
- (id)sourceView;
- (void)switcherContentController:(id)arg1 deletedAppLayout:(id)arg2 forReason:(long long)arg3;
- (void)switcherContentController:(id)arg1 handlePlusButtonActionForBundleIdentifier:(id)arg2;
- (void)switcherContentController:(id)arg1 performTransitionWithRequest:(id)arg2 gestureInitiated:(bool)arg3;
- (void)switcherContentController:(id)arg1 setBackdropBlurProgress:(double)arg2 withAnimationMode:(long long)arg3 completion:(id /* block */)arg4;
- (void)switcherContentController:(id)arg1 setBackdropBlurType:(long long)arg2;
- (void)switcherContentController:(id)arg1 setContainerStatusBarHidden:(bool)arg2 animationDuration:(double)arg3;
- (void)switcherContentController:(id)arg1 setContentOrientation:(long long)arg2;
- (void)switcherContentController:(id)arg1 setDimmingAlpha:(double)arg2 withAnimationMode:(long long)arg3 completion:(id /* block */)arg4;
- (bool)switcherContentController:(id)arg1 shouldMorphToPiPForTransitionContext:(id)arg2;
- (id)switcherContentController:(id)arg1 transitionEventForContext:(id)arg2 identifier:(id)arg3 phase:(unsigned long long)arg4 animated:(bool)arg5;
- (id)switcherContentController:(id)arg1 transitionEventForLayoutState:(id)arg2 identifier:(id)arg3 phase:(unsigned long long)arg4 animated:(bool)arg5;
- (bool)switcherContentControllerReloadsSnapshotsForActiveInterfaceOrientationChange:(id)arg1;
- (long long)switcherInterfaceOrientationForContentController:(id)arg1;
- (void)viewWillLayoutSubviews;

@end
