/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBInlineEmptyGridSwitcherModifier : SBSwitcherModifier

- (long long)backdropBlurType;
- (double)dimmingAlpha;
- (id)init;
- (bool)isIndexVisible:(unsigned long long)arg1;
- (unsigned long long)numberOfAppLayoutsToCacheSnapshots;

@end
