/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBInlineGridToFullScreenSwitcherModifier : SBTransitionSwitcherModifier {
    bool  _dimInactiveCards;
    SBAppLayout * _fullScreenAppLayout;
    struct UIRectCornerRadii { 
        double topLeft; 
        double bottomLeft; 
        double bottomRight; 
        double topRight; 
    }  _fullScreenCornerRadii;
    SBSwitcherModifier * _multitaskingModifier;
}

@property (nonatomic, readonly) SBAppLayout *fullScreenAppLayout;
@property (nonatomic, readonly) SBSwitcherModifier *multitaskingModifier;

- (void).cxx_destruct;
- (bool)_isIndexFullScreenAppLayout:(unsigned long long)arg1;
- (double)_unselectedCardScale;
- (id)appExposeAccessoryButtonsBundleIdentifier;
- (long long)appExposeAccessoryButtonsOverrideUserInterfaceStyle;
- (id)appLayoutToScrollToBeforeTransitioning;
- (double)backdropBlurProgress;
- (long long)backdropBlurType;
- (struct UIRectCornerRadii { double x1; double x2; double x3; double x4; })cardCornerRadiiForIndex:(unsigned long long)arg1;
- (double)darkeningAlphaForIndex:(unsigned long long)arg1;
- (double)dimmingAlpha;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frameForIndex:(unsigned long long)arg1;
- (id)fullScreenAppLayout;
- (id)initWithTransitionID:(id)arg1 fullScreenAppLayout:(id)arg2 multitaskingModifier:(id)arg3 fullscreenCornerRadii:(struct UIRectCornerRadii { double x1; double x2; double x3; double x4; })arg4 dimInactiveCards:(bool)arg5;
- (bool)isContainerStatusBarVisible;
- (bool)isContentStatusBarVisibleForIndex:(unsigned long long)arg1;
- (bool)isIndexVisible:(unsigned long long)arg1;
- (id)layoutSettings;
- (long long)liveContentRasterizationStyle;
- (id)multitaskingModifier;
- (double)opacityForIndex:(unsigned long long)arg1;
- (double)plusButtonAlpha;
- (long long)plusButtonStyle;
- (double)reopenClosedWindowsButtonAlpha;
- (double)reopenClosedWindowsButtonScale;
- (double)scaleForIndex:(unsigned long long)arg1;
- (double)titleOpacityForIndex:(unsigned long long)arg1;
- (id)topMostAppLayouts;
- (id)transitionWillBegin;

@end
