/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBInternalClientSettingObserverContext : NSObject {
    UIApplicationSceneClientSettings * _oldClientSettings;
    FBScene * _scene;
    SBDeviceApplicationSceneHandle * _sceneHandle;
    FBSSceneTransitionContext * _transition;
    UIApplicationSceneClientSettings * _updatedClientSettings;
}

@property (nonatomic, retain) UIApplicationSceneClientSettings *oldClientSettings;
@property (nonatomic, retain) FBScene *scene;
@property (nonatomic, retain) SBDeviceApplicationSceneHandle *sceneHandle;
@property (nonatomic, retain) FBSSceneTransitionContext *transition;
@property (nonatomic, retain) UIApplicationSceneClientSettings *updatedClientSettings;

- (void).cxx_destruct;
- (id)oldClientSettings;
- (id)scene;
- (id)sceneHandle;
- (void)setOldClientSettings:(id)arg1;
- (void)setScene:(id)arg1;
- (void)setSceneHandle:(id)arg1;
- (void)setTransition:(id)arg1;
- (void)setUpdatedClientSettings:(id)arg1;
- (id)transition;
- (id)updatedClientSettings;

@end
