/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBInlineAppExposeLiveContentOverlayView : NSObject <SBSwitcherLiveContentOverlay> {
    SBDeviceApplicationSceneViewController * _deviceApplicationSceneViewController;
    SBSceneViewStatusBarAssertion * _statusBarAssertion;
    bool  _transitioning;
}

@property (nonatomic, readonly) UIView *contentOverlayView;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) SBDeviceApplicationSceneViewController *deviceApplicationSceneViewController;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) SBSceneViewStatusBarAssertion *statusBarAssertion;
@property (readonly) Class superclass;
@property (getter=isTransitioning, nonatomic) bool transitioning;

- (void).cxx_destruct;
- (id)contentOverlayView;
- (void)dealloc;
- (id)deviceApplicationSceneViewController;
- (void)disableAsynchronousRenderingForNextCommit;
- (id)initWithDeviceApplicationSceneViewController:(id)arg1;
- (bool)isTransitioning;
- (void)noteKeyboardFocusDidChangeToSceneID:(id)arg1;
- (long long)rasterizationStyle;
- (void)setHomeGrabberHidden:(bool)arg1 animated:(bool)arg2;
- (void)setRasterizationStyle:(long long)arg1 withMinificationFilterEnabled:(bool)arg2;
- (void)setStatusBarHidden:(bool)arg1 nubViewHidden:(bool)arg2 animator:(id /* block */)arg3;
- (void)setTransitioning:(bool)arg1;
- (void)setUsesBrightSceneViewBackgroundMaterial:(bool)arg1;
- (id)statusBarAssertion;

@end
