/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBIPhotoLaunchDeniedAlertItem : SBAlertItem {
    bool  _offersMigration;
}

@property (nonatomic) bool offersMigration;

- (void)configure:(bool)arg1 requirePasscodeForActions:(bool)arg2;
- (bool)dismissOnLock;
- (bool)ignoreIfAlreadyDisplaying;
- (bool)offersMigration;
- (void)setOffersMigration:(bool)arg1;

@end
