/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBLayoutStateTransitionCoordinator : NSObject <SBWorkspaceApplicationSceneTransitionContextDelegate> {
    NSPointerArray * _observerPointerArray;
    <SBLayoutStateTransitionSceneEntityFrameProvider> * _sceneEntityFrameProvider;
    SBSceneManager * _sceneManager;
    SBLayoutStateTransitionContext * _transitionContext;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) <SBLayoutStateTransitionSceneEntityFrameProvider> *sceneEntityFrameProvider;
@property (nonatomic, readonly) SBSceneManager *sceneManager;
@property (readonly) Class superclass;
@property (nonatomic, readonly) SBLayoutStateTransitionContext *transitionContext;
@property (getter=isTransitioning, nonatomic, readonly) bool transitioning;

- (void).cxx_destruct;
- (void)addObserver:(id)arg1;
- (void)beginTransitionForWorkspaceTransaction:(id)arg1;
- (void)endTransitionWithError:(id)arg1;
- (id)init;
- (id)initWithSceneManager:(id)arg1;
- (bool)isTransitioning;
- (id)layoutStateForApplicationTransitionContext:(id)arg1;
- (id)previousLayoutStateForApplicationTransitionContext:(id)arg1;
- (void)removeObserver:(id)arg1;
- (id)sceneEntityFrameProvider;
- (id)sceneManager;
- (void)setSceneEntityFrameProvider:(id)arg1;
- (id)transitionContext;
- (void)willEndTransition;

@end
