/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBLayoutStateManager : NSObject

+ (id)_initialLayoutState;
+ (Class)_layoutStateClass;

- (id)_layoutStateForApplicationTransitionContext:(id)arg1;
- (id)layoutStateForApplicationTransitionContext:(id)arg1;

@end
