/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBLockToAppStatusBarAnimator : NSObject {
    SBDisableAppStatusBarAlphaChangesAssertion * _disableStatusBarAlphaChangeAssertion;
}

- (void).cxx_destruct;
- (void)animateStatusBarFromLockToHome;

@end
