/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBLockScreenViewControllerBase : UIViewController <SBApplicationHosting, SBAutoUnlockRule, SBBiometricUnlockBehavior, SBButtonEventsHandler, SBCoverSheetSlidingViewControllerContentViewController, SBIdleTimerProviding, SBLockScreenBacklightControlling, SBLockScreenBehaviorSuppressing, SBLockScreenBlockedStateObserving, SBLockScreenButtonObserving, SBLockScreenCallHandling, SBLockScreenContentStateProviding, SBLockScreenCustomActionStoring, SBLockScreenIdleTimerControlling, SBLockScreenLockingAndUnlocking, SBLockScreenMediaControlsPresenting, SBLockScreenPasscodeViewPresenting, SBLockScreenPluginPresenting, SBLockScreenProximityBehaviorProviding, SBLockScreenStatusBarTransitioning> {
    bool  _authenticated;
    double  _backlightLevel;
    <SBBiometricUnlockBehaviorDelegate> * _biometricUnlockBehaviorDelegate;
    SBFLockScreenActionContext * _customLockScreenActionContext;
    bool  _expectsFaceContact;
    <SBIdleTimerCoordinating> * _idleTimerCoordinator;
    SBFLockScreenWakeAnimator * _lockScreenWakeAnimator;
    UIVisualEffectView * _wakeEffectView;
}

@property (getter=isAuthenticated, nonatomic) bool authenticated;
@property (nonatomic) double backlightLevel;
@property (nonatomic) <SBBiometricUnlockBehaviorDelegate> *biometricUnlockBehaviorDelegate;
@property (nonatomic, readonly) bool contentOccludesBackground;
@property (getter=_customLockScreenActionContext, nonatomic, retain) SBFLockScreenActionContext *customLockScreenActionContext;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool expectsFaceContact;
@property (readonly) unsigned long long hash;
@property (nonatomic) <SBIdleTimerCoordinating> *idleTimerCoordinator;
@property (nonatomic, readonly) SBFLockScreenWakeAnimator *lockScreenWakeAnimator;
@property (nonatomic, readonly) bool shouldShowLockStatusBarTime;
@property (getter=isShowingMediaControls, nonatomic) bool showingMediaControls;
@property (readonly) Class superclass;
@property (nonatomic) UIVisualEffectView *wakeEffectView;

- (void).cxx_destruct;
- (id)_customLockScreenActionContext;
- (double)backlightLevel;
- (id)biometricUnlockBehaviorDelegate;
- (bool)canBeDeactivatedForUIUnlockFromSource:(int)arg1;
- (bool)canHostAnApp;
- (bool)contentOccludesBackground;
- (id)coordinatorRequestedIdleTimerBehavior:(id)arg1;
- (id)createHomeButtonShowPasscodeRecognizerForHomeButtonPress;
- (id)createHomeButtonSuppressAfterUnlockRecognizerForUnlockSource:(int)arg1;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)disableLockScreenPluginWithContext:(id)arg1;
- (void)emergencyDialerExitedWithError:(id)arg1;
- (void)enableLockScreenPluginWithContext:(id)arg1;
- (void)exitEmergencyDialerAnimated:(bool)arg1;
- (bool)expectsFaceContact;
- (void)finishUIUnlockFromSource:(int)arg1;
- (void)handleBiometricEvent:(unsigned long long)arg1;
- (bool)handleHeadsetButtonPress:(bool)arg1;
- (bool)handleHomeButtonDoublePress;
- (bool)handleHomeButtonLongPress;
- (bool)handleHomeButtonPress;
- (bool)handleLockButtonPress;
- (bool)handleVolumeDownButtonPress;
- (bool)handleVolumeUpButtonPress;
- (id)hostedAppSceneHandle;
- (id)hostedAppSceneHandles;
- (void)hostedAppWillRotateToInterfaceOrientation:(long long)arg1;
- (id)idleTimerCoordinator;
- (bool)isAuthenticated;
- (bool)isHostingAnApp;
- (bool)isInScreenOffMode;
- (bool)isMainPageVisible;
- (bool)isMakingEmergencyCall;
- (bool)isPasscodeLockVisible;
- (bool)isShowingMediaControls;
- (bool)isUnlockDisabled;
- (void)jiggleLockIcon;
- (void)launchEmergencyDialer;
- (void)launchEmergencyDialerAnimated:(bool)arg1;
- (void)launchInCallAlert;
- (id)lockScreenWakeAnimator;
- (void)noteDeviceBlockedStatusUpdated;
- (void)noteMenuButtonDown;
- (void)noteMenuButtonUp;
- (void)noteResetRestoreStateUpdated;
- (void)prepareForUILock;
- (void)prepareForUIUnlock;
- (void)setAuthenticated:(bool)arg1;
- (void)setBacklightLevel:(double)arg1;
- (void)setBiometricUnlockBehaviorDelegate:(id)arg1;
- (void)setCustomLockScreenActionContext:(id)arg1;
- (void)setIdleTimerCoordinator:(id)arg1;
- (void)setInScreenOffMode:(bool)arg1;
- (void)setInScreenOffMode:(bool)arg1 forAutoUnlock:(bool)arg2 fromUnlockSource:(int)arg3;
- (void)setPasscodeLockVisible:(bool)arg1 animated:(bool)arg2;
- (void)setPasscodeLockVisible:(bool)arg1 animated:(bool)arg2 completion:(id /* block */)arg3;
- (void)setShowingMediaControls:(bool)arg1;
- (void)setWakeEffectView:(id)arg1;
- (bool)shouldAutoUnlockForSource:(int)arg1;
- (bool)shouldDisableALS;
- (bool)shouldShowLockStatusBarTime;
- (bool)shouldUnlockUIOnKeyDownEvent;
- (void)startLockScreenFadeInAnimationForSource:(int)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (bool)suppressesBanners;
- (bool)suppressesControlCenter;
- (bool)suppressesScreenshots;
- (void)updateStatusBarForLockScreenComeback;
- (void)updateStatusBarForLockScreenTeardown;
- (void)viewDidLoad;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;
- (id)wakeEffectView;
- (bool)willUIUnlockFromSource:(int)arg1;

@end
