/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBLockOverlayView : SBUILockOverlayView

- (id)_legibilitySettingsForStyle:(unsigned long long)arg1;

@end
