/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBLockScreenBounceAnimator : NSObject <PTSettingsKeyObserver, UIDynamicAnimatorDelegate, UIGestureRecognizerDelegate> {
    UIDynamicAnimator * _animator;
    SBBounceBehavior * _behavior;
    bool  _bounceEnabled;
    id /* block */  _canceledBlock;
    id /* block */  _completedBlock;
    NSSet * _gestures;
    bool  _isAnimating;
    SBBouncingItem * _item;
    id /* block */  _prepareBlock;
    <SBPresentingDelegate> * _presentingDelegate;
    CSBounceSettings * _settings;
    id /* block */  _shouldBeginBlock;
    SBBouncingSystem * _system;
    NSMutableSet * _tapExcludedViews;
    NSMutableSet * _tapExcludedZones;
    UIGestureRecognizer * _tapRecognizer;
    id /* block */  _translateBlock;
    UIView * _view;
}

@property (copy) id /* block */ canceledBlock;
@property (copy) id /* block */ completedBlock;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSSet *gestures;
@property (readonly) unsigned long long hash;
@property (copy) id /* block */ prepareBlock;
@property (nonatomic) <SBPresentingDelegate> *presentingDelegate;
@property (nonatomic, retain) CSBounceSettings *settings;
@property (copy) id /* block */ shouldBeginBlock;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSSet *tapExcludedViews;
@property (copy) id /* block */ translateBlock;

- (void).cxx_destruct;
- (void)_addTapRecognizer;
- (void)_beginAnimating:(id)arg1;
- (void)_createAnimator;
- (void)_handleTapGesture:(id)arg1;
- (void)_removeAnimator;
- (void)_removeTapRecognizer;
- (void)_resetAnimator;
- (void)_updateSettings;
- (void)addTapExcludedView:(id)arg1;
- (void)addTapExcludedZone:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)allowTapForGestureRecognizer:(id)arg1;
- (void)cancelAnimation;
- (void)cancelGestureRecognizer:(id)arg1;
- (id /* block */)canceledBlock;
- (id /* block */)completedBlock;
- (void)dealloc;
- (void)dynamicAnimatorDidPause:(id)arg1;
- (bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)gestures;
- (id)initWithView:(id)arg1;
- (bool)isAnimating;
- (id /* block */)prepareBlock;
- (id)presentingDelegate;
- (void)reenableGestureRecognizer:(id)arg1;
- (void)removeTapExcludedView:(id)arg1;
- (void)setBounceEnabled:(bool)arg1;
- (void)setCanceledBlock:(id /* block */)arg1;
- (void)setCompletedBlock:(id /* block */)arg1;
- (void)setPrepareBlock:(id /* block */)arg1;
- (void)setPresentingDelegate:(id)arg1;
- (void)setSettings:(id)arg1;
- (void)setShouldBeginBlock:(id /* block */)arg1;
- (void)setTranslateBlock:(id /* block */)arg1;
- (id)settings;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (id /* block */)shouldBeginBlock;
- (id)tapExcludedViews;
- (id /* block */)translateBlock;

@end
