/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBLogWindowController : UIViewController {
    UITextView * _logTextView;
    SBMainScreenActiveInterfaceOrientationWindow * _logWindow;
}

@property (nonatomic, retain) UITextView *logTextView;
@property (nonatomic, retain) SBMainScreenActiveInterfaceOrientationWindow *logWindow;

+ (id)sharedInstance;
+ (id)sharedInstanceIfAvailable;

- (void).cxx_destruct;
- (void)hide;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)logTextView;
- (id)logWindow;
- (void)setLogTextView:(id)arg1;
- (void)setLogWindow:(id)arg1;
- (void)show;

@end
