/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBLockScreenService : NSObject <BSServiceConnectionListenerDelegate, SBSLockScreenServiceServerInterface> {
    <SBFAuthenticationAssertionProviding> * _authenticationAssertionProvider;
    NSMutableSet * _connections;
    NSMutableSet * _connectionsPreventingPasscodeLock;
    NSMutableSet * _connectionsPreventingSpuriousScreenUndim;
    BSServiceConnectionListener * _listener;
    SBLockScreenManager * _lockScreenManager;
    SBMainWorkspace * _mainWorkspace;
    SBFAuthenticationAssertion * _preventPasscodeLockAssertion;
    SBSpuriousScreenUndimmingAssertion * _preventSpuriousScreenUndimAssertion;
    SBRemoteTransientOverlaySessionManager * _remoteTransientOverlaySessionManager;
    FBServiceClientAuthenticator * _requestDeviceUnlockAuthenticator;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)initWithLockScreenManager:(id)arg1 workspace:(id)arg2 authenticationAssertionProvider:(id)arg3 remoteTransientOverlaySessionManager:(id)arg4;
- (oneway void)launchEmergencyDialerWithCompletion:(id /* block */)arg1;
- (void)listener:(id)arg1 didReceiveConnection:(id)arg2 withContext:(id)arg3;
- (void)requestPasscodeUnlockUIForClient:(id)arg1 options:(id)arg2 description:(id)arg3 withCompletion:(id /* block */)arg4;
- (oneway void)requestPasscodeUnlockUIWithOptions:(id)arg1 withCompletion:(id /* block */)arg2;
- (oneway void)setPreventPasscodeLock:(id)arg1;
- (oneway void)setPreventSpuriousScreenUndim:(id)arg1;

@end
