/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBMainScreenActiveInterfaceOrientationWindow : SBWindow <BSDescriptionProviding, SBUIActiveOrientationObserver> {
    NSString * _debugName;
    NSCountedSet * _orientationUpdateDisableReasons;
    bool  _passesTouchesThrough;
    UIViewController * _sb_rootViewController;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic, readonly, copy) NSString *debugName;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool passesTouchesThrough;
@property (setter=sb_setRootViewController:, nonatomic, retain) UIViewController *sb_rootViewController;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_updateInterfaceOrientationToCurrentActiveInterfaceOrientationWithDuration:(double)arg1;
- (void)activeInterfaceOrientationDidChangeToOrientation:(long long)arg1 willAnimateWithDuration:(double)arg2 fromOrientation:(long long)arg3;
- (void)activeInterfaceOrientationWillChangeToOrientation:(long long)arg1;
- (id)debugName;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (void)disableInterfaceOrientationChangesForReason:(id)arg1;
- (void)enableInterfaceOrientationChangesForReason:(id)arg1;
- (id)hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (id)initWithDebugName:(id)arg1;
- (bool)isActive;
- (bool)isDisablingInterfaceOrientationChanges;
- (bool)passesTouchesThrough;
- (id)sb_rootViewController;
- (void)sb_setRootViewController:(id)arg1;
- (void)setHidden:(bool)arg1;
- (void)setPassesTouchesThrough:(bool)arg1;
- (void)setRootViewController:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end
