/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBMainDisplayLayoutState : SBLayoutState {
    NSString * _bundleIDShowingAppExpose;
    long long  _floatingConfiguration;
    bool  _floatingSwitcherVisible;
    NSSet * _inlineAppExposeOverlayElements;
    long long  _spaceConfiguration;
    long long  _unlockedEnvironmentMode;
}

@property (nonatomic, readonly) NSString *bundleIDShowingAppExpose;
@property (nonatomic, readonly) long long floatingConfiguration;
@property (getter=isFloatingSwitcherVisible, nonatomic, readonly) bool floatingSwitcherVisible;
@property (nonatomic, readonly) NSSet *inlineAppExposeOverlayElements;
@property (nonatomic, readonly) long long spaceConfiguration;
@property (nonatomic, readonly) long long unlockedEnvironmentMode;

+ (long long)_defaultInterfaceOrientation;

- (void).cxx_destruct;
- (id)_initWithLayoutElements:(id)arg1 interfaceOrientation:(long long)arg2 elementInterfaceOrientation:(long long)arg3;
- (id)_initWithLayoutElements:(id)arg1 interfaceOrientation:(long long)arg2 elementInterfaceOrientation:(long long)arg3 spaceConfiguration:(long long)arg4 floatingConfiguration:(long long)arg5 unlockedEnvironmentMode:(long long)arg6 floatingSwitcherVisible:(bool)arg7 bundleIDShowingAppExpose:(id)arg8 inlineAppExposeOverlayElements:(id)arg9;
- (id)_transitionContextForDismissingLeftApplication;
- (id)_transitionContextForDismissingRightApplication;
- (id)_transitionContextForResizingToSpaceConfiguration:(long long)arg1;
- (id)bundleIDShowingAppExpose;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (long long)floatingConfiguration;
- (id)floatingItem;
- (unsigned long long)hash;
- (id)inlineAppExposeOverlayElementWithRole:(long long)arg1;
- (id)inlineAppExposeOverlayElements;
- (long long)interfaceOrientation;
- (bool)isEqual:(id)arg1;
- (bool)isFloatingSwitcherVisible;
- (long long)spaceConfiguration;
- (long long)unlockedEnvironmentMode;
- (id)visibleFloatingItem;

@end
