/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBMainDisplayLayoutStateManager : SBLayoutStateManager

@property (nonatomic, readonly) SBMainDisplaySceneManager *_mainDisplaySceneManager;
@property (nonatomic, readonly) SBMainWorkspace *_mainWorkspace;
@property (nonatomic, readonly) SBPlatformController *_platformController;
@property (nonatomic, readonly) SBRecentAppLayouts *_recentAppLayouts;

+ (Class)_layoutStateClass;

- (id)_applicationSceneEntityFromApplicationBundleIdentifier:(id)arg1 uniqueIdentifier:(id)arg2;
- (bool)_doesSceneIDSpecifyPrimaryScene:(id)arg1 forApplicationIdentifier:(id)arg2;
- (bool)_hasAppLayoutBeenUserKilledWithinThresholdToCreateNewScene:(id)arg1;
- (id)_layoutStateForApplicationTransitionContext:(id)arg1;
- (id)_mainDisplaySceneManager;
- (id)_mainWorkspace;
- (id)_mostRecentAppLayoutMatchingWorkspaceUniqueIdentifiers:(id)arg1;
- (id)_platformController;
- (id)_recentAppLayouts;
- (id)_sceneIDIfAppLayoutContainsPrimarySceneIDForBundleIdentifier:(id)arg1 bundleIdentifier:(id)arg2;
- (id)defaultSceneIdentifierForBundleIdentifier:(id)arg1 targetContentIdentifier:(id)arg2 allowCanMatches:(bool)arg3 preferNewScene:(bool)arg4 visibleSceneIdentifiers:(id)arg5 excludingSceneIdentifiers:(id)arg6;
- (id)layoutStateForApplicationTransitionContext:(id)arg1;
- (id)primarySceneIdentifierForBundleIdentifier:(id)arg1;

@end
