/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBModalUIFluidDismissGestureManager : NSObject <BSTransactionObserver, PTSettingsKeyObserver, SBModalUIFluidDismissPanGestureRecognizerDelegate> {
    SBAssistantController * _assistantController;
    SBModalUIFluidDismissPanGestureRecognizer * _bottomEdgeRecognizer;
    SBModalUIFluidDismissGestureWorkspaceTransaction * _currentTransaction;
    SBHomeGestureSettings * _homeGestureSettings;
    SBTransientOverlayPresentationManager * _transientOverlayPresentationManager;
}

@property (nonatomic, readonly) SBAssistantController *assistantController;
@property (nonatomic, retain) SBModalUIFluidDismissPanGestureRecognizer *bottomEdgeRecognizer;
@property (nonatomic, retain) SBModalUIFluidDismissGestureWorkspaceTransaction *currentTransaction;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) SBHomeGestureSettings *homeGestureSettings;
@property (readonly) Class superclass;
@property (nonatomic, readonly) SBTransientOverlayPresentationManager *transientOverlayPresentationManager;

- (void).cxx_destruct;
- (void)_addOrRemoveGestureForCurrentSettings;
- (long long)_dismissalTypeForCurrentContext;
- (void)_handleBottomEdgeGesture:(id)arg1;
- (void)_handleBottomEdgeGestureBegan:(id)arg1;
- (void)_handleBottomEdgeGestureChanged:(id)arg1;
- (void)_handleBottomEdgeGestureEnded:(id)arg1;
- (id)assistantController;
- (id)bottomEdgeRecognizer;
- (id)currentTransaction;
- (bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (bool)gestureRecognizerShouldBegin:(id)arg1;
- (id)homeGestureSettings;
- (id)initWithTransientOverlayPresentationManager:(id)arg1 assistantController:(id)arg2;
- (void)setBottomEdgeRecognizer:(id)arg1;
- (void)setCurrentTransaction:(id)arg1;
- (void)setHomeGestureSettings:(id)arg1;
- (void)settings:(id)arg1 changedValueForKey:(id)arg2;
- (long long)touchInterfaceOrientationForRecognizer:(id)arg1;
- (void)transactionDidComplete:(id)arg1;
- (id)transientOverlayPresentationManager;
- (id)viewForSystemGestureRecognizer:(id)arg1;

@end
