/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBMutableSwitcherTransitionRequest : SBSwitcherTransitionRequest

@property (nonatomic) long long animationDisabled;
@property (nonatomic, retain) SBAppLayout *appLayout;
@property (nonatomic) long long appLayoutEnvironment;
@property (nonatomic) long long dismissInlineAppExpose;
@property (nonatomic) long long floatingConfiguration;
@property (nonatomic) long long floatingSwitcherVisible;
@property (nonatomic) long long preferredInterfaceOrientation;
@property (nonatomic) long long source;
@property (nonatomic) long long unlockedEnvironmentMode;

@end
