/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBNotificationBannerWindow : SBSecureMainScreenActiveInterfaceOrientationWindow {
    bool  _isShowingLongLook;
}

@property (nonatomic) bool isShowingLongLook;

- (bool)_canBecomeKeyWindow;
- (bool)becomeFirstResponder;
- (bool)canResignFirstResponder;
- (id)init;
- (bool)isShowingLongLook;
- (bool)resignFirstResponder;
- (void)setIsShowingLongLook:(bool)arg1;

@end
