/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBNotificationLongLookBannerDestination : NSObject <NCNotificationViewControllerDelegate, NCNotificationViewControllerObserving, SBHomeGestureParticipantDelegate> {
    <BSInvalidatable> * _idleTimerDisableAssertion;
    <NCNotificationAlertDestination><NCNotificationViewControllerDelegatePrivate><NCNotificationViewControllerObserving> * _parentDestination;
    NCNotificationViewController * _presentedBanner;
    <BSInvalidatable> * _starModeDisableAssertion;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) <BSInvalidatable> *idleTimerDisableAssertion;
@property (nonatomic) <NCNotificationAlertDestination><NCNotificationViewControllerDelegatePrivate><NCNotificationViewControllerObserving> *parentDestination;
@property (getter=isPreemptingSTAR, nonatomic, readonly) bool preemptingSTAR;
@property (nonatomic, retain) NCNotificationViewController *presentedBanner;
@property (getter=isPresentingBanner, nonatomic, readonly) bool presentingBanner;
@property (getter=isPreventingAutomaticLock, nonatomic, readonly) bool preventingAutomaticLock;
@property (nonatomic, retain) <BSInvalidatable> *starModeDisableAssertion;
@property (readonly) Class superclass;

+ (bool)shouldNotificationRequestPresentAsLongLook:(id)arg1;

- (void).cxx_destruct;
- (id)_delegate;
- (void)_dismissBannerCompleted;
- (bool)_presentedBannerMatchesNotificationRequest:(id)arg1;
- (void)_setReadyForNotificationRequests;
- (bool)canModifyNotificationRequest:(id)arg1;
- (bool)canReceiveNotificationRequest:(id)arg1;
- (bool)canWithdrawNotificationRequest:(id)arg1;
- (void)dismissPresentedBannerAnimated:(bool)arg1 completion:(id /* block */)arg2;
- (id)hideHomeAffordanceAnimationSettingsForNotificationViewController:(id)arg1;
- (void)homeGestureParticipantOwningHomeGestureDidChange:(id)arg1;
- (id)idleTimerDisableAssertion;
- (id)initWithParentDestination:(id)arg1;
- (bool)isPreemptingSTAR;
- (bool)isPresentingBanner;
- (bool)isPreventingAutomaticLock;
- (void)notificationViewController:(id)arg1 executeAction:(id)arg2 withParameters:(id)arg3 completion:(id /* block */)arg4;
- (id)notificationViewController:(id)arg1 keyboardAssertionForGestureWindow:(id)arg2;
- (void)notificationViewController:(id)arg1 requestPermissionToExecuteAction:(id)arg2 withParameters:(id)arg3 completion:(id /* block */)arg4;
- (void)notificationViewControllerDidDismiss:(id)arg1;
- (void)notificationViewControllerDidPresent:(id)arg1;
- (void)notificationViewControllerWillDismiss:(id)arg1;
- (void)notificationViewControllerWillPresent:(id)arg1;
- (id)parentDestination;
- (void)postNotificationRequest:(id)arg1 withPresentingViewController:(id)arg2 animated:(bool)arg3 completion:(id /* block */)arg4;
- (id)presentedBanner;
- (void)setIdleTimerDisableAssertion:(id)arg1;
- (void)setParentDestination:(id)arg1;
- (void)setPresentedBanner:(id)arg1;
- (void)setStarModeDisableAssertion:(id)arg1;
- (id)settleHomeAffordanceAnimationBehaviorDescriptionForNotificationViewController:(id)arg1;
- (bool)shouldReceiveNotificationRequest:(id)arg1;
- (id)starModeDisableAssertion;
- (id)unhideHomeAffordanceAnimationSettingsForNotificationViewController:(id)arg1;

@end
