/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBPBAppLayout : PBCodable <NSCopying> {
    int  _environment;
    struct { 
        unsigned int secondaryDisplayItemRole : 1; 
    }  _has;
    bool  _hidden;
    int  _layoutConfiguration;
    SBPBDisplayItem * _primaryDisplayItem;
    SBPBDisplayItem * _secondaryDisplayItem;
    int  _secondaryDisplayItemRole;
}

@property (nonatomic) int environment;
@property (nonatomic, readonly) bool hasPrimaryDisplayItem;
@property (nonatomic, readonly) bool hasSecondaryDisplayItem;
@property (nonatomic) bool hasSecondaryDisplayItemRole;
@property (nonatomic) bool hidden;
@property (nonatomic) int layoutConfiguration;
@property (nonatomic, retain) SBPBDisplayItem *primaryDisplayItem;
@property (nonatomic, retain) SBPBDisplayItem *secondaryDisplayItem;
@property (nonatomic) int secondaryDisplayItemRole;

- (void).cxx_destruct;
- (int)StringAsEnvironment:(id)arg1;
- (int)StringAsLayoutConfiguration:(id)arg1;
- (int)StringAsSecondaryDisplayItemRole:(id)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (int)environment;
- (id)environmentAsString:(int)arg1;
- (bool)hasPrimaryDisplayItem;
- (bool)hasSecondaryDisplayItem;
- (bool)hasSecondaryDisplayItemRole;
- (unsigned long long)hash;
- (bool)hidden;
- (bool)isEqual:(id)arg1;
- (int)layoutConfiguration;
- (id)layoutConfigurationAsString:(int)arg1;
- (void)mergeFrom:(id)arg1;
- (id)primaryDisplayItem;
- (bool)readFrom:(id)arg1;
- (id)secondaryDisplayItem;
- (int)secondaryDisplayItemRole;
- (id)secondaryDisplayItemRoleAsString:(int)arg1;
- (void)setEnvironment:(int)arg1;
- (void)setHasSecondaryDisplayItemRole:(bool)arg1;
- (void)setHidden:(bool)arg1;
- (void)setLayoutConfiguration:(int)arg1;
- (void)setPrimaryDisplayItem:(id)arg1;
- (void)setSecondaryDisplayItem:(id)arg1;
- (void)setSecondaryDisplayItemRole:(int)arg1;
- (void)writeTo:(id)arg1;

@end
