/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBPIPController : NSObject <PGPictureInPictureControllerDelegate, SBAlertItemsControllerObserver, SBAssistantObserver> {
    bool  _expectKeyboardVisible;
    PGPictureInPictureController * _pictureInPictureController;
    NSMutableDictionary * _pictureInPictureInsetsForSource;
    NSMutableSet * _pictureInPictureMorphAnimatorControllers;
    SBPIPWindow * _pictureInPictureWindow;
    NSMutableSet * _pictureInPictureWindowHiddenReasons;
    NSMutableOrderedSet * _pictureInPictureWindowLevelOverrides;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _pictureInPictureWindowMargin;
    <BSInvalidatable> * _stateCaptureInvalidatable;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (bool)isAutoPictureInPictureSupported;
+ (bool)isPictureInPictureSupported;
+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_adjustPIPInsetsForKeyboardFrameChangeNotification:(id)arg1;
- (void)_appSwitcherWillQuitApp:(id)arg1;
- (void)_bulletinWillDismiss:(id)arg1;
- (void)_bulletinWillPresent:(id)arg1;
- (void)_createWindowAndRootViewControllerIfNeeded;
- (void)_destroyWindowAndRootViewControllerIfPossible;
- (void)_floatingDockHeightWillChange:(id)arg1;
- (void)_keyboardWillChangeFrame:(id)arg1;
- (void)_keyboardWillRotate:(id)arg1;
- (void)_keyboardWillShowOrHide:(id)arg1;
- (void)_lockStateDidChange:(id)arg1;
- (void)_managePictureInPictureWindowLevel;
- (void)_managePictureInPictureWindowVisibilityAnimated:(bool)arg1;
- (id)_morphAnimatorControllerForProcessIdentifier:(int)arg1;
- (id)_pictureInPictureApplicationForProcessIdentifier:(int)arg1;
- (id)_pipWindow;
- (bool)_pointInside:(struct CGPoint { double x1; double x2; })arg1;
- (void)_setPictureInPictureWindowMargin:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1 animationDuration:(double)arg2 animationOptions:(unsigned long long)arg3;
- (void)_updateFloatingDockInsets;
- (void)_updateFloatingDockInsetsWithHeight:(double)arg1;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })_updatePictureInPictureOverlayInsetsWithDuration:(double)arg1 withCurrentLayoutState:(bool)arg2;
- (void)addPictureInPictureMorphAnimatorController:(id)arg1;
- (void)alertItemsController:(id)arg1 didActivateAlertItem:(id)arg2;
- (void)alertItemsController:(id)arg1 didDeactivateAlertItem:(id)arg2 forReason:(int)arg3;
- (void)alertItemsController:(id)arg1 willActivateAlertItem:(id)arg2;
- (void)applyPictureInPictureInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1 fromSource:(long long)arg2 duration:(double)arg3;
- (void)assistantDidDisappear:(id)arg1;
- (void)assistantWillAppear:(id)arg1;
- (void)cancelPictureInPictureForApplicationWithProcessIdentifierEnteringBackground:(int)arg1 scenePersistenceIdentifier:(id)arg2;
- (void)dealloc;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })defaultHomeScreenInitialPiPFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1 withPreferredContentSize:(struct CGSize { double x1; double x2; })arg2;
- (id)init;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })initialFrameForInteractivePictureInPictureAnimationEnteringBackgroundForApplicationWithProcessIdentifier:(int)arg1 scenePersistenceIdentifier:(id)arg2;
- (bool)isPictureInPictureWindowVisible;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)pictureInPictureController:(id)arg1 didCreatePictureInPictureViewController:(id)arg2;
- (void)pictureInPictureController:(id)arg1 didHidePictureInPictureViewController:(id)arg2;
- (bool)pictureInPictureController:(id)arg1 shouldDenyNewConnection:(id)arg2;
- (void)pictureInPictureController:(id)arg1 willDestroyPictureInPictureViewController:(id)arg2;
- (void)pictureInPictureController:(id)arg1 willHidePictureInPictureViewController:(id)arg2;
- (void)pictureInPictureInterruptionBegan;
- (void)pictureInPictureInterruptionEnded;
- (id)pictureInPictureMorphAnimatorControllerForProcessIdentifier:(int)arg1;
- (struct CGSize { double x1; double x2; })preferredContentSizeForInteractivePictureInPictureAnimationEnteringBackgroundForApplicationWithProcessIdentifier:(int)arg1 scenePersistenceIdentifier:(id)arg2;
- (void)removePictureInPictureMorphAnimatorController:(id)arg1;
- (void)removePictureInPictureWindowLevelOverrideForReason:(id)arg1;
- (void)setPictureInPictureWindowHidden:(bool)arg1 withReason:(id)arg2;
- (void)setPictureInPictureWindowLevelOverride:(unsigned long long)arg1 withReason:(id)arg2;
- (bool)shouldStartPictureInPictureForApplicationWithProcessIdentifierEnteringBackground:(int)arg1 scenePersistenceIdentifier:(id)arg2;
- (void)startPictureInPictureForApplicationWithProcessIdentifierEnteringBackground:(int)arg1 scenePersistenceIdentifier:(id)arg2 animated:(bool)arg3 completionHandler:(id /* block */)arg4;
- (void)updatePictureInPictureWindowLevel;

@end
