/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBPIPWindow : SBWindow

@property (nonatomic, readonly) NSArray *containerViewControllers;

- (id)_pipWindowRootVC;
- (void)addContainerViewController:(id)arg1;
- (id)containerViewControllers;
- (id)hitTest:(struct CGPoint { double x1; double x2; })arg1 withEvent:(id)arg2;
- (id)init;
- (long long)interfaceOrientationForContainerViewController:(id)arg1;
- (bool)isActive;
- (void)removeContainerViewController:(id)arg1;
- (void)setRootViewController:(id)arg1;

@end
