/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBProximityBacklightPolicyFactory : NSObject

+ (id)createNewProximityBacklightPolicyWithBacklightController:(id)arg1;

@end
