/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBProximitySensorManager : NSObject <SBUIActiveOrientationObserver> {
    int  _backboardNotificationToken;
    NSMutableSet * _clientsWantingDetectionEnabled;
    SBHardwareDefaults * _hardwareDefaults;
    <SBProximitySensorControlling> * _hidInterface;
    SpringBoard * _interfaceOrientationProvider;
    bool  _objectInProximity;
    NSHashTable * _observers;
    bool  _proximityDetectionEnabled;
    bool  _proximityDetectionPermitted;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (getter=_interfaceOrientationProvider, setter=_setInterfaceOrientationProvider:, nonatomic, retain) SpringBoard *interfaceOrientationProvider;
@property (getter=isObjectInProximity, setter=_setObjectInProximity:, nonatomic) bool objectInProximity;
@property (getter=isProximityDetectionEnabled, setter=_setProximityDetectionEnabled:, nonatomic) bool proximityDetectionEnabled;
@property (getter=isProximityDetectionPermitted, setter=_setProximityDetectionPermitted:, nonatomic) bool proximityDetectionPermitted;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (bool)_clientsWantDetectionEnabled;
- (void)_destroy;
- (void)_disableProx;
- (void)_enableProx;
- (id)_interfaceOrientationProvider;
- (void)_proximityDidChange:(id)arg1;
- (void)_reloadDefaults;
- (void)_setInterfaceOrientationProvider:(id)arg1;
- (void)_setObjectInProximity:(bool)arg1;
- (void)_setProximityDetectionEnabled:(bool)arg1;
- (void)_setProximityDetectionPermitted:(bool)arg1;
- (void)_updateProxState;
- (void)activeInterfaceOrientationDidChangeToOrientation:(long long)arg1 willAnimateWithDuration:(double)arg2 fromOrientation:(long long)arg3;
- (void)activeInterfaceOrientationWillChangeToOrientation:(long long)arg1;
- (void)addObserver:(id)arg1;
- (void)client:(id)arg1 wantsProximityDetectionEnabled:(bool)arg2;
- (id)description;
- (id)init;
- (id)initWithHIDInterface:(id)arg1 hardwareDefaults:(id)arg2 interfaceOrientationProvider:(id)arg3;
- (bool)isObjectInProximity;
- (bool)isProximityDetectionEnabled;
- (bool)isProximityDetectionPermitted;
- (void)removeObserver:(id)arg1;
- (void)resetProximityCalibration;

@end
