/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBProximitySettings : SBUISettings {
    double  _initialBacklightDebounceDuration;
    double  _subsequentBacklightDebounceDuration;
}

@property (nonatomic) double initialBacklightDebounceDuration;
@property (nonatomic) double subsequentBacklightDebounceDuration;

+ (id)settingsControllerModule;

- (double)initialBacklightDebounceDuration;
- (void)setDefaultValues;
- (void)setInitialBacklightDebounceDuration:(double)arg1;
- (void)setSubsequentBacklightDebounceDuration:(double)arg1;
- (double)subsequentBacklightDebounceDuration;

@end
