/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBPressPrecedenceArbiter : NSObject {
    NSArray * _hardwareButtons;
    long long  _homeButtonType;
    bool  _isMusicPlayingSomewhere;
    unsigned long long  _volumeAndLockButtonPriority;
}

@property (nonatomic, retain) NSArray *hardwareButtons;

- (void).cxx_destruct;
- (void)_applyButtonPriority:(unsigned long long)arg1;
- (unsigned long long)_currentButtonPriority;
- (void)_initializeButtonPriorities;
- (bool)_shouldArbitrateLockAndVolumeHardwareButtonPriorities;
- (void)_updateButtonPrioritiesForClientIsPlayingNotification:(id)arg1;
- (void)_updateButtonPrioritiesForNotification:(id)arg1;
- (void)_updateButtonPriority;
- (id)hardwareButtons;
- (id)initWithHomeButtonType:(long long)arg1;
- (void)setHardwareButtons:(id)arg1;

@end
