/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBReverseCountedSemaphore : NSObject {
    NSObject<OS_dispatch_group> * _group;
}

- (void).cxx_destruct;
- (void)decrement;
- (void)increment;
- (id)init;
- (void)wait;

@end
