/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBReachabilityBackgroundViewController : UIViewController

- (bool)_canShowWhileLocked;
- (id)initWithWallpaperVariant:(long long)arg1;
- (bool)shouldAutorotate;
- (id)view;

@end
