/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBRemovalSwitcherModifierEvent : SBSwitcherModifierEvent {
    SBAppLayout * _appLayout;
    unsigned long long  _phase;
    long long  _reason;
}

@property (nonatomic, readonly) SBAppLayout *appLayout;
@property (nonatomic, readonly) unsigned long long phase;
@property (nonatomic, readonly) long long reason;

- (void).cxx_destruct;
- (id)appLayout;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)initWithAppLayout:(id)arg1 reason:(long long)arg2 phase:(unsigned long long)arg3;
- (unsigned long long)phase;
- (long long)reason;
- (long long)type;

@end
