/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBReduceMotionChangedSwitcherModifierEvent : SBSwitcherModifierEvent

- (long long)type;

@end
