/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBRingerVolumeSliderView : UIView {
    UIView * _backgroundView;
    UIView * _fillView;
    double  _value;
}

@property (nonatomic, retain) UIView *backgroundView;
@property (nonatomic, retain) UIView *fillView;
@property (nonatomic) double value;

- (void).cxx_destruct;
- (id)backgroundView;
- (id)fillView;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)layoutSubviews;
- (void)setBackgroundView:(id)arg1;
- (void)setFillView:(id)arg1;
- (void)setValue:(double)arg1;
- (double)value;

@end
