/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBRingerControl : NSObject <SBRingerHUDViewControllerDelegate> {
    SBHUDController * _HUDController;
    bool  _ringerMuted;
    SBSoundController * _soundController;
    float  _volume;
}

@property (nonatomic, readonly) SBHUDController *HUDController;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (getter=isRingerMuted, nonatomic) bool ringerMuted;
@property (nonatomic, readonly) SBSoundController *soundController;
@property (readonly) Class superclass;
@property (nonatomic) float volume;

- (void).cxx_destruct;
- (id)HUDController;
- (void)_softMuteChanged:(id)arg1;
- (void)activateRingerHUD:(int)arg1 withInitialVolume:(float)arg2 fromSource:(unsigned long long)arg3;
- (void)activateRingerHUDForVolumeChangeWithInitialVolume:(float)arg1;
- (void)activateRingerHUDFromMuteSwitch:(int)arg1;
- (void)buttonReleased;
- (id)existingRingerHUDViewController;
- (void)hideRingerHUDIfVisible;
- (id)initWithHUDController:(id)arg1 soundController:(id)arg2;
- (bool)isRingerMuted;
- (bool)lastSavedRingerMutedState;
- (void)nudgeUp:(bool)arg1;
- (void)ringerHUDViewControllerWantsToBeDismissed:(id)arg1;
- (void)setRingerMuted:(bool)arg1;
- (void)setVolume:(float)arg1;
- (void)setVolume:(float)arg1 forKeyPress:(bool)arg2;
- (id)soundController;
- (void)toggleRingerMute;
- (float)volume;

@end
