/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBRotationLockHUDController : NSObject

+ (void)activateWithLocked:(bool)arg1;

@end
