/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBRotationFloatingSwitcherModifier : SBTransitionSwitcherModifier

- (long long)keyboardSuppressionMode;
- (long long)layoutUpdateMode;
- (long long)liveContentRasterizationStyle;
- (bool)shouldPerformRotationAnimationForOrientationChange;
- (bool)wantsResignActiveAssertion;

@end
