/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSceneLayoutTransitionAnimationController : SBUIWorkspaceAnimationController {
    SBUIBlockAnimationController * _blockAnimation;
    SBSceneLayoutViewController * _layoutController;
}

- (void).cxx_destruct;
- (bool)_canBeInterrupted;
- (id)_getTransitionWindow;
- (unsigned long long)_serialOverlayPreDismissalOptions;
- (id)animationSettings;
- (id)containerView;
- (id)initWithTransitionContextProvider:(id)arg1 layoutController:(id)arg2 animationSettings:(id)arg3 animationBlock:(id /* block */)arg4;
- (id)initWithTransitionContextProvider:(id)arg1 layoutController:(id)arg2 animationSettings:(id)arg3 stepped:(bool)arg4 animationBlock:(id /* block */)arg5;
- (id)initWithWorkspaceTransitionRequest:(id)arg1;

@end
