/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSceneOrientationFollowingWindowRootViewController : UIViewController

- (bool)shouldAutomaticallyForwardAppearanceMethods;
- (void)viewWillLayoutSubviews;

@end
