/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSceneManagerCoordinator : NSObject <FBProcessManagerObserver, FBSDisplayObserving, FBSceneDelegate, FBSceneManagerDelegate_Private, FBSceneManagerObserver, FBWorkspaceDelegate, SBSceneManagerReferenceDelegate> {
    NSMutableDictionary * _displayIdentityToReferenceMap;
    UIApplicationSceneDeactivationManager * _sceneDeactivationManager;
    FBSceneManager * _sceneManager;
    NSMutableSet * _workspaceIdentifiersToIgnore;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) UIApplicationSceneDeactivationManager *sceneDeactivationManager;
@property (readonly) Class superclass;

+ (id)mainDisplaySceneManager;
+ (id)secureMainDisplaySceneManager;
+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)_referenceForDisplayIdentity:(id)arg1 creatingIfNecessary:(bool)arg2;
- (id)_sceneManagerForDisplayIdentity:(id)arg1 creatingIfNecessary:(bool)arg2;
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (void)displayMonitor:(id)arg1 didConnectIdentity:(id)arg2 withConfiguration:(id)arg3;
- (void)displayMonitor:(id)arg1 willDisconnectIdentity:(id)arg2;
- (void)enumerateSceneManagersWithBlock:(id /* block */)arg1;
- (id)init;
- (void)processManager:(id)arg1 didAddProcess:(id)arg2;
- (void)processManager:(id)arg1 didRemoveProcess:(id)arg2;
- (void)registerSceneWorkspaceIdentifierToIgnore:(id)arg1;
- (void)scene:(id)arg1 didApplyUpdateWithContext:(id)arg2;
- (void)scene:(id)arg1 didCompleteUpdateWithContext:(id)arg2 error:(id)arg3;
- (void)scene:(id)arg1 didPrepareUpdateWithContext:(id)arg2;
- (void)scene:(id)arg1 didReceiveActions:(id)arg2;
- (void)scene:(id)arg1 didUpdateClientSettingsWithDiff:(id)arg2 oldClientSettings:(id)arg3 transitionContext:(id)arg4;
- (id)sceneDeactivationManager;
- (id)sceneManager:(id)arg1 createDefaultTransitionContextForScene:(id)arg2;
- (void)sceneManager:(id)arg1 didCreateScene:(id)arg2;
- (void)sceneManager:(id)arg1 didDestroyScene:(id)arg2;
- (void)sceneManager:(id)arg1 interceptUpdateForScene:(id)arg2 withNewSettings:(id)arg3;
- (void)sceneManager:(id)arg1 scene:(id)arg2 didReceiveActions:(id)arg3;
- (void)sceneManager:(id)arg1 willDestroyScene:(id)arg2;
- (void)sceneManagerDidInvalidateForReference:(id)arg1;
- (id)sceneManagerForDisplayIdentity:(id)arg1;
- (void)workspace:(id)arg1 didReceiveSceneRequestWithOptions:(id)arg2 completion:(id /* block */)arg3;

@end
