/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSceneLayoutAnimationWrapperView : UIView <SBSceneLayoutReferenceOrientedView> {
    long long  _layoutOrientation;
    long long  _referenceOrientation;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSArray *elementWrapperViews;
@property (readonly) unsigned long long hash;
@property (nonatomic) long long layoutOrientation;
@property (nonatomic) long long referenceOrientation;
@property (readonly) Class superclass;

- (void)crossfadeWithCompletion:(id /* block */)arg1;
- (id)description;
- (id)elementWrapperViewForLayoutRole:(long long)arg1;
- (id)elementWrapperViews;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)invalidate;
- (long long)layoutOrientation;
- (long long)referenceOrientation;
- (void)setLayoutOrientation:(long long)arg1;
- (void)setReferenceOrientation:(long long)arg1;

@end
