/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBScrunchSystemGestureRecognizer : SBTouchTemplatePinchGestureRecognizer

+ (id)defaultTemplates;

- (double)animationDistance;
- (id)initWithTarget:(id)arg1 action:(SEL)arg2;
- (id)logCategory;

@end
