/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSecureAppManager : NSObject {
    NSHashTable * _observers;
    NSMutableArray * _remoteAlertActions;
    NSMutableDictionary * _secureAppActions;
}

@property (nonatomic, readonly) bool hasSecureApp;
@property (nonatomic, readonly) bool hasWakeDestinaton;
@property (nonatomic, retain) NSHashTable *observers;
@property (nonatomic, retain) NSMutableArray *remoteAlertActions;
@property (nonatomic, retain) NSMutableDictionary *secureAppActions;
@property (nonatomic, readonly) SBWakeDestination *wakeDestinaton;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_addRemoteAlertLockScreenContentAction:(id)arg1;
- (void)_addSecureAppAction:(id)arg1;
- (id)_applicationForAction:(id)arg1;
- (id)_applicationSceneEntityForAction:(id)arg1;
- (void)_enumerateSecureAppActionsByPriorityUsingBlock:(id /* block */)arg1;
- (void)_enumerateSecureAppActionsOfType:(unsigned long long)arg1 usingBlock:(id /* block */)arg2;
- (void)addLockScreenContentAction:(id)arg1;
- (void)addObserver:(id)arg1;
- (bool)hasSecureApp;
- (bool)hasSecureAppOfType:(unsigned long long)arg1;
- (bool)hasWakeDestinaton;
- (id)init;
- (id)newApplicationSceneEntityForCurrentSecureApp;
- (id)observers;
- (id)remoteAlertActions;
- (void)removeObserver:(id)arg1;
- (id)secureAppAction;
- (id)secureAppActions;
- (void)setObservers:(id)arg1;
- (void)setRemoteAlertActions:(id)arg1;
- (void)setSecureAppActions:(id)arg1;
- (id)wakeDestinaton;

@end
