/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSetupRegulatoryInfoViewController : UIViewController {
    UIScrollView * _containerView;
    UIImageView * _regulatoryImageView;
}

- (void).cxx_destruct;
- (void)loadView;

@end
