/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSoundPreferences : NSObject

+ (id)_soundDefaults;
+ (id)calendarAlarmPath;
+ (id)ringtoneIdentifier;
+ (id)ringtonePath;
+ (bool)vibrateWhenRinging;
+ (bool)vibrateWhenSilent;

@end
