/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSpotlightMultiplexingViewController : UIViewController <FBSceneManagerObserver, SBDeviceApplicationSceneStatusBarStateObserver, SBMultiplexedSpotlightDelegate, SBScrollToTopSceneProxyViewDelegate> {
    bool  _activeDelegate;
    UIGestureRecognizer * _dismissReachabilityGesture;
    _UILegibilitySettings * _legibilitySettings;
    UIView * _reachabilityContainerView;
    bool  _reachabilityEnabled;
    SBScrollToTopSceneProxyView * _scrollToTopView;
    unsigned long long  _searchViewPresentationSourceForNextTransition;
    <SPUIRemoteSearchViewDelegate> * _spotlightDelegate;
    SBAppStatusBarSettingsAssertion * _statusBarAssertion;
    SBDeviceApplicationSceneStatusBarStateProvider * _statusBarStateProvider;
}

@property (getter=isActiveDelegate, nonatomic) bool activeDelegate;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) _UILegibilitySettings *legibilitySettings;
@property (nonatomic, readonly) unsigned long long level;
@property (nonatomic) unsigned long long searchViewPresentationSourceForNextTransition;
@property (nonatomic) <SPUIRemoteSearchViewDelegate> *spotlightDelegate;
@property (readonly) Class superclass;

+ (id)sharedRemoteSearchViewController;

- (void).cxx_destruct;
- (void)_acquireStatusBarAssertionIfNeeded;
- (void)_configureStatusBarScrollToTopView;
- (void)_configureStatusBarStateProvider;
- (id)_currentStatusBarSettings;
- (double)_effectiveStatusBarAlpha;
- (void)_invalidateStatusBarAssertionIfNeeded;
- (void)_registerStatusBarScrollToTopView;
- (void)_registerStatusBarScrollToTopViewWithWindow:(id)arg1;
- (id)_spotlightSceneIdentifier;
- (void)_unregisterStatusBarScrollToTopView;
- (void)_unregisterStatusBarScrollToTopViewWithWindow:(id)arg1;
- (void)dealloc;
- (void)didBecomeActiveDelegate;
- (void)didResignActiveDelegate;
- (void)dismissSearchView;
- (bool)isActiveDelegate;
- (id)legibilitySettings;
- (unsigned long long)level;
- (unsigned long long)remoteSearchViewPresentationSource;
- (void)sceneManager:(id)arg1 didCreateScene:(id)arg2;
- (void)sceneManager:(id)arg1 didDestroyScene:(id)arg2;
- (void)sceneWithIdentifier:(id)arg1 didChangeStatusBarAlphaTo:(double)arg2;
- (void)sceneWithIdentifier:(id)arg1 didChangeStatusBarHiddenTo:(bool)arg2 withAnimation:(long long)arg3;
- (void)sceneWithIdentifier:(id)arg1 didChangeStatusBarStyleTo:(long long)arg2;
- (void)scrollToTopSceneProxyViewDidEnterViewHierarchy:(id)arg1 rootedAtWindow:(id)arg2;
- (void)scrollToTopSceneProxyViewWillExitViewHierarchy:(id)arg1 rootedAtWindow:(id)arg2;
- (unsigned long long)searchViewPresentationSourceForNextTransition;
- (void)setActiveDelegate:(bool)arg1;
- (void)setLegibilitySettings:(id)arg1;
- (void)setSearchViewPresentationSourceForNextTransition:(unsigned long long)arg1;
- (void)setSpotlightDelegate:(id)arg1;
- (id)spotlightDelegate;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewWillAppear:(bool)arg1;

@end
