/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSpotlightTransientOverlaySpotlightViewController : SBSpotlightMultiplexingViewController

- (unsigned long long)level;
- (unsigned long long)remoteSearchViewPresentationSource;

@end
