/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBStatusBarManager : NSObject <BSDescriptionProviding> {
    NSHashTable * _hideStatusBarAssertions;
    NSMutableArray * _recycledStatusBars;
    UIWindow * _recycledStatusBarsContainerWindow;
    NSHashTable * _statusBars;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)_removeStatusBarContainer:(id)arg1;
- (id)acquireHideFrontMostStatusBarAssertionForReason:(id)arg1;
- (id)createStatusBarWithReason:(id)arg1;
- (id)createStatusBarWithReason:(id)arg1 withFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg2;
- (id)debugDescription;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)frontMostStatusBarStyleRequest;
- (void)handleStatusBarTapWithEvent:(id)arg1;
- (id)init;
- (bool)isFrontMostStatusBarHidden;
- (void)recycleStatusBar:(id)arg1;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;
- (id)trailingStatusBarStyleRequest;

@end
