/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBStarkNotificationLayout : UICollectionViewLayout {
    UICollectionViewLayoutAttributes * _backgroundAttributes;
    UICollectionViewLayoutAttributes * _notificationAttributes;
    double  _notificationHeight;
    UICollectionViewLayoutAttributes * _previousBackgroundAttributes;
    UICollectionViewLayoutAttributes * _previousNotificationAttributes;
    NSArray * _previousSubActionsAttributes;
    double  _subActionHeight;
    double  _subActionPadding;
    NSArray * _subActionsAttributes;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _subActionsInsets;
    double  _transitionSpacing;
}

@property (nonatomic) double notificationHeight;
@property (nonatomic) double subActionHeight;
@property (nonatomic) double subActionPadding;
@property (nonatomic) struct UIEdgeInsets { double x1; double x2; double x3; double x4; } subActionsInsets;
@property (nonatomic) double transitionSpacing;

- (void).cxx_destruct;
- (id)_indexPathsToDeleteForDecorationViewOfKind:(id)arg1;
- (id)_indexPathsToInsertForDecorationViewOfKind:(id)arg1;
- (id)_transitionAttributesForAction:(long long)arg1 withLayoutAttributes:(id)arg2;
- (struct CGSize { double x1; double x2; })collectionViewContentSize;
- (id)finalLayoutAttributesForDisappearingDecorationElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)finalLayoutAttributesForDisappearingItemAtIndexPath:(id)arg1;
- (void)finalizeCollectionViewUpdates;
- (id)init;
- (id)initialLayoutAttributesForAppearingDecorationElementOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)initialLayoutAttributesForAppearingItemAtIndexPath:(id)arg1;
- (id)layoutAttributesForDecorationViewOfKind:(id)arg1 atIndexPath:(id)arg2;
- (id)layoutAttributesForElementsInRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)layoutAttributesForItemAtIndexPath:(id)arg1;
- (double)notificationHeight;
- (void)prepareForCollectionViewUpdates:(id)arg1;
- (void)prepareLayout;
- (void)setNotificationHeight:(double)arg1;
- (void)setSubActionHeight:(double)arg1;
- (void)setSubActionPadding:(double)arg1;
- (void)setSubActionsInsets:(struct UIEdgeInsets { double x1; double x2; double x3; double x4; })arg1;
- (void)setTransitionSpacing:(double)arg1;
- (bool)shouldInvalidateLayoutForBoundsChange:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (double)subActionHeight;
- (double)subActionPadding;
- (struct UIEdgeInsets { double x1; double x2; double x3; double x4; })subActionsInsets;
- (double)transitionSpacing;

@end
