/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBStartupTransitionToHome : SBBaseStartupTransition

- (void)performTransitionWithCompletionBlock:(id /* block */)arg1;

@end
