/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBStartupTransitionToLoginWindow : SBStartupTransitionToLockOut

- (id)suggestedLockAnimationForTransitionRequest:(id)arg1;

@end
