/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBStarkBannerCell : SBCollectionViewCell {
    SBBannerContextView * _bannerContextView;
    MTMaterialShadowView * _materialView;
    <SBStarkNotificationsConfiguring> * _starkNotificationsConfiguration;
    UIView * _strokeView;
}

@property (nonatomic, retain) SBBannerContextView *bannerContextView;
@property (nonatomic, retain) <SBStarkNotificationsConfiguring> *starkNotificationsConfiguration;

- (void).cxx_destruct;
- (bool)_disableRasterizeInAnimations;
- (id)bannerContext;
- (id)bannerContextView;
- (bool)canBecomeFirstResponder;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)noteDidAppear;
- (void)noteDidDismiss;
- (void)noteWillAppear;
- (void)noteWillDismissWithReason:(int)arg1;
- (void)prepareForReuse;
- (void)setBannerContext:(id)arg1;
- (void)setBannerContextView:(id)arg1;
- (void)setStarkNotificationsConfiguration:(id)arg1;
- (id)starkNotificationsConfiguration;

@end
