/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBStarkNotificationViewController : UIViewController <SBCollectionViewCellDelegate, SBStarkBannerTargetObserver, UICollectionViewDataSource, UICollectionViewDelegate, UIGestureRecognizerDelegate> {
    SBStarkAlertItemBannerSource * _alertItemBannerSource;
    UITapGestureRecognizer * _backGestureRecognizer;
    SBStarkBannerTarget * _bannerTarget;
    UITapGestureRecognizer * _cancelNotificationTapGestureRecognizer;
    <SBStarkNotificationsConfiguring> * _configuration;
    SBStarkBannerCell * _currentCell;
    SBUIBannerContext * _currentContext;
    NSArray * _currentSubActionLabels;
    <SBStarkNotificationViewControllerDelegate> * _delegate;
    UISwipeGestureRecognizer * _dismissNotificationTouchpadSwipeGestureRecognizer;
    bool  _dismissingForSystemGesture;
    bool  _invalid;
    SBStarkNotificationBannerSource * _notificationBannerSource;
    SBStarkNotificationLayout * _notificationsLayout;
    SBCarBannerNotificationView * _notificationsView;
    UITapGestureRecognizer * _selectGestureRecognizer;
    int  _state;
    SBStarkNotificationSystemGestureManager * _systemGestureManager;
    CPSTemplateBannerController * _templateBannerController;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBStarkNotificationViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (setter=_setState:, nonatomic) int state;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_notificationBannerSource;
- (void)_performBackGesture:(id)arg1;
- (void)_performCancelNotificationTapGesture:(id)arg1;
- (void)_performSelectGesture:(id)arg1;
- (void)_performSwipeGesture:(id)arg1;
- (void)_setState:(int)arg1;
- (void)_wheelChangedWithEvent:(id)arg1;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (bool)collectionView:(id)arg1 shouldDeselectItemAtIndexPath:(id)arg2;
- (bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)dealloc;
- (id)delegate;
- (bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (bool)handleMenuEvent;
- (id)initWithConfiguration:(id)arg1 systemGestureManager:(id)arg2;
- (void)invalidate;
- (void)loadView;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setSuspensionReasons:(unsigned long long)arg1 cancellingCurrent:(bool)arg2;
- (void)starkBannerTarget:(id)arg1 didChangeContextWithDismissReason:(int)arg2;
- (int)state;

@end
