/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBStarkNotificationSystemGestureManager : SBSystemGestureManager

- (bool)_shouldEnableSystemGestureWithType:(unsigned long long)arg1;
- (id)initWithConfiguration:(id)arg1;

@end
