/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSwitcherModifierStackSnapshot : NSObject {
    NSArray * _childSnapshots;
    NSString * _modifierName;
    SBSwitcherModifierQuerySnapshot * _querySnapshot;
}

@property (nonatomic, retain) NSArray *childSnapshots;
@property (nonatomic, retain) NSString *modifierName;
@property (nonatomic, retain) SBSwitcherModifierQuerySnapshot *querySnapshot;

- (void).cxx_destruct;
- (void)_enumerateModifierSnapshots:(id /* block */)arg1 stop:(bool*)arg2;
- (id)childSnapshots;
- (void)enumerateModifierSnapshots:(id /* block */)arg1;
- (id)modifierName;
- (id)querySnapshot;
- (void)setChildSnapshots:(id)arg1;
- (void)setModifierName:(id)arg1;
- (void)setQuerySnapshot:(id)arg1;

@end
