/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSwitcherToFullScreenSwitcherModifier : SBTransitionSwitcherModifier {
    long long  _direction;
    SBAppLayout * _fullScreenAppLayout;
    SBSwitcherModifier * _multitaskingModifier;
    bool  _wantsMinificationFilter;
}

@property (nonatomic) long long direction;
@property (nonatomic, readonly) SBAppLayout *fullScreenAppLayout;
@property (nonatomic, readonly) SBSwitcherModifier *multitaskingModifier;

- (void).cxx_destruct;
- (id)appLayoutToScrollToBeforeTransitioning;
- (id)appLayoutToScrollToDuringTransition;
- (long long)direction;
- (id)fullScreenAppLayout;
- (id)handleMainTransitionEvent:(id)arg1;
- (id)initWithTransitionID:(id)arg1 direction:(long long)arg2 fullScreenAppLayout:(id)arg3 multitaskingModifier:(id)arg4;
- (bool)isEffectivelyFullScreen;
- (id)multitaskingModifier;
- (void)setDirection:(long long)arg1;
- (bool)shouldRasterizeLiveContentUntilDelay:(inout double*)arg1;
- (id)transitionWillBegin;
- (bool)wantsMinificationFilter;

@end
