/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSwitcherModifierTimelineEntry : NSObject {
    SBSwitcherModifierActionSnapshot * _actionSnapshot;
    SBSwitcherModifierEventSnapshot * _eventSnapshot;
    SBSwitcherModifierStackSnapshot * _postEventStackSnapshot;
}

@property (nonatomic, retain) SBSwitcherModifierActionSnapshot *actionSnapshot;
@property (nonatomic, retain) SBSwitcherModifierEventSnapshot *eventSnapshot;
@property (nonatomic, retain) SBSwitcherModifierStackSnapshot *postEventStackSnapshot;

- (void).cxx_destruct;
- (id)actionSnapshot;
- (id)eventSnapshot;
- (id)postEventStackSnapshot;
- (void)setActionSnapshot:(id)arg1;
- (void)setEventSnapshot:(id)arg1;
- (void)setPostEventStackSnapshot:(id)arg1;

@end
