/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSwipeUpFloatingSwitcherGestureWorkspaceTransaction : SBFluidSwitcherGestureWorkspaceTransaction

- (long long)_gestureType;

@end
