/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSwitcherSwipeUpGestureFloatingSwitcherModifier : SBGestureSwitcherModifier {
    SBGridSwipeUpGestureSwitcherModifier * _gridSwipeUpGestureModifier;
}

- (void).cxx_destruct;
- (id)handleEvent:(id)arg1;
- (id)initWithGestureID:(id)arg1;

@end
