/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBSwitcherModifierEventSnapshot : NSObject {
    NSString * _eventDescription;
    NSString * _eventName;
}

@property (nonatomic, retain) NSString *eventDescription;
@property (nonatomic, retain) NSString *eventName;

- (void).cxx_destruct;
- (id)eventDescription;
- (id)eventName;
- (void)setEventDescription:(id)arg1;
- (void)setEventName:(id)arg1;

@end
