/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBTetheredRemovalSwitcherModifierEvent : SBSwitcherModifierEvent {
    unsigned long long  _phase;
    NSUUID * _tetheredRemovalID;
}

@property (nonatomic, readonly) unsigned long long phase;
@property (nonatomic, readonly) NSUUID *tetheredRemovalID;

- (void).cxx_destruct;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)initWithTetheredRemovalID:(id)arg1 phase:(unsigned long long)arg2;
- (unsigned long long)phase;
- (id)tetheredRemovalID;
- (long long)type;

@end
