/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBToAppsWorkspaceTransaction : SBMainWorkspaceTransaction <FBSynchronizedTransactionDelegate, SBSceneLayoutWorkspaceTransactionDelegate, SBUIAnimationControllerObserver> {
    SBUIAnimationController * _animationController;
    SBAppRepairTransaction * _appRepairTransaction;
    bool  _applicationStateNeedsCapture;
    NSCountedSet * _completionDelayRequesters;
    bool  _dismissedOverlays;
    SBFloatingDockBehaviorAssertion * _floatingDockBehaviorAssertion;
    bool  _gestureInitiated;
    SBSceneLayoutWorkspaceTransaction * _layoutTransaction;
    id /* block */  _layoutTransitionContinuation;
    unsigned long long  _preactivationForegroundRunningApplicationCount;
    UIApplicationSceneDeactivationAssertion * _resignActiveAssertion;
    bool  _retriedAfterVoluntaryExit;
    bool  _shouldDismissOverlays;
    bool  _toAndFromApplicationsDiffer;
    bool  _touchCancellationDisabled;
    id /* block */  _transitionCompletion;
    bool  _underLockScreenInForeground;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) SBFloatingDockBehaviorAssertion *floatingDockBehaviorAssertion;
@property (nonatomic, readonly) NSSet *fromApplicationSceneEntities;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) SBSceneLayoutWorkspaceTransaction *layoutTransaction;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSSet *toApplicationSceneEntities;

+ (bool)canInterruptTransaction:(id)arg1 forTransitionRequest:(id)arg2;

- (void).cxx_destruct;
- (void)_acquireResignActiveAssertion;
- (void)_animationDidFinish;
- (void)_animationDidRevealApplication;
- (void)_animationWillBegin:(bool)arg1;
- (bool)_beginAnimation;
- (void)_beginAnimationIfNecessary;
- (void)_beginTransition;
- (bool)_canBeInterrupted;
- (void)_captureApplicationState;
- (void)_checkForAnimationCompletion;
- (void)_childTransactionDidComplete:(id)arg1;
- (void)_clearAnimation;
- (void)_completeCurrentTransition;
- (void)_configureAnimation;
- (id)_customizedDescriptionProperties;
- (void)_delayTransitionCompletionForRequester:(id)arg1;
- (void)_didComplete;
- (void)_didInterruptWithReason:(id)arg1;
- (void)_endTransition;
- (void)_fireAndClearResultBlockIfNecessaryForFailure:(bool)arg1;
- (void)_handleApplicationDidNotChange:(id)arg1;
- (void)_handleApplicationUpdateScenesTransactionFailed:(id)arg1;
- (bool)_hasPostAnimationTasks;
- (bool)_hasPreAnimationTasks;
- (void)_logForInterruptAttemptReason:(id)arg1;
- (void)_noteAnimationFinished;
- (void)_performPostAnimationTasksWithCompletion:(id /* block */)arg1;
- (void)_performPreAnimationTasksWithCompletion:(id /* block */)arg1;
- (void)_relinquishResignActiveAssertion;
- (id)_scenesToBackground;
- (unsigned long long)_serialOverlayPreDismissalOptions;
- (void)_setShouldDismissOverlays:(bool)arg1;
- (id)_setupAnimation;
- (bool)_shouldDismissOverlays;
- (bool)_shouldFailForChildTransaction:(id)arg1;
- (bool)_shouldResignActiveForAnimation;
- (void)_stopDelayingTransitionCompletionForRequester:(id)arg1;
- (void)_synchronizeWithSceneUpdates;
- (id)_transitionContext;
- (bool)_transitionWasCancelled;
- (void)_willBegin;
- (void)_willFailWithReason:(id)arg1;
- (void)_willInterruptWithReason:(id)arg1;
- (void)activateApplications;
- (id)animationController;
- (void)animationController:(id)arg1 willBeginAnimation:(bool)arg2;
- (void)animationControllerDidFinishAnimation:(id)arg1;
- (void)animationControllerDidRevealApplication:(id)arg1;
- (id)createSceneEntityForHandle:(id)arg1;
- (void)dealloc;
- (id)floatingDockBehaviorAssertion;
- (id)fromApplicationSceneEntities;
- (id)initWithTransitionRequest:(id)arg1;
- (bool)isFromMainSwitcher;
- (bool)isGoingToCoverSheet;
- (bool)isGoingToLauncher;
- (bool)isGoingToMainSwitcher;
- (id)layoutTransaction;
- (void)performToAppStateCleanup;
- (void)setFloatingDockBehaviorAssertion:(id)arg1;
- (bool)shouldAnimateOrientationChangeOnCompletion;
- (bool)shouldPerformToAppStateCleanupOnCompletion;
- (bool)shouldPlaceOutgoingScenesUnderLockOnCompletion;
- (bool)shouldRestoreSpringBoardContentOnCleanup;
- (bool)shouldWatchdog:(id*)arg1;
- (void)synchronizedTransaction:(id)arg1 didCommitSynchronizedTransactions:(id)arg2;
- (void)synchronizedTransaction:(id)arg1 willCommitSynchronizedTransactions:(id)arg2;
- (void)synchronizedTransactionReadyToCommit:(id)arg1;
- (bool)toAndFromAppsDiffer;
- (id)toApplicationSceneEntities;
- (void)transaction:(id)arg1 didEndLayoutTransitionWithContinuation:(id /* block */)arg2;
- (void)transaction:(id)arg1 performTransitionWithCompletion:(id /* block */)arg2;
- (void)transactionWillBeginLayoutTransition:(id)arg1;
- (double)watchdogTimeout;

@end
