/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBTouchHistory : NSObject <SBGestureRecognizerTouchHistoryProviding> {
    unsigned long long  _depth;
    NSMutableArray * _locations;
    double  _peakSpeed;
    NSMutableArray * _timestamps;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (double)averageTouchPathAngleOverTimeDuration:(double)arg1;
- (struct CGPoint { double x1; double x2; })averageTouchVelocityOverTimeDuration:(double)arg1;
- (id)init;
- (id)initWithDepth:(unsigned long long)arg1;
- (double)peakSpeed;
- (void)reset;
- (int)touchHistoryDepthForTimeDuration:(double)arg1 forComputingDerivative:(bool)arg2;
- (void)updateWithLocation:(struct CGPoint { double x1; double x2; })arg1 timestamp:(double)arg2;

@end
