/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBTransientOverlayDismissToAppsWorkspaceTransaction : SBMainWorkspaceTransaction

+ (bool)isValidForTransitionRequest:(id)arg1;

- (void)_begin;
- (void)_didComplete;
- (void)_sendActivationResultWithSuccess:(bool)arg1;

@end
