/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBTransientOverlayWindow : SBWindow

+ (bool)_isSecure;
+ (bool)sb_autorotates;

- (bool)_canBecomeKeyWindow;

@end
