/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBUIStartupFromBlackAnimationController : SBUIMainScreenAnimationController {
    BSAnimationSettings * _animationSettings;
    UIView * _blackView;
    UIView * _internalContainerView;
    SBSceneLayoutAnimationWrapperView * _layoutWrapperView;
    bool  _waitsForAppActivation;
}

@property (nonatomic, retain) BSAnimationSettings *animationSettings;
@property (nonatomic) bool waitsForAppActivation;

- (void).cxx_destruct;
- (void)_cleanupAnimation;
- (id)_getTransitionWindow;
- (void)_prepareAnimation;
- (void)_setHidden:(bool)arg1;
- (bool)_shouldDismissBanner;
- (void)_showBlackView;
- (void)_startAnimation;
- (bool)_waitsForActivatingSceneContentAvailableIfNecessary;
- (id)animationSettings;
- (id)initWithTransitionContextProvider:(id)arg1;
- (void)setAnimationSettings:(id)arg1;
- (void)setWaitsForAppActivation:(bool)arg1;
- (bool)waitsForAppActivation;

@end
