/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBUserAlertNotificationSource : NSObject <NCNotificationSource, SBAlertItemPresenter> {
    NCNotificationDispatcher * _dispatcher;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NCNotificationDispatcher *dispatcher;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (bool)canPresentMultipleAlertItemsSimultaneously;
- (void)dismissAlertItem:(id)arg1 animated:(bool)arg2 completion:(id /* block */)arg3;
- (id)dispatcher;
- (id)initWithDispatcher:(id)arg1;
- (void)presentAlertItem:(id)arg1 animated:(bool)arg2 completion:(id /* block */)arg3;
- (bool)presentsAlertItemsModally;
- (void)setDispatcher:(id)arg1;

@end
