/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBVoiceDisabledBundles : NSObject

+ (void)setAppDisabledVoiceControl:(bool)arg1 bundleIdentifier:(id)arg2;
+ (bool)voiceControlDisabledByCurrentlyRunningApp;

@end
