/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBVODController : NSObject

+ (id)sharedInstance;

- (void)_launchIPodIfNecessary;
- (void)dealloc;
- (id)init;

@end
