/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBVolumeControlState : NSObject <NSCopying> {
    NSString * _activeVolumeCategoryName;
    bool  _currentRouteHasVolumeControl;
    bool  _isAudioPlayingSomewhere;
    bool  _isFullyMuted;
    bool  _isHostingAppOnLockScreen;
    bool  _isRingerMuted;
    bool  _isShowingLockScreenMediaControls;
    bool  _isUILocked;
}

@property (nonatomic, copy) NSString *activeVolumeCategoryName;
@property (setter=setCurrentRouteHasVolumeControl:, nonatomic) bool currentRouteHasVolumeControl;
@property (setter=setAudioPlayingSomewhere:, nonatomic) bool isAudioPlayingSomewhere;
@property (setter=setFullyMuted:, nonatomic) bool isFullyMuted;
@property (setter=setHostingAppOnLockScreen:, nonatomic) bool isHostingAppOnLockScreen;
@property (setter=setRingerMuted:, nonatomic) bool isRingerMuted;
@property (setter=setShowingLockScreenMediaControls:, nonatomic) bool isShowingLockScreenMediaControls;
@property (setter=setUILocked:, nonatomic) bool isUILocked;

- (void).cxx_destruct;
- (id)activeVolumeCategoryName;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (bool)currentRouteHasVolumeControl;
- (id)description;
- (bool)isAudioPlayingSomewhere;
- (bool)isFullyMuted;
- (bool)isHostingAppOnLockScreen;
- (bool)isRingerMuted;
- (bool)isShowingLockScreenMediaControls;
- (bool)isUILocked;
- (void)setActiveVolumeCategoryName:(id)arg1;
- (void)setAudioPlayingSomewhere:(bool)arg1;
- (void)setCurrentRouteHasVolumeControl:(bool)arg1;
- (void)setFullyMuted:(bool)arg1;
- (void)setHostingAppOnLockScreen:(bool)arg1;
- (void)setRingerMuted:(bool)arg1;
- (void)setShowingLockScreenMediaControls:(bool)arg1;
- (void)setUILocked:(bool)arg1;

@end
