/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBWakeDestination : NSObject {
    NSString * _identifier;
    SBSRemoteAlertDefinition * _remoteAlertDefinition;
    unsigned long long  _type;
}

@property (nonatomic, copy) NSString *identifier;
@property (nonatomic, retain) SBSRemoteAlertDefinition *remoteAlertDefinition;
@property (nonatomic) unsigned long long type;

- (void).cxx_destruct;
- (id)identifier;
- (id)remoteAlertDefinition;
- (void)setIdentifier:(id)arg1;
- (void)setRemoteAlertDefinition:(id)arg1;
- (void)setType:(unsigned long long)arg1;
- (unsigned long long)type;

@end
