/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBWeatherApplicationIcon : SBApplicationIcon

- (void)localeChanged;

@end
