/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBWindowScene : UIWindowScene

- (bool)_windowsIgnoreSceneClientOrientation;

@end
