/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBWorkspaceKeyboardFocusController : NSObject <FBProcessManagerKeyboardFocusDelegate> {
    <BSInvalidatable> * _compatibilityKeyboardFocusRule;
    NSMutableArray * _holdAssertions;
    int  _keyboardFocusPID;
    <BSInvalidatable> * _keyboardFocusRule;
    BKSHIDEventDeferringToken * _keyboardFocusToken;
    NSHashTable * _observers;
    NSMutableArray * _redirections;
    SBMainWorkspace * _workspace;
}

@property (nonatomic, retain) <BSInvalidatable> *compatibilityKeyboardFocusRule;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSMutableArray *holdAssertions;
@property (nonatomic) int keyboardFocusPID;
@property (nonatomic, retain) <BSInvalidatable> *keyboardFocusRule;
@property (nonatomic, retain) BKSHIDEventDeferringToken *keyboardFocusToken;
@property (nonatomic, retain) NSHashTable *observers;
@property (nonatomic, retain) NSMutableArray *redirections;
@property (readonly) Class superclass;
@property (nonatomic, retain) SBMainWorkspace *workspace;

+ (id)new;

- (void).cxx_destruct;
- (bool)_getSceneKeyboardFocusOverridePID:(int*)arg1 token:(id*)arg2;
- (void)_notifyObserversDidUpdateKeyboardFocusPID:(int)arg1 token:(id)arg2;
- (void)addObserver:(id)arg1;
- (id)compatibilityKeyboardFocusRule;
- (id)holdAssertions;
- (id)init;
- (id)initWithWorkspace:(id)arg1;
- (int)keyboardFocusPID;
- (id)keyboardFocusRule;
- (id)keyboardFocusToken;
- (id)lockFocusToSpringBoardForReason:(id)arg1;
- (id)observers;
- (void)processManager:(id)arg1 didSelectKeyboardFocusProcess:(id)arg2 deferringToken:(id)arg3;
- (id)redirectFocusForReason:(id)arg1 fromProcessIdentifier:(int)arg2 fromDeferringToken:(id)arg3 toProcessidentifier:(int)arg4 toDeferringToken:(id)arg5;
- (id)redirections;
- (void)removeObserver:(id)arg1;
- (void)setCompatibilityKeyboardFocusRule:(id)arg1;
- (void)setHoldAssertions:(id)arg1;
- (void)setKeyboardFocusPID:(int)arg1;
- (void)setKeyboardFocusRule:(id)arg1;
- (void)setKeyboardFocusToken:(id)arg1;
- (void)setObservers:(id)arg1;
- (void)setRedirections:(id)arg1;
- (void)setWorkspace:(id)arg1;
- (void)updateKeyboardFocusDeferringRules;
- (id)workspace;

@end
