/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBZoomView : UIView {
    UIView * _contentView;
    UIStatusBar * _statusBar;
}

@property (nonatomic, readonly) UIView *contentView;
@property (nonatomic) UIStatusBar *statusBar;

+ (id)_chromeStatusBarImageForInterfaceOrientation:(long long)arg1;

- (void).cxx_destruct;
- (id)_initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (bool)_shouldAnimatePropertyWithKey:(id)arg1;
- (id)contentView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setStatusBar:(id)arg1;
- (id)statusBar;

@end
